### ISSUE TITLE
[Solution (?)] 'utf8' codec can't decode byte 0xe3 in position 1265: invalid continuation byte

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#101]
http://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte

>Your file doesn't actually contain utf-8 encoded data, it contains some other encoding. Figure out what that encoding is and use it in the open call.
>In Windows-1252 encoding for example the 0xe9 would be the character é.
-Mark Ransom (From that Stack Overflow link)

I believe this means Hydrus is lacking support for this Hiragana character: ゛(utf-8 encoding).
http://www.fileformat.info/info/unicode/char/309b/index.htm
http://www.fileformat.info/info/unicode/char/309b/browsertest.htm

Hope that helps.

**Comment by eider-i128** [comment]
Hi, this bug report is meaningless without traceback so dev can actually know where in code problem exists.

**Comment by HASJ** [comment]
Sorry for that.
```
The following exception occured at 2015/11/18 06:46:43:
Database Error!
'utf8' codec can't decode byte 0xe3 in position 1265: invalid continuation byte
Unknown Caller, probably GUI.
Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusDB", line 198, in _ProcessJob
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 6689, in _Write
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 5050, in _SetJSONDump
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json", line 243, in dumps
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json.encoder", line 207, in encode
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json.encoder", line 270, in iterencode

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 1265: invalid continuation byte
```

**Comment by eider-i128** [comment]
Did you ever encountered this problem before, or it happens only in version 182?

For the developer, it indeed seems that data parsed by **json.dump** is not encoded in UTF-8. I think using **UnicodeDammit** should fix that problem. http://www.crummy.com/software/BeautifulSoup/bs3/documentation.html#Beautiful%20Soup%20Gives%20You%20Unicode,%20Dammit

**Comment by HASJ** [comment]
I've been running into it since v180, the first version I installed.
Slightly different position now:
```
Database Error!
'utf8' codec can't decode byte 0xe7 in position 1247: invalid continuation byte
Unknown Caller, probably GUI.
Traceback (most recent call last):

  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusDB", line 198, in _ProcessJob
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 6689, in _Write
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 5050, in _SetJSONDump
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json", line 243, in dumps
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json.encoder", line 207, in encode
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json.encoder", line 270, in iterencode

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 1247: invalid continuation byte
```

**Comment by hydrusnetwork** [comment]
Catching up on your other reports, this seems to be a problem dumping the session to the database, which the client does every five minutes or so. Is that hiragana in a queued search query on a download page?

I recently did a big rewrite to handle unicode better, but it is proving a continuing pain. json.dumps( serialisable_object ) should be able to _take_ unicode strings ( e.g. json.dumps( u'\u309b' ) ), but it will output a bytestring that is suitable for network transmission or database storage. json.loads does the opposite--bytestring->unicode. I suspect this hiragana is getting converted to a bytestring in the wrong order or something similar and the final json step is thus getting something it is not expecting.

I cannot reproduce the error on my end however. If I have japanese characters as pending search queries or even the names of pages, it saves and loads no problem. Where have you entered japanese characters? Have you entered any very complicated kanji that might be utf-16 rather than utf-8? Also, is your computer English or another language?

I have improved this specific error for next week to explicitly print the information it is trying to dump to the log. Once you update to v186, please post the new information that will be written to your log so we can see exactly what is trying to be dumped. (It _should_ be dumpable to the log, lol, but let me know if it causes a new error!)

**Comment by HASJ** [comment]
What's weird is that I never had any query using that character before and also don't think there's any tag that uses it.

I can't do what you said right now because of #122.

**Comment by HASJ** [comment]
>Where have you entered japanese characters? Have you entered any very complicated kanji that might be utf-16 rather than utf-8?
Nope. Like, at all. This started to happen before I even tried to use pixiv.

>Also, is your computer English or another language?
PT-BR.

Recently ran into some problems with another program which I think are similar to this. It was with youtube-dl and my Windows character encoding, which is using cp-1252. It was displaying accented characters (very common in languages of Latin heritage) like á Á é É and so on completely wrong. Had to change the youtube-dl config file (which is a simple txt file) to ANSI encoding and it was fixed.
Dunno if that helps. Most likely not...

My Windows is using that cp-1252 encoding and I do not know how to change it (nor does the internet, apparently). It should be using utf-8, right?

At first I though this was related to how long the client was running but it's been 10 hours now and not a single error.
I started following your advice in #96 to remove the thumbnails and that GREATLY sped up the client and no decode error to be seen so far. Even the GUI hangs are gone. I'll give further report in that issue.

**Comment by ScoreUnder** [comment]
>Have you entered any very complicated kanji that might be utf-16 rather than utf-8?

I just want to say utf-8 and utf-16 are fully compatible with each other in terms of the characters they support (not in how they represent them as bytes of course), so please don't try changing everything to utf-16 because it will be a lot of effort in vain!

A related issue (which I doubt is coming into play but might be nice to check): python internally uses either UCS-2 or UCS-4 to store strings. UCS-2 versions use half the memory for every string, but can't represent some unicode characters at all in their unicode() strings. You can use `sys.maxunicode` to find out which version you have. If it equals 0x10FFFF, then it is using UCS-4 and supports all of unicode. If it equals 0xFFFF, then it is using UCS-2 and does not. UCS-2 versions will only support characters in the [Basic Multilingual Plane][1]. Things like emoji (and as you say, many CJK ideographs) aren't supported by this.

On both python 2 and python 3 on my machine (the stock packages that come with Arch Linux) I have the "wide builds", which support the full unicode range and use UCS-4. However I've [seen in some (old) article online][2] that the "default" somewhere (not sure where) is a narrow build which does not fully support unicode.

Would it be worth checking this and warning about it in Hydrus?

---

All that said, with an error message like "Invalid continuation byte" I'd suspect the site itself is serving up corrupt text (or text encoded in some other encoding).

Your best bet in that case would be to use one of python's extra options to decode(), e.g. `thing.decode("utf-8", "replace")`. This would replace the character with some glyph indicating it's corrupted, but otherwise continue decoding normally. I think you'd have to warn if you did that though.

[1]: https://en.wikipedia.org/wiki/Plane_(Unicode)
[2]: http://wordaligned.org/articles/narrow-python

**Comment by HASJ** [comment]
>All that said, with an error message like "Invalid continuation byte" I'd suspect the site itself is serving up corrupt text (or text encoded in some other encoding).

I know that Sankaku Chan has a lot of tags in both english and japanese, could that be cause?

**Comment by hydrusnetwork** [comment]
Thank you for continuing here--it turns out some janky error was putting an invalid byte into the notes section of the import cache, and it couldn't be serialised. See #125

**Comment by hydrusnetwork** [comment]
This seems to be fixed. I wasn't converting error messages to unicode, so some cp1252 characters in one of your errors were causing problems in the json library's dumper, which couldn't handle the translation.

BTW, my Windows uses cp1252 as well--it seems to be the generic 'Western' encoding. That's true for both my Win 7 and Win8.1 machines--I would hope Windows 10 fixes that, but perhaps it is a python thing, rather than an OS thing.

Thank you @ScoreUnder for all the unicode info! It absolutely boggles my mind why this stuff is such a pain--I feel like they should have fixed every string library about ten years ago to Just Work™. Maybe we are hitting that time now.

I will close this issue now. Please reopen if you get anything new in v187.
