### ISSUE TITLE
"gelbooru favorites by user id" downloader deletes favorites it has downloaded

### ISSUE THREAD

**Issue by docchaoswizard** [hydrusnetwork/hydrus#1023]
### Hydrus version

464

### Operating system

macOS 11 "Big Sur" (Intel)

### Install method

Extract

### Bug description and reproduction

I was playing around with the downloader "gelbooru favorites by user id" for a friend of mine and noticed a worrisome behavior.  
The downloader first downloads the file(s) (Query-String: `id=<idOfPicture>,page=post,s=view`) (Link 1) after all files are downloaded it then does query again, this time with Query-String `id=<idOfPicture>,page=favorites,s=delete` (Link 2) which indeed does delete the file from your favorites if your logged in. This action is noted with status "ignored". So you always have a 50/50 split, e.g `18 - 9Ig`

It notes in the file log "Looks like HTML -- maybe the client needs to be taught how to parse this?", i would say it indeed does need to be taught this. 

Here is a pair of semi-SFW sources:

1. https://gelbooru.com/index.php?id=5768753&page=post&s=view
2. https://gelbooru.com/index.php?id=5768753&page=favorites&s=delete
 
Are there any additional informations you need? Is there something i can do to help?

Best regards,
Doc

**Comment by Chad90b** [comment]
@docchaoswizard i can confirm this unexpected behavior occurs and does in fact result in deleting favourites from your logged-in gelbooru account

**Comment by Chad90b** [comment]
@docchaoswizard a method to solve this has been suggested to hydrusdev. if he sees it early enough we might have a new default preset for next release that fixes this.
if that is the case, after upgrading to the next version of hydrus, you can upgrade the parser by doing the following:

navigate through **network** -> **downloader components** -> **manage parsers**
look for `gelbooru 0.2.x gallery page parser` and delete it.

from the bottom right corner, click **add defaults** -> **select from a list**
look for `gelbooru 0.2.x gallery page parser`. add a checkmark on it and click **apply**

this will only have an effect if and when the gelbooru default is updated.

as a possible temporary workaround for you: ||edit the parser `gelbooru 0.2.x gallery page parser` click the tab **content parsers* -> select **file page urls old** and click **edit** -> click **edit formula** at the bottom -> click the bottom leftmost button that ought to say ***no string processing*** -> click **add** -> **string converter** -> click **add** and select conversion type **regex substitution**

in the field **regex pattern:** replace the text `extra text` (delete it all) and paste in only this: `&s=delete`
leave all other fields blank.
click apply (about 7 times to close all windows) and open a new hydrus tab to test this fix.||

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am very sorry for the trouble. Thank you @Chad90b also for figuring out the problem area here too.

I presume and hope that this is due to a recent change in gelbooru's markup, and not something that has been true for ages. I don't remember who wrote this parser originally, but I can't imagine they made and submitted it with this problem originally.

I will roll out an update to the parser tomorrow to all users that will ensure it skips any url with '&s=delete' text in it.

Please let me know if you have any more trouble here. If you still have the problem downloaders open, if you click on the file log button and select the good urls, you should be able to _right-click->open sources_ to open them in your browser again.

You can alternately select the thumbnails and _right-click->known urls->open->gelbooru file page urls_. If you don't have the downloaders still up, maybe you can narrow down on those files again by searching for something like:

system:time imported<7 days ago
system:time imported>3 days ago
system:known url: has gelbooru file page url

And then spam re-favourite them on the site.
