### ISSUE TITLE
API Converters and URL Associations Behave Differently

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#1036]
### Hydrus version

467

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

As of a few versions ago (I believe 464 or 465), URL associations when dealing with URL classes with API converters no longer behave in the same way they used to.

Previously, if a URL class with an API converter was marked to associate a url, but the resulting API URL class was not, the pre-conversion URL would be associated with the resulting files, while the API URL would not.

As of the past few versions, this is no longer the case. Now, no URLs are associated with resulting files unless the final (API) URL class is marked to associate URLs, regardless of individual class settings.

**Comment by floogulinc** [comment]
This may be related, I have an api parser for posts that produces a post url as an associable, that post url has an api conversion to an api url. When the API parser for either the gallery or individual post API gets the file, the post url isn't set as a source url. Both the post url class and api post url classes are set to associate urls.

**Comment by Zweibach** [comment]
Sounds like it could be related to a change that was made some time ago with URL redirects?

**Comment by hydrusnetwork** [comment]
Thank you for this report. I will investigate this and try to do a mix of restoring old behaviour and making it work actually how you want as a human. I suspect some recent filtering I did for primary and source urls is causing this, it is not intentional.

In this vein, an extension I really want to do is an url class that says 'hey, I am an alternate way of expressing this other url class', for instance converting pixiv urls from the old type to the new. A bit like an API class but it converts the front-facing URL the user sees to the other format, rather than secretly hitting and parsing another in the background. Basically a url class 'sibling'.

**Comment by Zweibach** [comment]
@hydrusnetwork #505

**Comment by hydrusnetwork** [comment]
Thank you again. I have implemented an improvement for tomorrow that I hope fixes this.

Unfortunately I was unable to reproduce this issue exactly. If I grab a Deviant Art page, it looks up data with the API and associates the Post URL and the File URL. The Post URL Class is set to associate, the API URL Class is not. Looking through the code, I do not believe the API URL would ever be associated here--when I do the 'fetch this api url instead' bit, I never actually save that API URL to the file import object, since I always assume an API URL is not something a user wants. I think you have to hit an API URL directly in the downloader (i.e. it is the listed 'source' in the file log UI) to get it to try to associate, if set in the URL Class to do so.

However @floogulinc 's issue I think I can explain, so if your downloader does similar--where an API URL is either hit first, or it tries to add a post url as an associable through parsing--I think that could disappear that Post URL. I made a change recently that if you try to add via parsing a 'source' url with the same domain as a primary url, it would be skipped (this was to stop boorus that reference a file alternate through their 'source' field):

https://github.com/hydrusnetwork/hydrus/blob/master/hydrus/client/importing/ClientImportFileSeeds.py#L150

So my guess is if a Post URL is added after the API URL, and they share domains, then the Post URL is being lost.

So! This is complicated, and I don't think there is a perfect solution with our current tools, but if I upgrade that 'discard source url' test to work on URL Classes rather than domains (i.e. you can't associate a source url if it shares the URL Class of a Primary URL that was hit during download), I hope that'll improve this situation.

Let me know how you get on! If this doesn't fix your situation @GoAwayNow , can you walk me through a more specific example of how this is failing for you? Which order are the URLs parsed, what's actually being checked by the network engine and what's being parsed?
