### ISSUE TITLE
MPV is not available!

### ISSUE THREAD

**Issue by Alpha5361** [hydrusnetwork/hydrus#1040]
### Hydrus version

467

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Manjaro Linux x86_64
AUR package

### Bug description and reproduction

Hydrus Client displays a thumbnail, but no video in both the preview window, and the media window. The only information I could get out of the Hydrus Client is the `MPV is not available!` error from the client.log file.

The steps I took to get this error were to

- update my system
- update Hydrus through the AUR from, v466 to v467

and then MPV stopped working for all aplicable media files.

### Log output

```text
v467, 2022/01/03 11:58:51: hydrus client started
v467, 2022/01/03 11:58:52: booting controller…
v467, 2022/01/03 11:58:52: booting db…
v467, 2022/01/03 11:58:52: checking database
v467, 2022/01/03 11:58:52: preparing db caches
v467, 2022/01/03 11:58:52: initialising managers
v467, 2022/01/03 11:58:52: booting gui…
v467, 2022/01/03 11:59:03: MPV is not available!
v467, 2022/01/03 11:59:05: MPV is not available!
v467, 2022/01/03 11:59:07: MPV is not available!
v467, 2022/01/03 12:07:38: MPV is not available!
v467, 2022/01/03 12:08:16: shutting down gui…
v467, 2022/01/03 12:08:16: waiting for managers to exit
v467, 2022/01/03 12:08:17: waiting for daemons to exit
v467, 2022/01/03 12:08:17: waiting for twisted to exit
v467, 2022/01/03 12:08:17: shutting down db…
v467, 2022/01/03 12:08:17: saving and exiting objects
v467, 2022/01/03 12:08:18: cleaning up…
v467, 2022/01/03 12:08:18: shutting down controller…
v467, 2022/01/03 12:08:18: hydrus client shut down
```

**Comment by shimmeringpenny** [comment]
Oh Rip

**Comment by Alpha5361** [comment]
Is there nothing I can do to help fix this with the client the way it is? Sorry about the absence of details. I didn't keep close track of what I was doing at the time it stopped working.

**Comment by hydrusnetwork** [comment]
Hey, I am sorry for the trouble here. Normally the AUR release doesn't run into this sort of trouble since it is running from source, but it seems there have been several software updates that end that have caused trouble.

If you hit _help->about_, you will get more information about why MPV failed to import. What does it say? If libmpv1 recently updated or python-mpv did, then I know that can sometimes cause trouble. Basically some versions just don't know how to talk to each other because of some API difference. Our frozen (Ubuntu) Linux release build is locked to python-mpv 0.4.5 for this reason. I do not make the AUR build though so I can't talk too cleverly about the choices it makes.

Although it sucks to say, a temporary patch for now is to hit _options->media_ and switch your animation/video to the 'native viewer', which is my slow audioless software solution. At least you'll see something until this can be fixed.

**Comment by Alpha5361** [comment]
I did not know that was a feature. It gave me this traceback.

```
v467, 2022/01/04 21:44:33: booting gui…
v467, 2022/01/04 21:44:50: If this information helps, MPV failed to import because:
v467, 2022/01/04 21:44:50: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/client/gui/ClientGUIMPV.py", line 25, in <module>
    import mpv
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'mpv'

v467, 2022/01/04 21:45:04: Physically deleted 6 files and 6 thumbnails from file storage.
v467, 2022/01/04 21:50:16: shutting down gui…
```

**Comment by freedg** [comment]
Python recently updated to 3.10, python-mpv needs to be updated/reinstalled/rebuilt for it to be present for 3.10.

**Comment by hydrusnetwork** [comment]
@Alpha5361 Hey, I am sorry for getting back late here--were you able to fix this, and/or if you use a package like the AUR, did that update things for you? It looks like your error is related to python-mpv actually being missing, as freedg says, so however your third-party package is putting your environment together, it needs to get a new version of the package for python 3.10.

If you are running from source with your own thing, you'll need to get the new python-mpv using pip as you did for 3.9 or 3.8.

If this is all sorted now, please feel free to close the issue!

**Comment by soxhime** [comment]
Also Manjaro user here installing from AUR using yay, all I did reinstall python-mpv with `yay -S python-mpv`. When prompted with `Packages to cleanBuild? ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)` I responded with [A]ll and it's worked fine since.

You should pay attention to the [Manjaro forum posts about the latest stable releases](https://forum.manjaro.org/t/stable-update-2022-01-23-opensearch-kernels-kde-software-cinnamon-pipewire-mesa-gnome-libreoffice), they are specifically telling everyone that "you may need to rebuild any Python packages you’ve installed from the AUR"

**Comment by Alpha5361** [comment]
Sorry for ghosting this bug report for a month. I updated python-mpv from the aur as @soxhime instructed and in-client video playback started working again. I'm closing the issue because the client is working as desired. Thanks for the help.
