### ISSUE TITLE
Sort by import time doesn't always work properly

### ISSUE THREAD

**Issue by GreenLandisaLie** [hydrusnetwork/hydrus#1061]
### Hydrus version

v473

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

When files are imported within a very short amount of time between each other, hydrus will register the exact same timestamp for them. [Screenshot](https://i.imgur.com/hRYCGVY.png)
When this happens, search results sorted by import time will randomly order such files - this makes it impossible to read manga and such through the API  even when the files were actually imported in the correct order.

A possible solution would be to establish an absolute minimum amount of time between imports so that every file will have its own unique timestamp.
Also I'm aware we can just tag files with enumerable tags (ex: page:1, ...) but as far as the client API goes we can't yet take advantage of that - unless I missed something.

**Comment by floogulinc** [comment]
The best option for comics right now is indeed page number tags since sometimes you can't even rely on things being imported in a certain order. Currently there is sorting in the file search API but it can't yet sort by namespace (see #1062). For now in your applications using the API I would recommend sorting by namespace yourself on the client after getting the tags for all the files in the search since generally for an individual comic there are few enough files for this to be feasible.

**Comment by GreenLandisaLie** [comment]
@floogulinc 
Yeah its probably best to not change the way timestamps are assigned as to not either unnecessarily increase the size of the .db or potentially, massively increase importation time on huge simultaneous/parallel imports.
After thinking about it I believe sorting by namespace is really the only way to go. I will close this issue in favor of yours.

**Comment by stysmmaker** [comment]
I'd like to point out this isn't really an issue specific to comics -- for example, files that have been saved to disk in bulk will likely have the same modified date if they were saved in quick succession. This problem amplifies itself further if it's a set of files saved within a few seconds, where within that timestamp the files will end up being randomly sorted. This issue even applies to the time when files were archived in the system. Since Hydrus imports files in a consistent way (I believe by sorting on filename), I think it's safe to expect that sorting should be consistent for these files too.

This doesn't require any DB work to fix though. Perhaps kind of a hack-y fix, but since the file IDs increment in order consistently based on when they were imported, appending `+ x.GetHashId()` to these lines after the `deal_with_none` function resolves it and still maintains the desired sort:

https://github.com/hydrusnetwork/hydrus/blob/a09ab839633661f446612a92b680bb8118a46b39/hydrus/client/media/ClientMedia.py#L3016
https://github.com/hydrusnetwork/hydrus/blob/a09ab839633661f446612a92b680bb8118a46b39/hydrus/client/media/ClientMedia.py#L3023
https://github.com/hydrusnetwork/hydrus/blob/a09ab839633661f446612a92b680bb8118a46b39/hydrus/client/media/ClientMedia.py#L3034

I don't believe this should impact the current speeds of sorting on these keys.

**Comment by GreenLandisaLie** [comment]
@stysmmaker Sry only noticed your message now (19 days later -.-). Reopened.

**Comment by Zweibach** [comment]
This is working as intended though clearly not as desired. Open a feature request.

**Comment by bbappserver** [comment]
### Clarification of Working as Intended
Hydrus does not trust HTTP `Last-Modified` in the way it does not trust `Content-Type`, because Hydrus, has mutliple downloaders running it my write files out of order if say you have a subscription that gets the gallery in order, but you send a post file that is one of those galleries elements, or some of those galleries elements have previously shown up on a booru you already downloaded.

There is no way to distinguish this.  There is an open issue to trust the post time in the parser for some parsers such as those for art gallery services (e.g. Deviantart) where the date would be fairly authoritative, and to choose the oldest post date as long as it seems sane for such parsers.  However modified timestamps will necessarily be unhelpful some of the time, because they represent modified time, not ideal published time.
