### ISSUE TITLE
Total bandwidth status bar glitching out

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1068]
### Hydrus version

473

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

1. Have something downloaded in session
2. If applicable rounding method goes BRRRRRR as shown:

![](https://i.imgur.com/38CFC6I.gif)
(Obviously nothing is downloading in background and number will keep on changing)

Might be related to #1028

**Comment by hydrusnetwork** [comment]
Thank you for this great report! It turns out the way I do my new 'how precise should we write this number?' method, which figures out 12345 -> 12.1KB, was setting a global precision variable in the library I use for these calculations. For an unlucky number like 188213746 (179.495MB), that lead down two different code paths that set that precision variable differently, and flipped between the two on subsequent calls. I think this will have happened on any number that was around x9.49, maybe x9.4.

This should be fixed for tomorrow, let me know if you still have trouble.
