### ISSUE TITLE
Error when choosing rclone mount as database location

### ISSUE THREAD

**Issue by RafeeDaBoy** [hydrusnetwork/hydrus#1084]
### Hydrus version

v474

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

When I select my rclone mount as the database location, it always gives out an error message and doesn't work.
Trying to launch the client as admin, doesn't fix it either.
Mount working as download location for other programs like gallery-dl, yt-dlp as normal.

### Log output

```text
v474, win32, frozen
OSError
[WinError 1005] The volume does not contain a recognized file system.
  File "hydrus\client\gui\widgets\ClientGUICommon.py", line 235, in EventButton
    self._func( *self._args,  **self._kwargs )
  File "hydrus\client\gui\ClientGUIScrolledPanelsReview.py", line 790, in _SelectPathToAdd
    self._AddPath( path )
  File "hydrus\client\gui\ClientGUIScrolledPanelsReview.py", line 184, in _AddPath
    path = os.path.realpath( path )
  File "ntpath.py", line 651, in realpath
  File "ntpath.py", line 601, in _getfinalpathname_nonstrict

Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'C:\\.Mount\\gallery'
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am afraid I am not familiar with rclone, so I cannot talk too expertly on why this is happening, but this is a core python call failing here--basically I ask it to normalise any symlinks etc... in the path before adding it as a location for file storage.

Some searching around for the error code produced these very similar tracebacks:
https://forum.rclone.org/t/oserror-winerror-1005-the-volume-does-not-contain-a-recognized-file-system/28112/5
https://github.com/quodlibet/quodlibet/issues/3354
https://github.com/SickChill/SickChill/issues/6876
https://github.com/gcovr/gcovr/issues/365

So my guess is python just can't do a 'realpath' on an rclone mount, or maybe common permission setups stop it from resolving something. Since the mount is a clever online mount, maybe trying to get a 'real' path from it is not an appropriate thing to do anyway.

In any case, I only do this realpath check in file storage when you add a file or thumbnail location, just a safety thing. What I'll do here is if the path you add fails this realpath normalisation, I'll throw up a warning dialog talking about it and let you continue with the path as given. I assume for all other basic file system operations this mount is fine, but I can't promise anything, so please make a backup and test this out for me and let me know if there are any more problems!
