### ISSUE TITLE
Media rotation not handled properly in some cases

### ISSUE THREAD

**Issue by stysmmaker** [hydrusnetwork/hydrus#1124]
### Hydrus version

481

### Operating system

Windows 11

### Install method

Running from source

### Bug description and reproduction

In some cases, the rotation of both images and video is not handled correctly.

For images, when an ICC profile is embedded, the EXIF rotation is ignored. There's several examples of this in the [initial commit of the recurser/exif-orientation-examples repository](https://github.com/recurser/exif-orientation-examples/commit/c14b77886806f19fc80705cedc102d1a8b08c1f2), which each have an ICC profile embedded ([and later removed due to copyright](https://github.com/recurser/exif-orientation-examples/releases/tag/v1.0.2)).

For videos, when there's a rotate flag, the thumbnail becomes stretched either horizontally or vertically depending on the aspect ratio, and black bars are created in the media viewer to compensate (since mpv displays the video correctly). There's some examples of this [here](https://github.com/KhronosGroup/WebGL/tree/main/sdk/tests/resources) ('video-rotation' files). This seems to be consistent with any file I've tested it on so the rotate flag can be applied via ffmpeg if more test examples are needed.

**Comment by hydrusnetwork** [comment]
Thank you for this report and the example images! I had a very similar set of test images, I think from the same project, but they didn't have ICC Profiles. With the new ICC Profile code in hydrus, a different image loading routine is used, exposing this issue.

Also, it turns out I had this fixed already, but the EXIF rotation code wasn't plugged in due to a typo! I have fixed it for 483. Hydrus should notice any images that have been 90-degree rotated as soon as they appear as thumbnails and fix them automatically within a few seconds. Anything flipped or 180-degree rotated will not be automatically fixed, but given these are far rarer, I won't give everyone a huge maintenance job to scan for them.

If you would like to force-fix them all quickly, please schedule a 'regenerate file metadata' and 'regenerate thumbnail' call for all jpegs with ICC Profile under _database->file maintenance_, or if you know the affected files, hit _manage->regenerate_ on their thumbnail right-click menus. If you are willing to wait, I'm fairly certain we'll have searchable Exif data one day, which will allow more targeted and efficient maintenance routines for this sort of stuff.

Please let me know if you have any more trouble.

**Comment by boobayayo** [comment]
@hydrusnetwork As far as I can tell there is still an aspect ratio issue with videos that have rotation metadata (like [this one](https://github.com/KhronosGroup/WebGL/blob/main/sdk/tests/resources/video-rotation-90.mp4) linked above.

For thumbnails the rotation is correct, but it gets squished into the un-rotated aspect ratio.
The embedded mpv player also rotates properly and does not distort the file but is resized to the wrong aspect ratio which results in (potentially huge) black bars.
