### ISSUE TITLE
MacOS no audio when playing videos

### ISSUE THREAD

**Issue by tbennett6421** [hydrusnetwork/hydrus#1132]
### Hydrus version

481

### Operating system

macOS 11 "Big Sur" (Apple silicon)

### Install method

Installer

### Install and OS comments

install via disk image (dmg)

### Bug description and reproduction

no audio when playing videos in hydrus. Has not worked since install. There is no audio output on either the preview player or the full player

**Comment by roachcord3** [comment]
This isn't a bug with hydrus, but a bug with how the mpv library works with Qt on macOS. https://github.com/jaseg/python-mpv/issues/61

Normally, hydrus video playback uses mpv, but on macOS, mpv can't work, so it's disabled, and some legacy player code that doesn't have audio support runs instead.

**Comment by tbennett6421** [comment]
Is there no workaround to install/load mpv via homebrew or an alternative player?

**Comment by roachcord3** [comment]
It doesn't matter how you install mpv, it won't work because of the linked issue. To resolve this issue, someone needs to implement a workaround _somewhere_, so it's gonna require some programming. Unfortunately, I tried to take a crack at it a while ago, but I have absolutely zero experience with Qt and macOS GUI programming so I got nowhere. The owner of this project knows about this limitation and that's why the macOS build disables mpv, but I think he is also in no place to go fix the underlying bug in the third party libs. So we're probably screwed unless someone who does know what they're doing takes interest in fixing it, or one of us teaches himself enough to fix the bug on his own, lmao

**Comment by HerveKuate** [comment]
I asked help on discord, thanks for the advice.

**Comment by hydrusnetwork** [comment]
@roachcord3 thank you for this information about python-mpv on macOS. What a shame. I had spent a bunch of time trying to get mpv built into the macOS App, having mixed success and knowing there was a 100% CPU problem still to solve, and it seems like that second problem is more serious. There are some interesting ideas in that python-mpv thread on how to get around this with subprocess, so I've recorded that stuff for now and will think about it when I revisit this topic.

I am going to close this issue for now. Hope to have proper mpv support on macOS in future, but for now it just seems a no-go.
