### ISSUE TITLE
Can't zoom out of max zoom level

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#116]
When zooming in on an image in the built-in viewer, after zooming to the max zoom level it's impossible to zoom out.

**Comment by hydrusnetwork** [comment]
I can't reproduce this, but if I try hitting 2000% on anything bigger than about 400x400, my client hangs and my memory use explodes. Do you get anything like that? Does it happen reliably for you for many sorts of images, or does one in particular do it? I remember some problem a little while ago where particular resolutions were causing problems because they were an exact multiple of some zoom ratio or something, and it hit a < vs <= logic typo.

Writing tiling zoom code to handle big zooms is on the vote list to handle this better, btw.

**Comment by ScoreUnder** [comment]
I think I may have mis-reported this.

Looking at it again it looks like I just hit a very high zoom level (not always maximum) and the image viewer grinds to a halt, not letting me zoom out or do anything at all. Telling it to close of course lags for some time too. It uses about 110% CPU while this is happening, but the RAM doesn't increase by any noticeable amount unless the image was already kind of large (in which case it increases by crazy amounts, taking several gigabytes).

It's surprising to me that it takes so long to zoom. I might look into profiling that if I can, and I'll get back with the results if that comes up with anything unusual.

**Comment by ScoreUnder** [comment]
Oh no I've found what originally prompted me to report this (along with the other GIF bug).

If you zoom a gif until it fills the viewer, you can't zoom out. No lag, no high memory usage, and it keeps playing, but it just won't zoom.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
