### ISSUE TITLE
Some windows have extremely tiny font on dual-monitor setup 

### ISSUE THREAD

**Issue by DeutscheGabanna** [hydrusnetwork/hydrus#1175]
### Hydrus version

488

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

![image](https://user-images.githubusercontent.com/59067099/173782364-cb9bbb9f-eecb-4c76-8bb7-51c780298242.png)
![image](https://user-images.githubusercontent.com/59067099/173782409-d6c09913-4499-42ee-a555-3d46d59bb28b.png)

The problem persists regardless of whether:
- I move the window to the laptop screen or the big PC screen
- I start the program with laptop screen closed
- I move the entire hydrus main window (not just the pop-up) to the laptop screen or big PC screen

**Comment by floogulinc** [comment]
Some parts of Hydrus will scale based on what the display scaling of the primary display was when you signed in to Windows and it very much does not handle moving between scaling levels well. If your primary display has changed I'd suggest signing out and back into your windows account before opening Hydrus.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry for the trouble--font scaling is limited at the moment. Please check out the 'Fixed Font Size Example.qss' file in install_dir/static/qss. You can force a certain font size by copying and editing that, and then setting it in _options->style_.

I am hoping some of this tech will work more fluidly and naturally when we move from Qt5 to Qt6 this year, since all this is _supposed_ generally to all be teed off by the OS and UI library without me doing much. In either case, that QSS solution, while ugly, does work, so I'd also like to make it more powerful and easier to use in future.

If the QSS fixes you for now, please close this issue, and we'll revisit this topic when we try out Qt6 and see if monitor transitions work a little better.
