### ISSUE TITLE
Some files fail to export on Linux due to path errors

### ISSUE THREAD

**Issue by jkendall327** [hydrusnetwork/hydrus#1194]
### Hydrus version

490

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Pop!_OS 22.04 LTS

My Hydrus install is on an encrypted Veracrypt drive. The folders it is exporting to are on the same drive.

### Bug description and reproduction

When running 'file -> import and export folders -> run export folder now -> run all', some files fail to export with the error given below. Given the mention of HydrusPaths.py, I suspect this is due to the filenames not being escaped properly? More specifically it seems to be with the `shutil.copy2` method, which deals with copying metadata.

This happened with multiple files, all of which contained characters such as colons (:), quote marks (") and at-signs (@) alongside parentheses.

### Log output

```text
v490, linux, frozen
OSError
[Errno 22] Invalid argument: '[filename here]'
Traceback (most recent call last):
  File "hydrus/core/HydrusPaths.py", line 609, in MirrorFile
    safe_copy2( source, dest )
  File "hydrus/core/HydrusPaths.py", line 490, in safe_copy2
    shutil.copy2( source, dest )
  File "shutil.py", line 435, in copy2
  File "shutil.py", line 264, in copyfile
OSError: [Errno 22] Invalid argument: '[filename here]'
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I searched around a bit for Errno 22 on a copyfile, and the general consensus seemed to be it could mean many things and is unhelpfully generic, but it does in practise tend to mean some variant of 'the filename has bad characters'.

Since your filename does have some funky characters, is it possible the Veracrypt partition is NTFS? If so, afaik, it will have character limitations, including ':' and '"', unlike a Linux ext4 disk.

Assuming this is true, I have reworked the file export code to test the export folder's partition's file system, and if it is NTFS or exFAT, to run it through the appropriate sanitation, replacing invalid characters with underscores. Previously it only tested your system platform, not the actual device being written to. Fingers crossed, this solves your problem, but it may need some more work if the change adds any lag or there are any issues detecting the mount and its partition. Let me know how it works for you.

If you are confident the partition is ext4 or something else that should allow those characters, please let me know, and re-open the issue as appropriate.

**Comment by jkendall327** [comment]
Your fix sounds very reasonable. I checked the drive with `df -T` and it was, indeed, exfat from back when I used Windows. I'll try exporting files on the next release and let you know if the error reoccurs. Until then I'll mark this as closed. Thanks a ton!
