### ISSUE TITLE
Semicolon in URL path cuts off in url normalisation

### ISSUE THREAD

**Issue by boobayayo** [hydrusnetwork/hydrus#1200]
### Hydrus version

492

### Operating system

Windows 11

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

scoop install

### Bug description and reproduction

Trying to download a url containing a semicolon in its path results in the url import page cutting of the url at (not including) the semicolon.
I assume this happens during url normalisation, as the same thing happens when resolving these urls in the "edit url class" dialog at the bottom.

Percent encoding it works, but is impractical, as this breaks copy-pasting from browser address bar or adding urls using hydrus companion.

Example dummy url:
`https://stream.bunkr.is/v/yepyepyep-12-07-2021-12345677-hello-nice-to-i&-133;-aBC3dc.mp4`
results in this normalised url:
`https://stream.bunkr.is/v/yepyepyep-12-07-2021-12345677-hello-nice-to-i&-133`

**Comment by hydrusnetwork** [comment]
Thank you for this report. This is an interesting one. I looked it up, and it turns out ';' is supposed to be a stand-in for '?' or '&' in the query parameters, so:

index.php?p=search&page=2
and
index.php?p=search;page=2

are apparently equivalent. And I _think_ it is supposed to work for ? in the same way. Therefore, that semicolon _has_ to be %3B(?) in the actual URL or it will break. It actually isn't my code that's taking out that component, but the main URL parser I use, this guy:

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse

So I am not totally sure how to solve this. Firefox is cleverer than hydrus and will _display_ pretty characters but secretly store and use the percent encoded ones. When I was playing around here, I noticed that if I copy/paste from the address bar in this case, the % encoding copies correctly into hydrus, but if I drag and drop, I get the invalid display text even though the DnD object that Qt is parsing is supposed to be giving me URLs. Furthermore, Firefox doesn't seem to want to accept the semicolon when I enter it as %3B and instead keeps it as %3B. So I think this is all a mess.

I'm afraid I think this touches on some RFC business that is beyond my expertise and definitely beyond the hydrus URL system for now. The whole URL normalisation routine is waiting for a complete overhaul so I can update it to do a similar 'store the encoding, display the characters' thing. Maybe we'll be in a better position for problems like this then.

I guess this has ultimately come about because some html encoding--some munged variant of "&133;" or something--ended up in an URL title. I think any site weird enough to put & and ; in an URL is not something I can keep up with for now.

As a side thing, you might discover that a lot of that text in the URL is not needed. You sometimes get articles like:

site.com/articles/senator-blah-offers-new-bill-123456.html

which can also be expressed as:

site.com/articles/123456.html

I wouldn't be surprised if the same were true here of the abC3dc.mp4 component and the 12345677 part. Maybe you can change your initial parser to cut out the weird english and get around the whole problem?

I'm going to close this issue for now. Maybe we can come back to it later, maybe it gets magically fixed by a library update somewhere, or the site itself stops producing them.
