### ISSUE TITLE
Share -> copy/export thumbnail

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1201]
Pretty simple: I'd like to be able to copy/export an item's thumbnail. My primary use case is dealing with saucenao file size limits without having to open an image editor.

**Comment by Zweibach** [comment]
There are currently an API endpoint for this: https://hydrusnetwork.github.io/hydrus/developer_api.html#get_files_thumbnail
So some very basic scripting would let you get them through that.

But since your usecase is for Saucenao I recommend just using either HydrusNao or hatate-iqdb since they both get and send a thumbnail/scaled down image when looking up sources for that same reason.

**Comment by hydrusnetwork** [comment]
Hey, I think I've just added this in today's release! If the image is bigger than 1,024 pixels on a side, it offers a second bitmap copy option bounded to a 1,024x1,024 box. Let me know if it gives you any trouble!

**Comment by floogulinc** [comment]
@hydrusnetwork I think it would be better to just copy the actual thumbnail. Then it would work for files hydrus can't display and would just be simplier. In my testing thumbnails work just fine for saucenao and such. In Hydrus Web for example all saucenao lookups use the thumbnail.
