### ISSUE TITLE
Duplicate filter screen hangs on 'Looking for pairs to compare--please wait'

### ISSUE THREAD

**Issue by SenseiSchizo** [hydrusnetwork/hydrus#1202]
### Hydrus version

v492

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Arch Linux, AUR
Also tried with official tar.gz file, same result.

### Bug description and reproduction

1. Open duplicates processing tab
2. Click launch the filter; as far as I can tell, the options don't matter.

**Comment by SenseiSchizo** [comment]
It appears this doesn't happen with a fresh DB. I just started using the software about 3 days ago.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry for the trouble, especially to a new user. This is an odd situation, and I am not totally sure how your client got into this position. It seems like:

A) The initial job to fetch some pairs never gets started.
B) The job starts, but it comes back with no data and the duplicate filter falls into a 'display nothing' error state.

When I look at the code, though, I feel like neither are possible, ha ha ha! I have changed a tiny bug I noticed for tomorrow's release, there's the smallest chance it fixes things for you. Please try v493 when it is convenient and let me know if that changes things.

If it does not, I think our best next bet is to try opening the duplicate filter with _help->debug->report modes->db report mode_ on. That'll spam database jobs to your popup toaster as they happen. Let's see if you get 'read duplicate_pairs_for_filtering' or not when you try to open the duplicate filter.

In the duplicate page itself, how many 'potential pairs' are listed for you to review? Is it a few dozen, a few hundred? Is it 0? What happens if you change the search on the 'filtering' page, something like 'system:filesize < 200KB'--does the number of potential duplicates go down, or does it always stay the same number?

Another thing to check would be _help->debug->data actions->review threads_. On the three tabs of that window, are there a couple dozen at most jobs on each page, or does one page have hundreds and hundreds of jobs it is trying to get through? (i.e. could something be blocked, meaning your duplicate search never starts?)

In general, even though you are new, do you have a busy client with hundreds of download pages? Or do you just have a couple of normal import pages you have been testing with, that sort of thing?

**Comment by SenseiSchizo** [comment]
I recreated the DB and it doesn't seem to be an issue anymore. I will reopen if the issue appears again. Thanks.
