### ISSUE TITLE
Duplicates filtering: Maintain earliest modified time

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#1203]
Hydrus now treats the earliest "modified time" as canonical information to be maintained when gathering information from files and domains, but (correct me if I'm wrong) it still seems that it freely discards this when processing duplicates. I would expect it to maintain the earliest time on the better file when marking one as better, and maintain the earliest time on all files when marking them as the same quality.

Another dropdown should probably be added to the "edit duplicate merge options" dialogue for this as well:
- sync modified time?:
    - make no change
    - if worse is earlier, copy from worse to better
    - always copy from worse to better
    - use earliest for both

I think this should be locked on "make no change" when the action is "alternates", like how "sync known urls?" is locked to "sync nothing" in the same situation. The option "always copy from worse to better" was included for completeness, but the usefulness of it is unclear, so it may not be worth implementing.

Not sure if this is really a feature request or a bug, I'd consider it technically "absent obvious functionality".

**Comment by bbappserver** [comment]
Suppose two files
- Patreon file [better]
- Twitter downscale [worse] 

Suppose one file is released on 
`2023-01-02 13:05`
and one on
`2023-01-07 14:05`

If the patreon file is released first, then merging would make the king the patreon file, causing the modified time of the twitter file to fly back in time several days and screwing up any chronological sorting (not that modified time is perfect for that to begin with).

If the twitter file is release first, and you say the patreon file is better, then the twitter file flies forward several days wrecking the chronological sorting in the other direction.

Either way you have destroyed the canonicalness of the timestamp.  The timestamp is different because the place where the image was obtained was different.

The better or worseness does not actually change the modified time of the files, because they are distinct, and setting a duplicate king does not change that.  Unlike tags where both files should have similar tags because they are congruent. Urls can be synced for the same reason as tags, what's important is you can find a high quality version.  But since modified time is connected to the file, not the identity of the media, it should not be merged IMHO.

**Comment by hydrusnetwork** [comment]
I was doing more timestamp work this week and I have this sorted. I did essentially exactly as you @pozieuto suggest, and I left out the 'always copy from worse to better'. I've got the 'set as better' merge options set to do 'earlier worse -> later better', and 'set as same quality' to do 'use earliest for both'. If anyone doesn't like it, they can also set 'make no changes'.

I also made it so when you sync URLs, if the URL's domain comes with a modified timestamp, this too is earliest-merged to the destination file.

Other timestamps like archived might be mergeable too, for some users, but I'll let this breathe a bit first and see where it goes wrong.

This took some time, but if you happen to play with this, let me know if you have any trouble with it!
