### ISSUE TITLE
Default sorting bug when opening a new window

### ISSUE THREAD

**Issue by fuka-eri** [hydrusnetwork/hydrus#1229]
### Hydrus version

499

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

When selecting multiple files and opening a new window using the context menu, the default sorting option for new pages is ignored and files are shown in order selected instead.

**Comment by floogulinc** [comment]
I believe this is the expected behavior and not a bug.

**Comment by hydrusnetwork** [comment]
Hey, thank you for this report. Yeah, this is the normal behaviour. Most people who are copy/pasting files from one page to another usually want the files in the same order they came in in order to do some particular work on them.

Since you would like to sort your 'open in a new page' files, I can reveal a secret shortcut in the client, which is if you are looking at a page of thumbnails like this, where the page does not have 'search' UI on the left, then F5 (or _right-click->refresh_) simply enforces the current sort. If you hit F5 right after you open your files in a new page, you should get what you want here and still retain the original sort if you ever want.
