### ISSUE TITLE
edit title namespace query toggles exclusion instead of editing

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#1235]
### Hydrus version

499

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Bug description and reproduction

Had a title namespace search with a wildcard and right clicked it to edit it.
It excluded instead of opening the edit window.

![image](https://user-images.githubusercontent.com/8496821/192067567-2852ceac-8d0f-491c-8a59-1e5793b06c75.png)
![image](https://user-images.githubusercontent.com/8496821/192067617-90e03d02-749a-432e-859d-fd454e756019.png)

It also does this in reverse, so it's the old toggle exclude button we had before.
Verified this for multiple new search tabs.

**Comment by hydrusnetwork** [comment]
Thanks for this reminder. This kind of not a bug, since the edit that is supported is just the invert flip, but rather than faff about, I decided to just do it. Tags, namespace:anything, and wildcards are now fully searchable with a text input that lets you convert between them at will. This is in for tomorrow, let me know if you have any trouble with it!

![image](https://user-images.githubusercontent.com/3878678/192640785-f9aa3ad7-b339-4bfb-b1bf-0b1086a76c3d.png)
