### ISSUE TITLE
MacOS crash on startup

### ISSUE THREAD

**Issue by justmilly** [hydrusnetwork/hydrus#1241]
### Hydrus version

v499

### Qt major version

Qt 6

### Operating system

macOS 10.15 "Catalina"

### Install method

Installer

### Install and OS comments

DMG installation

### Bug description and reproduction

Try to start Hydrus, crashes.

### Log output

```text
https://pastes.io/r7lpwwclpg
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry to say that I am not an expert with macOS, so I cannot be the best help here, and while that crash dump looks excellent, I am not very familiar with its format. It looks like Thread 0, which is the main GUI thread, crashed when entering libdyld.dylib. Could that be the system 'dylib' that helps locate/load other dylibs?

As we have moved to Qt6, there have been several 'I cannot boot' problems for older OSes, some Linux versions and Windows 7, and the actual problem location is usually related to loading a newer dll or so on the older OS. This _may_ be true for you, but I am not so confident. We build in macOS-11 now, and according to this https://doc.qt.io/qt-6/macos.html , it seems like Qt6 is supposed to, by default, work on 10.15. Catalina isn't that old, is it? 2019?

Are you able to run the Qt5 App? If that is fine, then I am afraid the only serious difference between the two is the version of Qt being built. The best explanation for the error in that case would be some combination of OS incompatibility, pyoxidizer packaging problems, or an issue with Qt6 and Catalina.

Also, if you check your desktop, your home directory, and your hydrus db path (should be /Users/[You]/Library/Hydrus) if it was created, is there a crash.log there, and/or a 'client - date.log' file? Maybe just maybe there is a different error related to Qt or anything else having trouble here, but I am not super confident there will be, since you are having actual program-halting crashes.

If you can run Qt5, please stick with it for now. I am going to keep putting out Qt5 releases for a few more weeks yet. I hope there is a switch I can flip to get you working on Qt6.

**Comment by hydrusnetwork** [comment]
I forgot to mention I have been working on a macOS boot crash that two other users had this past week. Please try v500, as I may have accidentally fixed things, or at least exposed a better error.

**Comment by hydrusnetwork** [comment]
I have been told by several users that this issue is fixed in 500/501. Please re-open if you still have it in 502!

**Comment by justmilly** [comment]
> I have been told by several users that this issue is fixed in 500/501. Please re-open if you still have it in 502!

I just updated and it seems to be working now. Thank you!
