### ISSUE TITLE
Python2 is EOL and deprecated on Archlinux. Consider switching to Python 3.

### ISSUE THREAD

**Issue by sodamouse** [hydrusnetwork/hydrus#1243]
Title is self-explanatory.

**Comment by thatfuckingbird** [comment]
Hydrus switched to Python 3 back in early 2019. What made you think it's still on Python 2?

**Comment by sodamouse** [comment]
> Hydrus switched to Python 3 back in early 2019. What made you think it's still on Python 2?
The installation process on Arch compiling and installing the entirety of Python 2.

**Comment by Mengmoshu** [comment]
AFAIK the Arch version is maintained by a user, and you should figure out how to contact them for this.

**Comment by thatfuckingbird** [comment]
Yes, the AUR package is unofficial. Talk to the maintainer on the AUR.

**Comment by Zweibach** [comment]
The installation instructions very clearly state that AUR is third party and not maintained by Hydrus Developer.

**Comment by ScoreUnder** [comment]
I'm maintaining the AUR package. The part that relies on python 2 is doc / help page generation, because some way down the dependency chain the `python-jsmin` package is set to build for both python versions. At this rate i might just sequester the docs into a separate package until that gets fixed.
