### ISSUE TITLE
Still getting Qt error after the update

### ISSUE THREAD

**Issue by aurosalinda** [hydrusnetwork/hydrus#1255]
### Hydrus version

503

### Qt major version

Qt 6

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 8.1. I tried both the installer and the extract method.

### Bug description and reproduction

1. Start client.exe
2. Get this error:
![image](https://user-images.githubusercontent.com/110314017/196960515-d11c4f13-abde-4e99-bb8e-6b4fa555c296.png)
Three days ago I decided to update the program. When I did it it showed the same error, so I tried installing older versions, but with them it didn't start, and didn't show an error at all.

**Comment by Mojavve** [comment]
I am also getting the same error as before on Arch even after updating.

```
Traceback (most recent call last):
  File "/opt/hydrus/hydrus/hydrus_client.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/opt/hydrus/hydrus/client/gui/QtInit.py", line 33, in <module>
    from qtpy import QtCore as QC
  File "/usr/lib/python3.10/site-packages/qtpy/QtCore.py", line 90, in <module>
    Qt.MidButton = Qt.MouseButton.MiddleButton = Qt.MiddleButton
  File "/usr/lib/python3.10/enum.py", line 480, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.
```

**Comment by hydrusnetwork** [comment]
@aurosalinda Damn, I had understood that Win 8.1 was ok with Qt6. Can you tell me what was the last version that worked for you? Was it Qt5 or Qt6?

If you have had a Qt6 version work ok for you before, then this is a new problem, but by that error it feels like it just won't initialise, which feels more serious. My feeling is you have never been able to run Qt6. If the last version you ran was before the Qt5/Qt6 releases, then you were on Qt5.

I suspect you have some 'dirty' dlls in your install now, which is why installing the older versions did not help. Please run a 'clean install' as here:

https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#clean_installs

Then again, for 503 I made it much easier to run the program from source, specifically for people with problems with the new Qt tech. I think you might be a candidate for that, so please also check out this guide:

https://hydrusnetwork.github.io/hydrus/running_from_source.html

You would be looking at the 'Qt5' variant of the setup script. You would want to do a 'clean install' too here.

Thank you for this report, and please let me know how you get on.

**Comment by hydrusnetwork** [comment]
@Mojavve Sorry for the trouble. It seems one of the libraries that we rely on (PySide6) updated in a way that breaks another library that needs it (qtpy). With luck, they will fix things on the qtpy end fairly soon, but for now I have fixed our setup documents (requirements.txt) to force versions that we know work. I am hoping the AUR guys can force my fix on their end, so you will be fixed automatically soon, but I am not expert on how their build works, so I cannot talk cleverly about it.

The ultimate fix, if it helps you, is to roll your PySide6 version back from 6.4.0 to 6.3.2. The magic line to do that normally is:

`pip install PySide6==6.3.2`

But I imagine that AUR uses a venv, so it is likely more complicated than that.

However, that may not be true. They may just work off your system python. Please open a terminal, then go:

`pip show PySide6`

If it says version 6.4.0, then try that pip line above to roll back to 6.3.2 and then try booting the client again.

Sorry for the trouble, this appeared out of nowhere!

**Comment by aurosalinda** [comment]
@hydrusnetwork the clean installation with the Qt 5 version worked. It's strange since I remember clearly that I used the installer for the version 497, that had Qt 6. Well, now it works, so no problem. Thanks for the help
