### ISSUE TITLE
thumbnail drag and drop to create new tab does not load thumbail view in main window

### ISSUE THREAD

**Issue by Rubeae** [hydrusnetwork/hydrus#1258]
### Hydrus version

503

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Running from source

### Bug description and reproduction

Upon dragging thumbnails out of one tab and up to the tab bar to create a new tab, the main window GUI's thumbnail section disappears within the newly created target tab. The tab only displays left column (tags and media preview).
Upon restarting the GUI, it properly loads the thumbnail view of all open tabs.
Dragging thumbnails to an existing tab--which has the thumbnail view already rendered--behaves normally, as expected.

![GUI Window Capture](https://user-images.githubusercontent.com/7447006/197786330-fcbfa12c-5429-4ace-9937-672791dddf3e.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I had trouble figuring this one out, as several other users also reported it, but I wasn't able to reproduce it. When one user noted they only got it on Qt5, I realised that was it and was able to reproduce it very reliably. I have fixed this for v505.

However your note suggests you are running Qt6. Since you are running from source, can you double-check for me that that is correct? If you hit _help->about_, does it say PySide6/PyQt6, or does it say PySide2/PyQt5? If you really are Qt6, then I am afraid my fix will most likely not apply for you.
