### ISSUE TITLE
Importing sidecar.txt with tags containing uppercase characters raises DBException error in 504

### ISSUE THREAD

**Issue by RossVFX** [hydrusnetwork/hydrus#1264]
### Hydrus version

504

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

In previous versions tags and namespaces containing uppercase characters were converted to lowercase in the sidecar import process, but in 504 they do not, so 'example:UPPERCASE' is imported and shown in the UI as 'example:UPPERCASE'.

Trying to right-click on a tag containing an uppercase character will raise a DBException error, which I've pasted below. 

Additionally it doesn't seem possible to delete any uppercase tag, though the lowercase equivalent can be added to a file (so a file can have both 'example:UPPERCASE' and 'example:uppercase')

### Log output

```text
v504, win32, frozen
DBException
KeyError: 'title:retro'
Traceback (most recent call last):
  File "hydrus\client\gui\ClientGUIAsync.py", line 59, in _doWork
    result = self._work_callable()
  File "hydrus\client\gui\lists\ClientGUIListBoxes.py", line 2601, in sp_work_callable
    selected_tag_to_service_keys_to_siblings_and_parents = HG.client_controller.Read( 'tag_siblings_and_parents_lookup', ( selected_tag, ) )
  File "hydrus\core\HydrusController.py", line 684, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 200, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 927, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 2061, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: KeyError: 'title:retro'
Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 610, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 7214, in _Read
    elif action == 'tag_siblings_and_parents_lookup': result = self.modules_tag_display.GetSiblingsAndParentsForTags( *args, **kwargs )
  File "hydrus\client\db\ClientDBTagDisplay.py", line 425, in GetSiblingsAndParentsForTags
    tags_to_service_keys_to_siblings_and_parents[ tag ][ service_key ] = ( sibling_chain_members, ideal_tag, descendants, ancestors )
KeyError: 'title:retro'


Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 610, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 7214, in _Read
    elif action == 'tag_siblings_and_parents_lookup': result = self.modules_tag_display.GetSiblingsAndParentsForTags( *args, **kwargs )
  File "hydrus\client\db\ClientDBTagDisplay.py", line 425, in GetSiblingsAndParentsForTags
    tags_to_service_keys_to_siblings_and_parents[ tag ][ service_key ] = ( sibling_chain_members, ideal_tag, descendants, ancestors )
KeyError: 'title:retro'
```

**Comment by hydrusnetwork** [comment]
Damn, thank you for this report! I'm sorry for the trouble. I have fixed this for v505, and I've updated the 'sidecars' tab when you set up a manual import so it correctly cleans tags for the preview column too.

I _believe_ the good news here is that this is just a display bug, and a restart will fix what your client thinks of the tags. There's a 'tag cleaning' routine that is force-run on all tag imports at the database level--so it _should_ be impossible to actually add an invalid tag--but since I forgot to also add this routine at an upper UI level, the bad (and now orphaned) tag string propagated across the upper pipeline and sent incorrect data to your UI taglists. I've fixed that second issue for v505.

If this does not fix on a restart, then please run _database->check and repair->fix invalid tags_.

Let me know if you have any more trouble!

**Comment by RossVFX** [comment]
Thanks. Yes, a restart seemed to fix it and they're displaying correctly now.
