### ISSUE TITLE
Download support for IBSearch?

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#129]
https://ibsearch.xxx
Found about this site today and damn isn't it awesome. It's a image board agreggator with a great search engine able to cross information over basically all boorus.

**Comment by AreFinstad** [comment]
nice find! if they add a few other sites it would be perfect.
Hydrus already supports the site already tho, you just have to create a booru profile, tho i am getting some failes downloads, not sure why. they might handle non-image files differently like rule34hentai did or it might be that the image in question i tested on had some issues.

i cant get tags to work at all tho, prob since there is no tags hosted on the image page itself.

one thing i want from this if Hydrus is adding support is that it will pull tags from each of the host sites (every image page has direct links to the other boorus where tags can be grabbed from)

![](http://i.imgur.com/74KglK3.png)

all in all, you can search and download from the site with Hydrus ATM with these settings in the image, seems like the image downloaded is the full res version aswell as im getting dupe hits on the server when doing the test. 


will make a new issue about source tags in a sec as its needed more than ever (did actually write the issue but never posted it then closed the tab two days ago.)

**Comment by AreFinstad** [comment]
this site does have an api and can be built into hydrus in many ways. you could set and requirement for having an personal api key has it seems like he is handing them out to anyone.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
