### ISSUE TITLE
i "seem to have an invalid tag in view" yet when i run "fix invalid tags" it finds no invalid tags and the error persists.

### ISSUE THREAD

**Issue by FlashlightET** [hydrusnetwork/hydrus#1324]
### Hydrus version

v513

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Install and OS comments

was installed via installer back in 2020 and has been updated via extract ever since

### Bug description and reproduction

1. Imported tags from sidecars (with some oopsies happening causing a few tags with spaces at the start (i didnt use the new seperator feature), these may be the "invalid tags." i can't delete these tags either, it just adds the tag without the space at the start to the end)
![image](https://user-images.githubusercontent.com/29938499/213951691-499f0650-3588-4a0b-aaa3-3ace22c8d17e.png)

2. hydrus warns me that there are invalid tags in view
3. i do what it says and run the fix invalid tags task
4. bad found: 0
5. hydrus warns me that there are invalid tags in view
![image](https://user-images.githubusercontent.com/29938499/213951599-5c619892-ccb0-40de-8625-f9682489e5d5.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report. Sorry for the trouble!

The issue with sidecars is fixed--I regret it and thought I had more safeguards on this stuff--they should now clean their tags correctly as of v514.

I will investigate why invalid tags is not fixing things here.

**Comment by hydrusnetwork** [comment]
Just as an update here, I have fixed the underlying problem, I think, which is that while bad tags were being fixed at the db level, it wasn't propagating up to the UI level. Turns out I did have safeguards, but they weren't applying in 'soft' places. Now, if the db notices bad tags in the last step of the content update pipeline, it also fixes the update package that is later passed on to the UI so the UI gets the fixed tag too.

I believe the reason why you got the 'invalid tags' message, but no actual db problems found, is that the UI saw the bad tags it got, but the db never actually saved them. The solution in your case is just to restart the client, I hope! And in the release I'll publish in a bit, this specific UI-db desync shouldn't happen again.
