### ISSUE TITLE
Duplicate filter window does not work if image "media show action" is set to certain options

### ISSUE THREAD

**Issue by chev2** [hydrusnetwork/hydrus#1329]
### Hydrus version

514

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Linux: EndeavourOS latest (kernel 6.1.8-arch1-1)

Installed via `hydrus` package in the AUR.

### Bug description and reproduction

The duplicates filter window simply gets stuck on "Looking for pairs to compare--please wait" if the "media show action" for the image filetype is set to anything other than either "show with native hydrus viewer" or "show an 'open externally' button".

Steps to reproduce:
1. Open Hydrus, then go to File -> Options -> Media.
2. Under "media viewer filetype handling", make sure the "media show action" for image filetypes is set to anything other than "show with native hydrus viewer" or "show an 'open externally' button".
3. Open the duplicates processing window, click "launch the filter".
4. The filter should keep displaying "Loading for pairs to compare--please wait" indefinitely.

Possibly related issue: #1202

**Comment by hydrusnetwork** [comment]
Thank you for this report! This is an odd one, since I don't have a valid view state for this case. We need to show something useful on screen, but the user said don't show anything. I'm sure this will come up again with weirder filetypes people introduce to the duplicate system, so I have set it so if you are in the media viewer and somehow the show action is 'do not show' or 'do not show, open externally', its fallback is to show the 'open externally' button.

This frees up the initialisation of the duplicate filter again and eliminates this weird halt you found. Basically when it came across an invalid media state, the filter was just stopping where it was on the last view it could handle ('loading...').

Let me know if you have any more trouble with this!
