### ISSUE TITLE
New native renderer display bug where most of animation/video is garbled mess

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1334]
### Hydrus version

v516

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

I'm actually running on macOS 13.1, but it's not an option in the dropdown.

### Bug description and reproduction

This applies to both the preview window and the media viewer window. The animation/video renders in the top left corner of the player and the rest is a garbled mess. Screenshot attached. The garbled mess is different for every video, it's not the same exact mess. And the mess does not animate alongside the animation/video, it's static.

<img width="1792" alt="hydrus_client_media_viewer" src="https://user-images.githubusercontent.com/73802796/218532338-c9d446d0-ab88-4682-be04-e617045e3809.png">

**Comment by floogulinc** [comment]
Are you using mpv or the old video player?

**Comment by floogulinc** [comment]
The old player is very janky and I doubt it will be worked on anymore since every other platforms can just use MPV.

**Comment by hydrusnetwork** [comment]
Thank you for this report! I think I have fixed this for tomorrow.

> @hydrusnetwork do you know why the above line of code hard-sets the device pixel ratio to 1.0? I can't imagine a reason why you'd want to override it.

I set it to the window DPR a couple lines later, so I _think_ this was me originally drawing the animation frame to the bitmap in raw pixel coordinates at 100% scale before adapting the bitmap to the screen. I've been cleaning code recently and I think I changed the `drawImage` line in between here to work on `self.rect()` rather than the raw pixels and it broke everything! Ironically, I was doing more `self.rect()` image drawing stuff instead of raw pixel numbers so I'd make fewer math errors, and here we are.

Anyway, sorry for the trouble. Let me know if there's still any problems in tomorrow's release.

If you are interested, that garbled mess is where I'm not drawing. Its pixels are whatever RGB bytes were in the memory previously. It is most likely another bitmap from a few seconds ago, but it could be channel-rotated so it has funny colours and the resolution is different so its pattern/phase doesn't line up and you get that moiré pattern.
