### ISSUE TITLE
"sha256 hash recognised: Imported at..." on a server-replaced image

### ISSUE THREAD

**Issue by ZacTheHac** [hydrusnetwork/hydrus#1353]
### Hydrus version

522

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

1. Import image from URL
2. image gets replaced by the creator
3. attempt to re-import from the same URL
4. Hydrus blocks it because it knows the URL, and it's marked as only holding a single image, but you override it with "try again"
5. Hydrus claims the sha256 matches the file it already has (try again has no effect from this point onwards)
6. manually give hydrus the direct image URL it gets from the page parser
7. Hydrus happily imports the new version.

Specifically, this is happening with the FurAffinity importer, which doesn't have a hash parser, so hydrus itself is generating the hash. I don't know how it's generating it, though, because the hashes don't match at all. The source times match, since FA doesn't consider the image being replaced as the source time changing.
I verified that the download URL the parser is generating is the same one I manually put in.

So I flag this as a bug because clearly hydrus is generating a hash from something that isn't the actual image.
I even looked at the old imported image to see if they were directly replacing the file and maybe their server was making the mistake, but the direct image URLs for them are different. The post number & file name are the same, but they're in different folders. (to be fair, it doesn't matter. accessing it via the old URL still serves the new image, which could be where the issue stems from?)
IE:
old image: *url*/1234/1235.imagename.jpg
new image: *url*/1365/1235.imagename.jpg
The importer gives the hash of the old image, despite that image not being accessible anymore.
Importing the new image manually gives back a different hash, and these hashes match up with their actual hashes.

This is only going to become more of an issue as more sites are offering the ability for users to edit their content after uploading it without changing the URL/losing any favorites/comments.

### Log output

```text
no log output since boot
```

**Comment by Zweibach** [comment]
I had some issue with this in regards to something completely different. I think it stems from Hydrus seeing the post URL, seeing that it has a file URL associated on the same file and doesn't even try to get a new file URL from the post URL.

What *might* solve this is if you set the post URL class to 'post page can produce multiple files'. This should force Hydrus to recheck the file URLs and notice the new one.

**Comment by hydrusnetwork** [comment]
Thank you for this report. Thinking about this, I believe what is happening is:

1. Import object tries to do its thing initially.
2. It matches the URL to the database record, sets 'already in db' and the 'seen this before' note _and it fetches the sha256 hash of the file for the import object so it can do presentation and various 'already in db' content-update logic_.
3. You set it to 'try again'.
4. ***My code does not erase the sha256 hash!!!***
5. On trying again, it now has a hash in store that it can use for a lookup--as far as it knows, it parsed this in a previous step.
6. It now presents the bogus 'sha256 hash recognised' 'already in db' status.

I will fix this. I'll have to be careful, but doing 'try again' should reset a few things.

I'm not totally sure, since I may have diagnosed this wrong or the situation may be slightly more complicated, but I think if you set the 'file import options' on this downloader to `check URLs to determine "already in db/previously deleted"? -- do not check`, before you started the download, I think this would have worked for you (but it wouldn't have worked in the 'try again' situation). The problem was this initial URL lookup, which then poisoned the re-attempt.

In any case, I'll make 'try again' undo a bit better. I think you will still need to set that 'file import options' setting to force-retry your updated URLs though. There's a related setting in 'tag import options', `force page fetch even if url/hash recognised and file already in db`, but I don't think that one is 'strong enough' to figure out a situation where the previously visited destination file has changed. It might, but I suspect it would just apply the tags and other metadata to the original file again.

Note, obviously, that that 'file import options' setting is expensive and should only be turned on for jobs where you know it is needed.
