### ISSUE TITLE
Folder import of image that exists in the database leaks temp file

### ISSUE THREAD

**Issue by AngusThermo-Pyle** [hydrusnetwork/hydrus#1356]
### Hydrus version

524

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Running from source

### Install and OS comments

Originally encountered with --temp_dir r:\HydrusTemp --no_db_temp_files, where r:  is a ram drive.  Retested with stock launch.

### Bug description and reproduction

Running a folder import where some files are imported and others exist in the database results in leaked temp files filling to temp directory which are not deleted when Hydrus is exited cleanly.  Verification with "file import report mode" shows that the temp filenames always match a file that exists in the database and therefore isn't imported.  Looking through the source, it appears that CleanUpTempPath is never called in this case.  It is possible that there may be other potential leaks here based on how CleanUpTempPath is expected to be called elsewhere.

### Log output

```text
v524, 2023/04/21 19:48:05: File import job starting work.
v524, 2023/04/21 19:48:05: File import job hash: a3e02fb2d99f0208643981aec7b1ed81a4432400fb9467c84c84df601e485cc2
v524, 2023/04/21 19:48:05: File import job pre-import status: already in db, file recognised: Imported at 2022-11-15 14:49:11, which was 5 months 7 days ago before this check.
v524, 2023/04/21 19:48:05: File import job is done, now publishing content updates
v524, 2023/04/21 19:48:05: File import job created for path c:\HydrusTemp\hydrusw7qy9c35.
v524, 2023/04/21 19:48:05: File import job starting work.
v524, 2023/04/21 19:48:05: File import job hash: 62e201078a3ab223640c8cda81258e9c4140a996c030b78d3dde8a0aa43f25ec
v524, 2023/04/21 19:48:05: File import job pre-import status: already in db, file recognised: Imported at 2022-11-15 14:49:14, which was 5 months 7 days ago before this check.
v524, 2023/04/21 19:48:05: File import job is done, now publishing content updates
v524, 2023/04/21 19:48:05: File import job created for path c:\HydrusTemp\hydrus5_cy3_9_.
v524, 2023/04/21 19:48:05: File import job starting work.
v524, 2023/04/21 19:48:05: File import job hash: 3e6b3d647b6d083970cb2c7245fb6ed0daecd6bcc9d6944533472cd18eecd78d
v524, 2023/04/21 19:48:05: File import job pre-import status: already in db, file recognised: Imported at 2022-11-15 14:49:17, which was 5 months 7 days ago before this check.
v524, 2023/04/21 19:48:05: File import job is done, now publishing content updates
v524, 2023/04/21 19:48:05: File import job created for path c:\HydrusTemp\hydrusg7u_2emh.
v524, 2023/04/21 19:48:05: File import job starting work.
v524, 2023/04/21 19:48:06: File import job hash: 8f362a3b48de9a61a48d925e6e360f732875277d548a6b744daf2c9cf2b03fd5
v524, 2023/04/21 19:48:06: File import job pre-import status: already in db, file recognised: Imported at 2022-11-15 14:49:21, which was 5 months 7 days ago before this check.
v524, 2023/04/21 19:48:06: File import job is done, now publishing content updates
v524, 2023/04/21 19:48:06: File import job created for path c:\HydrusTemp\hydrusxgishow4.
v524, 2023/04/21 19:48:06: File import job starting work.
v524, 2023/04/21 19:48:06: File import job hash: 3f6eabc9446e036a161c0e08155e1a559e2e546574a3ab574001f9b1ed6f1c98
v524, 2023/04/21 19:48:06: File import job pre-import status: already in db, file recognised: Imported at 2022-11-15 14:49:24, which was 5 months 7 days ago before this check.
v524, 2023/04/21 19:48:06: File import job is done, now publishing content updates
v524, 2023/04/21 19:48:06: File import job created for path c:\HydrusTemp\hydrusjlqth5bw.
```

**Comment by hydrusnetwork** [comment]
Thank you for this interesting report! I have done three things here:

1. Temp paths are removed more reliably now, on shutdown. I feel pretty good that my `CleanUpTempPath` routine is running in the right places (I complement it in a try...finally after every call to `GetTempPath`), but I think it can sometimes fail if ffmpeg or opencv or whatever I was using to inspect the import file hasn't giving up its file locks yet. In this case, the path goes in a set for later processing, and when a maintenance routine rolls around (every five minutes), it tries to clear those lingering files again. This routine was not happening on client shutdown, which meant any failed-to-delete temp paths that happened in the last few minutes of the client before shutdown were not being cleared correctly.
2. It turns out that maintenance routine was abandoning delete attempts if they were taking too long. I've extended the amount of time it is willing to wait, so it should reliably have several attempts at this now.
3. I moved these 'loose' temp files up into the 'hydrusxxxxxxxx' temp dir that I make on boot for various purposes and am careful to completely delete on exit. All my python-level temp files are now stored in this subdir. This will ideally ensure these no-longer-useful orphan files are caught in a final sweep, and if the program crashes, it ensures they are all in one location for easier manual deletion.

So, let me know how you get on with this. If what we are really facing here are some very sticky file locks, then maybe this will cause errors as the client tries to delete the temp dir on shutdown, but with luck this'll just be a better net on these tricky files.
