### ISSUE TITLE
527 MacOS build damaged

### ISSUE THREAD

**Issue by KamillaPup** [hydrusnetwork/hydrus#1367]
### Hydrus version

527

### Qt major version

Qt 6

### Operating system

macOS 12 "Monterey" (Apple silicon)

### Install method

Extract

### Install and OS comments

I actually have macOS 13.3.1 "Monterey" (Apple silicon)

### Bug description and reproduction

1. Downloaded DMG and copied over .app file. What bothered me is it had a NO sign through it.
![CleanShot 2023-05-11 at 14 51 31](https://github.com/hydrusnetwork/hydrus/assets/26353056/f176fd12-c60b-4946-afc8-6e3e02006707)
2. Tried launching and it says the app is damaged or incomplete.
3. Checked the Security Control Panel and there's no prompt like usual to "Open Anyway"
4. Reverted back to v526 and no problems.

So it seems the MacOS build is arfed.

**Comment by hydrusnetwork** [comment]
Damn. Thank you for this report. The big change in v527 is the new executable name, so, if this problem isn't something odd like the download was mangled or something, it sounds like it isn't redirected from 'client' to 'hydrus_client' properly.

Please forgive that I don't have a macOS machine to test on, and I am by no means any expert on it. I remember, from when I did have a macOS machine, that you can right-click on an App and say like 'look inside' or something, right? And you can explore the directory tree. Can you do that for me? I can browse it here in 7zip and you should have an inner executable path somewhat like:

`Hydrus Network.app/Contents/MacOS/hydrus_client`

Do you have that executable file? Or has anything crazy happened, like an anti-virus removed it?

If you have the file, please open a terminal and enter this:

`open -n -a "Hydrus Network.app"`

(You need to have 527 installed to Applications I think first though.)

Does it produce a nicer error than your UI there? Anything like 'cannot find "client"' or something?

Someone else has been telling my that the new Qt Media Player may be causing problems with macOS since it uses PyQt6 rather than Windows's and Linux's PySide6. It seems odd that it would stop a boot from even starting though, rather than, say, breaking a boot. I will investigate this more, and I have written some extra error code that may help.

**Comment by hydrusnetwork** [comment]
EDIT: Wait, I think I found it. I forgot to update the Info.plist (a manifest file)! Damn. I will make a build soon for you to test, will update in a bit.

**Comment by KamillaPup** [comment]
Sadly no luck. It doesn't appear damaged anymore but it won't open. I tried launching hydrus_client directly from Terminal and got this error:
```/Applications/Hydrus\ Network.app/Contents/MacOS/hydrus_client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 7, in <module>
ModuleNotFoundError: No module named 'hydrus'```

**Comment by classicsc** [comment]
It seems the problem is that the `hydrus` package directory that was present in v526 is missing under `Contents/MacOS` in v527. I got v527-MacOS-test-1 to work by downloading and extracting the source tarball, then running `cp -R /path/to/hydrus-527-macos-test-1/hydrus /path/to/Hydrus\ Network.app/Contents/MacOS`.

**Comment by hydrusnetwork** [comment]
@classicsc Thank you very much for discovering the fix!

I took this source folder out of the Windows and Linux builds recently, knowing it was surplus there, and assumed it was the same for macOS, which uses PyOxidizer instead of PyInstaller. It was not!

I have un-done my regression and a new build is here: https://github.com/hydrusnetwork/hydrus/releases/tag/v527-macos-test-3

Let's hope this sorts it. Very sorry for the trouble!

**Comment by classicsc** [comment]
Yes, that did it! v527-macos-test-3 is working normally.
