### ISSUE TITLE
Stop all downloads and paged file imports when there is 500 MB of disk space left

### ISSUE THREAD

**Issue by Gradivus500** [hydrusnetwork/hydrus#1373]
When Hydrus has less than 500 MB of free disk space left, the program will refuse to start. This can be a particularly big problem when hydrus is the only thing on that disk (As it is in my case). This leaves you with no other choice but to start deleting thumbnails, or worse, move some of your db files else where and tell hydrus to ignore the problem. This is all necessary since the solution to this problem is to delete files from within hydrus, but you can't do that if you can't launch hydrus. Hydrus will already display an error and stop all downloads and imports when there is no disk space left, what I want is for it to stop sooner than that so you can at least start the client again later. A temporary solution instead of a more robust one could even be for hydrus to create a 500 MB file on start up, and delete it on shutdown. That way, no other changes have to be made to behavior, the 500 MB file will prevent the disk from ever actually having less than 500 MB free.

**Comment by hydrusnetwork** [comment]
Thanks, I'll look at this. I can't remember how the logic works here, but I expect it isn't being careful about the locations it tests. If you have a ton of space on your db drive but are short on your media drive, then yeah I think I can let you boot but disable importers and just moan at you to delete things.

**Comment by hydrusnetwork** [comment]
I looked at how this works today. Some of it I am happy with--it turns out I had the logic correct, and the free space check only occurs on the drive that has the database files on it--but it was a bit too strict.

I have moved the check down to after the first open/close connection cycle to the database files is made, which means it is checking after it has cleaned up any gigantic old journal files from a previous crash etc...

I have also made it look at the size of your database, and if half the total size is less than 500MB, I'll let it use that instead, down to 50MB minimum (to catch new users who spawn a fresh boot on a crazy full drive). If someone wants to run a micro db on their USB stick, that's fine, we don't need lots of spare space, but an actual real client that is doing stuff needs free space.

I don't have time to do clever solutions here or constant observers checking and rechecking. And I don't have the infrastructure for a read-only mode yet either. Overall, hydrus should only be run on a healthy drive, and all healthy drives are at least 5% empty, and preferably 10%.
