### ISSUE TITLE
Latest Mac client locks up & crashes when interacting with Subscriptions window

### ISSUE THREAD

**Issue by InvaderJ** [hydrusnetwork/hydrus#1379]
### Hydrus version

531

### Qt major version

Qt 6

### Operating system

macOS 12 "Monterey" (Apple silicon)

### Install method

Extract

### Install and OS comments

Just updated to Hydrus 531 from the DMG. 

### Bug description and reproduction

Updated my client to latest Hydrus 531 build, directly from the DMG. 

Seems to work fine, except the client completely locks up and crashes when trying to work with Subscriptions. I do have all Subscriptions currently paused.

0. Network > Manage Subscriptions 

Locking up: 
1. In the Subscriptions window, I have one subscription. 
2. Clicking once on the Subscription in the list view, will do nothing – it will not highlight the Subscription or anything.
3. If I click again on the Subscription, the client will lock up, requiring me to kill it. 

Crashing: 
1. In the Subscriptions window, I have one subscription. 
2. Clicking once on the Subscription in the list view, will do nothing – it will not highlight the Subscription or anything.
3. If after clicking once on the Subscription, I then attempt to close the Subscription window, the client will crash.

I've attached a crash log, prob not that useful, and also the logging below from a fresh run and subsequent lockup.

Potentially related: I seem to have to launch the client twice to interact with a 10-query gallery page. That is, when I click on a query in the list, it will not select until I click another 1-2 times, and it will also not actually display the images from that query. If at this point I quit the client and relaunch, I will be able to properly interact with the queries, where double-click a query will highlight it, make it active, and display the images from the query. Weird. 

[hydrus_crash.txt](https://github.com/hydrusnetwork/hydrus/files/11712918/hydrus_crash.txt)

### Log output

```text
v531, 2023/06/10 13:06:21: hydrus client started
v531, 2023/06/10 13:06:22: booting controller…
v531, 2023/06/10 13:06:22: booting db…
v531, 2023/06/10 13:06:22: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v531, 2023/06/10 13:06:22: checking database
v531, 2023/06/10 13:06:22: preparing db caches
v531, 2023/06/10 13:06:22: initialising managers
v531, 2023/06/10 13:06:22: booting gui…
v531, 2023/06/10 13:06:22: starting services…
v531, 2023/06/10 13:06:22: Running "client api" on port 45869.
v531, 2023/06/10 13:06:22: services started
v531, 2023/06/10 13:06:41: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
v531, 2023/06/10 13:06:44: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
v531, 2023/06/10 13:07:27: saving and hiding gui…
```

**Comment by KamillaPup** [comment]
I was having this issue with 530 so I upgraded to 531 and still have the matter. This happens also in managing sessions cookies, url classes, etc. Pretty much every sub menu.

**Comment by KamillaPup** [comment]
I backdated to v529 and the issue went away so this was a change likely in 530, if not 531.

Thanks for all you do!

**Comment by InvaderJ** [comment]
> I backdated to v529 and the issue went away so this was a change likely in 530, if not 531.

So you didn’t run into any database hiccups going back to 529 from 531?

**Comment by hydrusnetwork** [comment]
Hey, I am sorry for the trouble here. This sounds like it sucks! Looking at the v530 commit (https://github.com/hydrusnetwork/hydrus/commit/1e4c416fd6e5862a19eb31cc064c72e3d0d51c83) did not help me much, unfortunately, although it crossed some things off the list--I don't change anything related to the subscriptions dialog, nor multi-column list event handling, and I don't seem to have updated Qt or anything in the background, which might have altered the behaviour here despite the same code. It must just be some small change that I am missing.

Whatever I did, we have crashing here rather than just a little annoyance. I hate having this happen, but I am happy to have seen this error in both your logs: `Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.`

I never knew this! But I can reproduce it real easy (it crashes instantly for me, without giving that log entry), and it explains some other bizarre crashes I've seen but had trouble figuring out. I can't remember this being an issue before, so perhaps it is more aggravated in newer Qt, or maybe I am just using eventFilters more (and less carefully?) these days. I'll assume for now that somewhere I have an event handler catching a mouse move or similar and it wants to say something like 'hey, I couldn't click on that subscription/url class/whatever row because of (good v530-related macOS-specific reason)', but instead the error can't propagate up to the top level reporting. All those multi-column lists have a little file-drop watcher tech that handles some drag and drop events, so perhaps they are hooking into minute mouse movement when you click and checking them out to see if they are drag events with accompanying files, and then running into some trouble.

So, for tomorrow's v532, I have wrapped all my event handlers in strong error handling code, and I'll keep them this way in future. Everything should be caught and reported in normal popup windows, and this specific problem will no longer cause a crash. Please try it out and let me know what you get. At the very least, I hope whatever that Qt error in the log is about will be gone, and more I hope this is actually what is happening to you and we'll get some nicer normal errors on what your problem with multi-column clicks actually is.

Let me know how you get on, and if it still crashes, roll back to v529 again. There's no big database changes coming this week, so it'll still be ok to do.

**Comment by InvaderJ** [comment]
You are awesome! Thanks very much for taking a look! Love all the details.  :) 

Unfortunately, 532 is still acting the same as previously described. Please let me know if I can provide any logging (and where exactly to find said logging)!

**Comment by eldarium** [comment]
Hi! I'm also having the same issue. Before updating to 532 the client didn't lock up, but it was very janky. It was more as if the first click was ignored. E.g. in file log, when right-clicking, nothing happened, but when you right click again it showed the context menu for the empty page and not the selected entry. This (probably) also impacted downloads - they paused after each one and client showed the "waking up from sleep" message. Hitting Cmd+Q forced a dialog to appear and that progressed the download.  
Now on 532 the client crashes if you select any list in options (e.g. frame locations). Nothing in the logs except for the Qt message.

**Comment by hydrusnetwork** [comment]
Thanks for the updates everyone. Since the event handling didn't fix it, this sounds more like a build issue. I examined the build logs of macOS 529 vs 530 and it turns out there's an auxiliary Qt library, some sort of C++ bindings support in addition to `sip`, that updated a minor version. I have forced this library back to the version that worked in v529 in a test build here:

https://github.com/hydrusnetwork/hydrus/releases/tag/v532-macos-test-1

Please try it out and let me know what you get.

An interesting thing is @roachcord3, from source, is on PySide6. This further suggests this is some PyQt6 issue, and that auxiliary library is the only thing I know that changed. I'm not sure why the macOS App build isn't on PySide, since I've generally had more success with that, but I think it might have been a different compatibility thing, or it was an issue with PyOxidizer.

What a tangled mess--sorry everyone. We are spinning plates with duct tape bootstraps here just to get pixels on screen.

**Comment by eldarium** [comment]
this build seems to work fine on my end - no mentioned issues with lists. thanks!

**Comment by hydrusnetwork** [comment]
Fantastic, thanks for letting me know! I will roll this into the normal release, so 533 _should_ be fixed.

As a side thing, while I was thinking about PySide6, I tried out another test, right here: https://github.com/hydrusnetwork/hydrus/releases/tag/v532-macos-test-2

This simply swaps out PyQt6 for PySide6 to see if it works, and now I remember why we use PyQt6 for macOS--the DMG here is 600MB! Now, there may be a whole ton of trimmable fat in there, but for now I'll be less excited about PySide6 as a macOS alternative. The App is probably 2GB or something ridiculous. Feel free to try this out too, and let me know if it has a ton of graphical issues or anything. If it works wonderfully, amazing, with many bugs fixed, then I'll re-examine and see what is in all that extra 320MB.

**Comment by KamillaPup** [comment]
532a is working for me but haven't tried this test you did.

**Comment by eldarium** [comment]
Both test versions seem to work fine (tried variuos menus/lists, archive/delete filter, tag management), test-2 version is indeed twice as large
