### ISSUE TITLE
Untether siblings from parents

### ISSUE THREAD

**Issue by KrivenRaven** [hydrusnetwork/hydrus#1381]
If I want "red swimsuit" to be the child of "tag:red clothes," I cannot then make it the sibling of "tag:swimwear" without "tag:red clothes" becoming the parent of "tag:swimwear." This is very, very wrong.

Current solution: "red swimsuit" child of both "tag:red clothes" and "tag:swimwear." Problem: "red swimsuit" still appears in auto-complete search results, even if it is set to be hidden.

Desired solution: child/parent tags should only ever look at the root tag, and never look at the sibling tag. Sibling tag should only ever look at the root tag and not look at the child/parent tags.

Alternative desired solution: tags which are hidden should not populate in auto-complete results.

**Comment by Mengmoshu** [comment]
What is your *purpose* in making `red swimsuit` the sibling of `swimwear`? Because it looks like you're trying to use siblings to hide things, but they're for things that are either typos or "equally correct" in that they represent the same property.

For example, if you're trying to "hide" `swimwear` by making it the hidden sibling of `red swimsuit`, what do you do when it comes time to address `blue swimsuit`? I feel like you might have a fundamental misunderstanding of the intent and common usage of siblings in Hydrus. To people who understand what siblings are supposed to be good for, collapsing both the presentation and child/parent logic to a single "king" tag makes sense, and untethering that breaks core functionality.

That said, blocking select tags from auto-complete sounds like a potentially useful feature, that you could make a new issue for.
