### ISSUE TITLE
MacOS Hydrus Update Workflow to backup DB, mark app as safe, then launch

### ISSUE THREAD

**Issue by KamillaPup** [hydrusnetwork/hydrus#1391]
![CleanShot 2023-07-04 at 02 44 07](https://github.com/hydrusnetwork/hydrus/assets/26353056/87cccff4-c90c-427d-887e-8491d7639d72)

I'm not sure if this is where I should share this, but I wrote a MacOS automator script that does the following and can be run after updating Hydrus every time:

1. Zips client db files with current date.
2. Runs shell script to disable MacOS quarantine on new version `xattr -dr com.apple.quarantine "/Applications/Hydrus Network.app"`
3. Launches Hydrus Network

Because MacOS requires granting permissions and putting in your password or fingerprint everytime you update, it can get quite annoying. This also backs up the DB files prior to launching the new version so if it borks your database, you can revert. I find if you automate backups, you're more likely to use them.

You can open this workflow in automator and change the location of the hydrus backup and add copy commands into the application if you modified it in anyway, like replacing some of the UI art, custom icns, etc.
[Backup DB and mark as safe.zip](https://github.com/hydrusnetwork/hydrus/files/11946135/Backup.DB.and.mark.as.safe.zip)

**Comment by Zweibach** [comment]
This is not the place to share this.

Fork this repo https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/tree/master/Scripts and create a folder in the linked folder named something appropriate, "Mac backup script" or something like that. Create a README.md in that same folder with the instructions. Probably better to just share the file instead of a zip though.
