### ISSUE TITLE
Having siblings window open while deleting trash crashes Hydrus

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1447]
### Hydrus version

v544

### Qt major version

Qt 5

### Operating system

Windows other (specify in comments)

### Install method

Running from source

### Install and OS comments

Windows 7

### Bug description and reproduction

1. Preferably have HDD so you can replicate this issue reliably
2. Have items in trash
3. Select them and delete them
4. Meanwhile you can still open images queued for deletion; open one
5. Right-click on some tag and issue siblings(/parent?) management
6. If deleting items is faster than processing sibling pairs (and it should be) then whole application crashes to desktop

Log info says it's about MPV but I can't tell for sure there were any animations in trash, I forgor. I'm 100% sure I watch all the media I decide to delete so in their "complete" form none of it crashed media view panel.

### Log output

```text
v544, 2023/09/28 19:53:16: services started
v544, 2023/09/28 21:57:10: A media loaded in MPV appears to have had an error. This may be not a big deal, or it may be a crash. The specific errors should be written after this message. They are not positively known as crashy, but if you are getting crashes, please send the file and these errors to hydev so he can test his end.

Its hash is: xxx
v544, 2023/09/28 21:57:10: [MPV error] ffmpeg/demuxer: gif: invalid block label
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry I am late getting to it. I have adjusted the physical 'delete from trash' action to remove all the to-be-physically-deleted files from view immediately, to stop the user accidentally clicking on something that is very soon about to disappear from disk. If the files are on another page they won't be removed, so a user who jumps around, clicks a to-be-deleted-file, and then hits a UI-lagging job may still get the problem, but I'll settle for this!

Yeah, the crash was probably due to mpv trying to navigate a 'hey, this file just disappeared' problem while the sibling/parent dialog was lagging the hell out of the main UI thread trying to load its pairs. There are additional protections that are supposed to stop this (the actual disk delete doesn't happen until several seconds after the file is removed from database records, and the file should be removed from the UI by then), but if the UI thread is delayed is long enough, I imagine this can still occur. The real answer here is to rework the sibling and parent dialogs to asynchronously load just the pairs the user is working on, so the UI doesn't get lagged. I plan this!

Thanks again, let me know if you have any more trouble.
