### ISSUE TITLE
Hydrus keeps connections open indefinitely.

### ISSUE THREAD

**Issue by rktfier** [hydrusnetwork/hydrus#1458]
### Hydrus version

545

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Install and OS comments

OS connections are handled by Proxifier. Every application which is not whitelisted goes through TOR. 

### Bug description and reproduction

1. Start a download process (through subscriptions or URL Downloader)
2. Wait for it to finish
3. After the process ends, Hydrus keeps connections open for the source.

### Log output

```text
https://imgur.com/992dTUw

The time is HH:MM:SS, this is after the subscriptions download has finished around 9 hours ago and subscriptions paused afterwards.
```

**Comment by hydrusnetwork** [comment]
Thank you very much for this report! Sorry I am late to it.

I had thought the tools I used handled this for me, but it seems they don't! I have written a maintenance system to clear lingering keep-alive connections after five minutes of inactivity. I hope this will keep things clean while also saving repeated reconnection during download tasks that may have longer inter-job waits due to bandwidth or forced pause times.
