### ISSUE TITLE
Allow Hydrus to use multiple CPU cores.

### ISSUE THREAD

**Issue by NyaaTell** [hydrusnetwork/hydrus#1480]
For bigger hoards where file maintenance, import/export jobs, high session/page weight and large queries could use more way more juice than 1 out of 24 cores can provide... (wouldn't be surprised if that single core is shared with other apps too :D)

**Comment by hydrusnetwork** [comment]
Hey, I am sorry, but for now, since hydrus runs on python, it is limited to one physical core for the higher level work. When the code dips down into C++ (e.g. when doing certain image processing), it can use multiple cores, but for now, this is a limitation of the language. It is called the 'GIL': https://realpython.com/python-gil/

I think I am right in saying that a future version of python is planning to get around this, so with luck it'll naturally happen in a few years.
