### ISSUE TITLE
Windows defender Trojan warning for  Bearfoos.A!ml 

### ISSUE THREAD

**Issue by LonelyBard** [hydrusnetwork/hydrus#1515]
### Hydrus version

558 and 560

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

Window Defender is throwing up a Trojan warning for Bearfoos.A!ml is affecting hydrus_client.exe 558 and is deleting it on resolution. I reinstalled 560 from this GitHub (I also installed 558 from here) and still have the issue, so it's most likely a false positive because I was doing some heavy downloads.

**Comment by hydrusnetwork** [comment]
Thanks for letting me know, and I'm sorry for the trouble. It is always useful to know when these strike. The good news is these _tend_ to go away after a couple of weeks. It is odd it is giving the same warning on two versions so soon after each other.

We've had the same basic build process for years now, and everything is built from python on Github, so we can generally be confident it is a false positive.

If hydrus keeps getting flagged your end, you might like to try running from source. I do it now for my personal Windows client and love it: https://hydrusnetwork.github.io/hydrus/running_from_source.html

For anyone checking in on this who has not seen this help text before, these just happen sometimes. Less often these days, though; I think it must have been six months or more since the last: https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#anti_virus
