### ISSUE TITLE
[Linux] Mouse pointer stays hidden after closing media viewer

### ISSUE THREAD

**Issue by bobdanek** [hydrusnetwork/hydrus#1518]
### Hydrus version

559

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

NixOS 23.11, Wayland (Hyprland)

Installed by adding `pkgs.hydrus` to `environment.systemPackages` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/hydrus/default.nix).

Note on being a version out of date: I cannot install newer than v559 at the moment; v559 is the current version in nixpkgs, and trying to build a newer version from unstable fails, here's the last few relevant lines from that:

```
  File "/nix/store/dhv6s3r00vlr26c4w6396pcf4ijxgyna-python3.11-psd-tools-1.9.28/lib/python3.11/site-packages/psd_tools/psd/__init__.py", line 8, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

### Bug description and reproduction

Description:

The mouse pointer becomes hidden when using the keyboard arrow keys to move between images in the media viewer. This is good and fine, I don't want it there if I'm not using the mouse. However, when I close the media viewer with the [Escape] key, the mouse pointer remains hidden while it's over the Hydrus window. It shows up outside of the window, but as soon as the pointer is over the Hydrus window, it hides itself again.

Reproduction:

1. Open a page with ~20 or more images
2. Double-click an image to open the media viewer
3. Put the mouse pointer roughly in the middle of the viewer (so it's not hovering over tags or URLs or anything)
4. Use the keyboard arrow keys to quickly move through a bunch of images, watching for the mouse pointer to disappear. Once it does, keep going through a few more images.
5. Press [Escape] to exit the media viewer if the pointer does disappear.
6. See if the pointer remains hidden in the main Hydrus window. If so, I can usually get it to come back by making some big, quick mouse movements.

### Log output

```text
No relevant logging output, assuming `hydrus/db/client - 2024-02.log` is the correct log to be looking at. I saw no updates to that log file as I reproduced the issue.


v559, 2024/02/05 15:53:01: hydrus client started
v559, 2024/02/05 15:53:03: booting controller…
v559, 2024/02/05 15:53:03: booting db…
v559, 2024/02/05 15:53:03: checking database
v559, 2024/02/05 15:53:03: initialising managers
v559, 2024/02/05 17:53:04: booting gui…
v559, 2024/02/05 17:53:04: starting services…
v559, 2024/02/05 17:53:04: Running "client api" on port 45869.
v559, 2024/02/05 17:53:04: services started
```
```

**Comment by hydrusnetwork** [comment]
Thank you for this report! Interesting bug, I am sorry for the trouble. Wayland has been funny for us, I guess some flag here isn't being reset manually, or it doesn't have per-window cursor settings or whatever.

I have forced the media viewer to reset the mouse cursor to normal as it exits. I hope this fixes your issue. It will be in tomorrow's v562, but it seems like you won't be able to test it easily. I am not sure what that missing 'attr' module complaint is about, and I am afraid I am absolutely not a Linux expert and only learned about this nix package thing from you posting it here, but I guess somehow the setup script isn't figuring out the right dependencies or there is just an odd conflict that isn't being reported correctly. I don't know if you can edit a '.nix' file and run the edited version manually, but `psd-tools` is completely optional (it just adds thumbs/metadata for PSD files), so if that is the only problem here, you might just be able to remove that line and be able to build it again.

Failing that, I have a little guide here on how to set up your own source install. It doesn't take a huge amount of work these days--on Linux, you just clone the git repo, run one .sh script to build the venv, and then make yourself a shortcut. It should have all the correct version numbers and stuff: https://hydrusnetwork.github.io/hydrus/running_from_source.html

Some AUR guys were having a problem this week with their easy-setup AUR package using their system python and getting the latest library versions as a result, which brought a recursion bug down into hydrus when the AUR stuff updated a bit of Qt. Maybe your issue here is similar?

Anyway, once you are back, let me know how you get on with everything.

**Comment by bobdanek** [comment]
Figured out how to run v562 and it seems fixed!

For anyone else on NixOS wanting to install a newer version, here's what I did:

In `configuration.nix` right after my imports (I got the sha256 by setting it to "" and letting the error output from the `nixos-rebuild switch` tell me the correct hash):

```
  nixpkgs = {
    overlays = [
      (self: super: {
        newhydrus = super.hydrus.overrideAttrs (oldAttrs: {
          version = "562";
          src = self.fetchFromGitHub {
            owner = "hydrusnetwork";
            repo = "hydrus";
            rev = "refs/tags/v562";
            hash = "sha256-v/oXpTA+JNhzTrxUkUw6PDLFvDLLoGxfJcoRodE4dc0=";
          };
        });
      })
    ];
    config = {
      allowUnfree = true;
    };
  };
```

Then down in my `environments.systemPackages = with pkgs; [` I put `newhydrus`.


nix is pain.
