### ISSUE TITLE
pdf, cbz, cbr support? some might find it handy.

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#152]
i think it would be great if hydrus would support these formats as im guessing alot people already a quite a few of these files. 
that way some might want to use hydrus as a manga/comic manager aswell as an image manager. 
cbz and cbr files is practically zip and rar files with images contained, one thing that might be really handy with these two is that they contain metadata in text files inside these files that hydrus could be able to read aswell as edit and change. 

pdf is another matter tho but i guess some have those still eventho its not the best format, it could be done if hydrus has a built in browser for example.

as for thumbnails then it can either load the first image in the file or in the case with cbz/r then read the metadata file on which image is the cover image.

**Comment by pokeball99** [comment]
the first one is supported
![](http://i.snag.gy/A3zcd.jpg)

**Comment by AreFinstad** [comment]
while it is supported in browsing it is not supported by being actually able to open it inside hydrus and requires an external program aswell as does not load thumbs for it either.

**Comment by HASJ** [comment]
if cbz and cbr become supported, i'd say goodbye to three other programs.
if you want some good readers for example of good archive readers, take a look at these hydrus: honeyview, cdisplayex and comicrack.

comicrack is hands down the best comic library manager.

**Comment by AreFinstad** [comment]
ComicRack and happy panda is the better ones IMO, still early days on panda tho for sure.

**Comment by ScoreUnder** [comment]
> while it is supported in browsing it is not supported by being actually able to open it inside hydrus and requires an external program aswell as does not load thumbs for it either.

What is the issue with a PDF opening in another program? I mean, imagine trying to scroll it in the image viewer!

I think PDFs opening in another program is the best thing to do, because PDF rendering is no easy task. It would need a lot of code, a lot of effort, and [possibly introduce a lot of vulnerabilities][1], just for something which would likely end up being a sub-par replacement for an existing program.

[1]: http://www.cvedetails.com/product/497/Adobe-Acrobat-Reader.html?vendor_id=53

**Comment by pokeball99** [comment]
@ScoreUnder well said, don't fix whats not broken.

**Comment by AreFinstad** [comment]
while PDF's might not be the best choice (try to not use it myself but official releases comes that way alot of the time for tags sake i would use it) 
cbr/z files tho in another thing as its practically zip and rar files with images and can be supported alot simpler. 
do agree that PDF support might be not the best, but it would still be handy non-the-less

**Comment by HASJ** [comment]
@AreFinstad you can just extract the images with the pdf

**Comment by AreFinstad** [comment]
i do know that and i do know you can convert and many other things, its handy to be able to support official releases from people tho IMO. alot of payed releases comes in pdf formats offically and the hash value for that file will always be the same. that way tags and such will also be shared wit the official release and so on. thats my thought process about it tho. i always convert or rip them in full quality but i also always keep the original file.

**Comment by Link-Satonaka** [comment]
Do you guys actually want cbz/cbr support in hydrus (which would give you the option to open it in an external viewer), or do you want the importer to be able to extract zipped images into hydrus (using metadata for tags)? Actual cbz/cbr support in hydrus would appear as one file with one set of tags for the entire thing (no individual tags per page).

I personally tag individual pages of my manga so I'd prefer to have cbz/cbr just extracted into individual pictures.

While we're adding support for things that are "just zip and metadata" there's the Pixiv ugoira file too :) but that would require actual support

**Comment by AreFinstad** [comment]
well tags per image could be set in the metadata of the file, and i dont see a huge problem that hydrus cant handle it either when its inside an archive. 
i would think that atleast some users would find it useful and as a thought to just make an issue out of it. 
i would think they would want to keep the cbr/z files as it would make it easier to manage like that....
and you could never really use the hash of the hole file, you have to use the images inside the archive no matter what if you want to share the tags with the tagshare. 
also, doesnt metadata from such archives contain hash values aswell? atleast they could thats for sure.

**Comment by Link-Satonaka** [comment]
I'm not sure I fully understand- what reasons do you want cbz/cbr in hydrus for (vs just having images from them). The way I see it, hydrus is the endpoint- once it's in there, that's where it stays. How would it be "easier to manage like that"?

**Comment by AreFinstad** [comment]
less thumbnails that take up space and resources ofc. can fit more issues on a single screen over just one page at a time.

**Comment by Link-Satonaka** [comment]
`less thumbnails that take up space and resources`
I am opposed to any idea that removes individual pages from search results. There will always be thumbnails for each page.

`can fit more issues on a single screen`
If that's the only benefit, it would be just as easy for hydrus-dev to implement an option to "collapse images with matching title into one thumbnail". Any reason why keeping the cbz/cbr intact is better than just tweaking the interface?

To me, it makes more sense (and would be less work for hydrus-dev) to extract images rather than implement cbr/cbz reading support into the viewer. I wouldn't be opposed to optionally treating cbr/cbz like pdfs are treated now- they're in the database but you have to open with an external viewer.
