### ISSUE TITLE
importing tags from image name

### ISSUE THREAD

**Issue by EnderDovahkin** [hydrusnetwork/hydrus#1580]
issue: i have way to many images to import and tag properly in a reasonable timeframe

solution: example image of a solar system with the tags: blue sun, 3 planets, gas giant.
have something that the user sets up so that when a string is read then the tag is applied. for example: blue sun -> star: blue. 
or something along the lines of that. is this at all possible and at all reasonable to ask?
this method would create a user generated database of sorts that can be used for large imports of images.

**Comment by Mengmoshu** [comment]
If you're talking about getting tags from filenames, that feature exists in two forms. One just grabs the filename whole. The other uses regex.

If there's some other source of "image names" you'll have to explain.

**Comment by EnderDovahkin** [comment]
> If you're talking about getting tags from filenames, that feature exists in two forms. One just grabs the filename whole. The other uses regex.
> 
> If there's some other source of "image names" you'll have to explain.

image names just refers to file name, like reading a string and taking it apart for tags. can you explain both methods you mentioned?

**Comment by Mengmoshu** [comment]
Poke around the file import window, google what a regex is, and above all read the `help and getting started guide` that is under `help` in the client.

We don't use the issue tracker for teaching people how to use Hydrus, since just bug tracking and feature requests are a lot of things already. The documentation is a good place to start. If it's confusing any of the other platforms the Hydrus community uses (like the Discord) are likely to be better places to get this kind of help.

**Comment by Zweibach** [comment]
Features to do this already exists.
