### ISSUE TITLE
Version 601 macOS App Test 2 is only available for apple silicon macs

### ISSUE THREAD

**Issue by marceloexc** [hydrusnetwork/hydrus#1641]
### Hydrus version

v601

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Installer

### Install and OS comments

macos sonoma 14.6.1 on Intel(R) Core(TM) i7-9750H (12) @ 2.60 GHz 

new macos binary built from the github actions using macos-14 runner is only being shown to run on apple silicon (downloaded from dmg [here](https://github.com/hydrusnetwork/hydrus/releases/tag/v601-macOS-2)

<img width="512" alt="Screenshot 2024-12-05 at 15 21 45" src="https://github.com/user-attachments/assets/46a67f0d-2f14-4372-bb7f-9684e49d9fd8">
<img width="372" alt="Screenshot 2024-12-05 at 15 21 38" src="https://github.com/user-attachments/assets/cf14d5d5-ea1b-46de-9cf8-67a7b84486f0">
<img width="1032" alt="Screenshot 2024-12-05 at 15 21 36" src="https://github.com/user-attachments/assets/27f7dfbd-230d-4a9e-81e9-61405ccd5fa0">

### Bug description and reproduction

1. download binary from github releases
2. try to open on intel mac

**Comment by marceloexc** [comment]
macos 14 and above runners are arm only 

macos14-large has intel cpu's available but requires a paid account and idk if this repo has that

macos 13 still has intel support and doesn't require a paid account (afaik)

**Comment by hydrusnetwork** [comment]
Thank you for this report! I am quite ignorant about macOS and its new chipset outside of the fact that they have been doing this. This is a free repo, so if you can only get intel support on macOS-14 with money, we may be short on luck there.

I have updated the test build release with an App built with the macos-13 runner: https://github.com/hydrusnetwork/hydrus/releases/tag/v601-macOS-3 It is 40MB bigger than the other one, so sounds hopeful?

A guy was telling me last week that if we move the macOS App from the current 'pyoxidizer' build back to 'PyInstaller', which we use for the Windows and Linux builds, that it can somehow bundle support for both chipsets. I don't know if the runner would affect this.

Since the hardware is moving towards ARM, would it be reasonable to assume that we probably will be dropping the universal binary within the next five years, or is this something I should be thinking about for longer-term legacy reasons? Much like with Win 7, would I be looking at saying 'hey, if you are on intel, you have to be looking at running from source' once the 13 runner is removed? I don't have a feel for what is reasonable here.

**Comment by marceloexc** [comment]
next five years sounds reasonable (even 3 years is good) - i think githubs desicion to drop intel with macos14 was too early but at the same time its probably an infrastructure issue, theres no new macs with intel chips and i dont think they can scale with 2019 mac pros / mac minis that arent sold new to just host new runners

my estimates are that intel macs get dropped entirely by macos 17

**Comment by marceloexc** [comment]
the dmg built with macos13 now runs 👍🏻

**Comment by hydrusnetwork** [comment]
Thank you for your help! I'll update the runner to the 13 for v602. Let me know if you run into any more trouble.
