### ISSUE TITLE
SSLCertVerificationError on parser causes us cannot download file.

### ISSUE THREAD

**Issue by Yuki-Soul** [hydrusnetwork/hydrus#1642]
### Hydrus version

v600

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Install and OS comments

Tried with extract and installer. The error still happened.

### Bug description and reproduction

Hi, I encountered so many times error like this (SSLCertVerificationError). Have tried to ask about it in dicord support. But no one can solve it.
![image](https://github.com/user-attachments/assets/a9f0910c-45d4-4fec-b78a-64c37f609ceb)

I am not a python dev but maybe this site (https://medium.com/@vkmauryavk/resolving-sslcertverificationerror-certificate-verify-failed-unable-to-get-local-issuer-515d7317454f) is the solution. Use Ctrl+f for "Solution: Setting the CA Certificates Path Globally" to jump to the important part.

This happens not just for gelbooru. also happen for archiveofsins, danbooru and several parsers.
When using manual image URL, pixiv, derpibooru or twitter parser it's working and can grab the json/html, even downloading the file.

I hope dev can fix it soon.

### Log output

```text
'fetch failed: Problem with SSL: SSLError(MaxRetryError("HTTPSConnectionPool(host=\'gelbooru.com\', port=443): Max retries exceeded with url: /index.php?page=post&s=view&id=4163910 (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)\')))"))\n\n'
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am not sure exactly what is not working here, but I have to guess it is something related to Win 10, or perhaps your version of Win 10, that it has older SSL tech somehow, and requests cannot talk to it.

That Medium article is interesting, because it suggests `requests` cannot find `certifi`. I was of the understanding that `certifi` was only added to the program (you can see its folder in the install dir) _because_ `requests` was asking for it, but perhaps it needs a little extra bump to get it linked in some (all?) cases, and thus in your case it is falling back to the OS, and that has older SSL stuff. I can figure this out for v602.

Can you please try something for me? Please open a terminal in your install folder or fresh extract (do shift+right-click on the folder and then select 'open in terminal/powershell'), and then make sure you are in the older terminal by typing `cmd` and hitting enter.

Then please enter this:

`set REQUESTS_CA_BUNDLE "C:\Hydrus Network\certifi\cacert.pem"`

Where the `C:\Hydrus Network\certifi\cacert.pem` is whatever your install dir and certifi folder is.

Then type `hydrus_client` and hit enter to run the client as normal.

If you do this, does this fix the SSL problem? Do you have the cacert.pem file, or could, say, an anti-virus program have somehow deleted it?

**Comment by hydrusnetwork** [comment]
Oh, yes, this is an alternate fix, but if you hit _file->options->connection_, there is a `BUGFIX: verify regular https traffic`. Turning off this checkbox turns off all https verification and may 'fix' this bug, but turning off https verification is not ideal so it isn't a good long-term solution. But it might make your install work for a week or two until we figure this out.

**Comment by hydrusnetwork** [comment]
Ah, sorry, I think I messed up the syntax! I specifically asked you to switch to `cmd` but I guess it works a little different there. If you would like to try again, instead do this:

(open a new terminal in the install dir of the test extract)
```
cmd
set REQUESTS_CA_BUNDLE=F:\Hydrus For Testing\Hydrus Network\certifi\cacert.pem
echo %REQUESTS_CA_BUNDLE% (this should output the path we just set, just to check it was set ok)
hydrus_client
```

You have to open hydrus_client in the same terminal window because our edited environment is specific to just that terminal.

In any case, I will see what I can do on my end for v602, which will release on the 11th December. Let me know if that fixes things with 'verify regular https traffic' back on.

**Comment by hydrusnetwork** [comment]
That 404 is interesting, and I'm not sure what is going on. Maybe there's a path by which the various CDN gateways navigate this that can lead to a dead end if our `requests` does not somehow do all of its SSL stuff.

I could not reproduce this on my end, and if you say the 404 is only _sometimes_, then perhaps this is a different issue like the CDN having other trouble.

Let's see if it clears up once we fix the main SSL problem.

**Comment by hydrusnetwork** [comment]
Ah, wow, so that was the problem!

It looks like you followed the steps perfectly, by the way.

I do not think I can write any code to get around your country's content blocker. It looks like they are employing it at the network infrastructure level. I presume when your network connection is doing SSL stuff, your ISP is forcing the connection to close early or similar. I'm not enough of an expert in DNS, particularly the newer DNS tech, to know how that could be involved, but maybe there's some SSL verification that works through a DNS request and that's where your ISP steps in.

If you try to load the site in a normal web browser, does it simply fail to connect, or does it instead redirect you to a government web page saying 'content blocked'? If a redirect is happening, I imagine that's why hydrus is having trouble--it is trying to verify the SSL with the wrong server due to a weirdly coded redirect. The specific error is 'unable to get local issuer cert' so I guess in some way the site is blocked from starting the SSL handshake.

While I cannot code around this, what I can do, as you say, is improve the error. At the moment, it is some ugly error text, but I can catch that and say something like "SSLCertVerificationError -- could it be an ISP content blocker?" or similar.

Thank you for your help here, and I wish you good luck in future.

**Comment by hydrusnetwork** [comment]
I had a quick look, and I'm afraid it does not look like it is simple to change DNS with the library I use, `requests`. I can write a patch, but it isn't the best way to do it.

`requests` wants to use the system DNS, so is there any way you can change it at the system level? I think in Windows you go into your network settings and edit the network adapter, go into the IPv4 settings, and can set it to 1.1.1.1 or whatever there, and then anything in your system that asks the OS for a DNS resolution will use that instead. This might fix your situation better since it'll work for many programs, not just hydrus.

You can google for a different result, but this seems to be the basic idea: https://www.howtogeek.com/767564/how-to-change-dns-servers-on-windows-11/

I think you can force DNS over HTTPS in the Windows settings too.

**Comment by hydrusnetwork** [comment]
Damn, that's annoying. Let me know how you get on with this in future. Good luck!
