### ISSUE TITLE
Two features i desprately need, id assume would be simple to implement

### ISSUE THREAD

**Issue by Chikessi3** [hydrusnetwork/hydrus#1656]
i dont think its hard to add or any reason to not add but i really want to be able to add any kind of file regardless of filetype which i dont think is possible ? also i reaaaaally need capitalization sensitivity with tags, can u please make it a toggle in settings ? im not sure how the database works but surely it can discern different capitalization?
this software has been really good to me so far but these problems are making my life very very difficult the more time passes
if u know of software that is an alternative with these features and u cant add them for whatever reason feel free to recommend

**Comment by Zweibach** [comment]
It's ironic that you request capitalization when you can't even bother to use it yourself. Anyways, both requests already exist.

**Comment by Chikessi3** [comment]
can u explain why its not planned ? i searched for capitalization and general filetype and couldnt find it
also how is it ironic ? i need it in hydrus not here
is it ironic that ppl who request a dark theme to be added dont have their eyes half closed at all times or how does this work

**Comment by thatfuckingbird** [comment]
More/any type of file is here https://github.com/hydrusnetwork/hydrus/issues/261, you're better off commenting there what filetypes you want and upvote that issue.
Capitalized tags are unlikely to happen as the whole system was designed with all tags being normalized to lowercase. It might not have been the best decision but it is what it is, and unfortunately not easy to change. Recently adding custom metadata fields (e.g. title, original filename) was discussed. Those would be capitalized, but they are not implemented yet.

**Comment by Chikessi3** [comment]
Im currently using notes to remove the problem but whats the reason behind limiting filetypes ?

**Comment by thatfuckingbird** [comment]
They aren't really limited on purpose, originally the system was designed with only images/videos in mind and then later expanded. Originally it didn't make much sense to allow everything because you couldn't display them anyway and that made little sense in an image viewing oriented program. Each file type needs supporting code to recognize it, extract metadata, display it so its not that easy to implement. However, Hydrus is definitely moving in the direction of supporting more filetypes and having the ability to import any file, without the filetype-specific support is very likely going to be implemented at some point. It is one of the most popular feature requests.

**Comment by Zweibach** [comment]
![image](https://github.com/user-attachments/assets/df0ccaad-7eda-45c4-9839-bb036a020be1)
