### ISSUE TITLE
save all url's on download (not just one)

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#179]
right now hydrus seems to only save the one url from where it go its file.
i think it should be able to save them all and have an export/open url in the context menu of the file/s to let us choose which site to use.

also a note on the url's saved. we should be able to copy the image url and no the page url aswell which is really handy for chats like Discord that displays any raw image url as the image.

so an option to copy/open the page and copy/open the file (which is a direct link to the file and not the page with the tags and all)

small note, if the website icon can be displayed in the context menu it would be amazing!

**Comment by AreFinstad** [comment]
since saving of urls are now a thing in hydrus and has been for some time i was about too close this issue. 
but i feel its very limited with what it COULD be.

i think it should be able to save all urls of the file no matter what. the UI should also contain the logo of the site/booru the link comes from.

4chan and other threads that wont have urls saved for long has to be put on an ignore list if we can.

what i want is have the export url opening up the hole list of links with the icons next too them. then just let us click the one we like too copy it to the clipboard.

an option to NOT copy to clipboard and an option to open in browser could also be useful as people might have different needs. i personally like to have more control and not have my clipboard filled and rather open then drag&drop.

a site hierarchy would also be amazing, with one then we would have no need to show the list (tho it should be there as an option). with a hierarchy the user would just get the url from the site highest on his personal list with a single button.

(totally forgot to post this as i changed the title)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
