### ISSUE TITLE
Can't open Windows DB using Linux client

### ISSUE THREAD

**Issue by ve3lst** [hydrusnetwork/hydrus#189]
Hi,

I've been using Hydrus on windows but I don't have a windows anymore and I'm using Ubuntu 16.04 the problem is: I just moved DB folder (Windows ver.) to Linux client DB folder. I though that's all what I've to do but the client won't start giving me this error:

![screenshot from 2016-07-28 17-32-12](https://cloud.githubusercontent.com/assets/18611574/17216786/af4b7676-54ea-11e6-97b6-5ce6b222fb64.png)

I tried to figure out what I can do reading the log file but I wasn't able to understand anything.

Here's the log file if it may help: [client.log.zip](https://github.com/hydrusnetwork/hydrus/files/388613/client.log.zip)

Thanks!

**Comment by ve3lst** [comment]
Hi,

I guess I know what's the problem, The client were working perfectly. 
I installed windows on a VM and made a backup of the DB, imported it to Linux client and it didn't work. Then exported the images, imported it to the DB works fine, then I added a proxy (Tor) restarted the client and the client won't boot up (same error in the screenshot).
Please note that Tor proxy settings were working perfect on windows client.

Anyhow I've wasted hours importing the images and I don't want to that again. So can you please tell me where the client store proxy settings so I can restore, so the client will starts again?

Thanks

**Comment by ScoreUnder** [comment]
I have an idea of how to fix it:

First, **back up your `client.db` database.** Just create a copy somewhere so that if things go wrong you can revert to normal.

You may need to install `sqlite3` and `python`, but I think desktop ubuntu comes with those by default.

In your ubuntu command line, do this:

```bash
sqlite3 PATH_TO_HYDRUS/db/client.db 'select * from options' > options.yml
```
Replace `PATH_TO_HYDRUS` with the correct path.

It should respond with nothing. If it gave any errors, don't continue.

Then, open the newly-created `options.yml` in a text editor (something like `gedit options.yml` in the console might do it, otherwise find it in the file manager). Find the line that starts with `proxy:`, it should look like this:
```yaml
proxy: !!python/tuple [socks5, localhost, 3128, null, null]
```
Delete that line and save the file.

Then, put that file back into the database. This is the hard part. I've written a little python script to do it, so run this in the terminal:
```bash
python2 -c 'import sqlite3, sys; sl = sqlite3.connect(sys.argv[1]); sl.cursor().execute("update options set options=?", (open("options.yml").read(),)); sl.commit()' PATH_TO_HYDRUS/db/client.db
```
Again replace `PATH_TO_HYDRUS` with the correct path. Again it should respond with nothing.

After that, try running hydrus again. It should no longer have the problem.

----

@hydrusnetwork 

```python
./include/ClientNetworking.py:    socks.setdefaultproxy( proxy_type = proxytype, addr = host, port = port, username = username, password = password )
```
I'm led to believe that the version of pysocks on @ve3lst's hydrus setup is out of date. If @ve3lst is using the packaged version, it could be a packaging problem. See if the copy of pysocks in the environment used to package hydrus is out of date. Note the change in PySocks 1.3 which renamed `proxytype` to `proxy_type`: https://github.com/Anorov/PySocks/commit/298d7c9265af117e2806ad6da26e6fd612591fc1#diff-ebb1878b28de14cbe1c43d894bbd2aa1L84

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
