### ISSUE TITLE
Autocomplete dropdown is visible

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#21]
What a silly bug title!

When Hydrus is first launched, it always looks like this:
![Screenshot](http://a.pomf.se/axtump.png)

The dropdown window moves to the correct place once you click away from the textbox and back into it. After that, clicking away from the textbox makes the window appear sized 5x5 (including borders) next to the textbox.

WM is i3

**Comment by ScoreUnder** [comment]
Screenshot of second issue
![Screenshot](http://a.pomf.se/dlvlfv.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report. Getting the autocomplete dropdown floating code to work consistently on multiple platforms has been a constant headache. For instance, Windows and OS X seem to be ok with a frame with size 0x0, but Linux WMs, even if they can handle that, tend still to draw visible shadows around that zero-size box. Hiding/Showing the window causes focus issues, and your i3 seems not to be initialising size and position as I would like it to as well!

I think I will add an option to integrate the dropdown into the parent frame in all cases, like I did for the manage tags dialog last week, for these WMs that I don't have to test with. And I think I will make it default ON for Linux, just because of the particular problems it has with floating frames.
