### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by Unknow0059** [hydrusnetwork/hydrus#244]
## Environment

Hydrus version: 400
OS: Windows 10 Pro 1909 10.0.18363.900 64-bit 

## Steps to reproduce

1. Extract or install version 400. 
2. Double-click client.exe or tick the "Launch client" checkbox on the install wizard.
3. Profit.

## Describe what you expected to happen
The client to launch.
## Error message / Log file
None.
There is no crash.log, and there is no client(date).log in the db folder. My antivirus has not captured any files.
The server does launch, whatever that's worth.
I also tried the previous version, 399. Same issue.

**Comment by ShadowJonathan** [comment]
Did you have a previous hydrus installation?

Also, can you maybe see in task manager or [Process Hacker](https://processhacker.sourceforge.io/) if the client pops up at all?

**Comment by Unknow0059** [comment]
Did not.
![image](https://user-images.githubusercontent.com/25656892/84640070-92a56e80-aecf-11ea-9320-1dcff1a86e1f.png)
It does pop up in the log, but only if I try to open multiple instances of it by holding Enter for a few seconds. If I only press Enter once, it won't show up in the log at all.

**Comment by ShadowJonathan** [comment]
Interesting.

If you didn't have a previous installation (but started out fresh), my best suggestion for right now (before going into actual debugging) is to uninstall the program completely and reinstall it again, but also confirm if the directory it's being installed in is totally empty.

**Comment by Unknow0059** [comment]
Yes, the directory in which it was installed was an empty one. The only folder in it is the Hydrus Network folder.

**Comment by ShadowJonathan** [comment]
I mean after uninstallation, confirm if the Hydrus Network directory is empty or gone

**Comment by Unknow0059** [comment]
Gone.

**Comment by ShadowJonathan** [comment]
Alright, after reinstallation, could you please try to launch it again, if it doesn't work this time, I might have to ask you to join the discord server so we can help you a little bit faster with trying to find out why it's crashing with exit code 0, without even popping up a initialization window.

**Comment by Unknow0059** [comment]
I've already reinstalled a couple of times and tried to relaunch all those times. Nothing changed in those attempts.

**Comment by ShadowJonathan** [comment]
Alright, then I might indeed have to ask you to join the discord chat, so I can help you with this a little quicker.

**Comment by ShadowJonathan** [comment]
Error log, btw:
```
Traceback (most recent call last):
  File "G:\TemporarySoftware\Hydrus Network\client.py", line 19, in <module>
    from hydrus.client.gui import QtPorting as QP
  File "G:\TemporarySoftware\Hydrus Network\hydrus\client\gui\QtPorting.py", line 22, in <module>
    import qtpy
ModuleNotFoundError: No module named 'qtpy'
```

**Comment by imtbl** [comment]
> ```
> Traceback (most recent call last):
>   File "G:\TemporarySoftware\Hydrus Network\client.py", line 19, in <module>
>     from hydrus.client.gui import QtPorting as QP
>   File "G:\TemporarySoftware\Hydrus Network\hydrus\client\gui\QtPorting.py", line 22, in <module>
>     import qtpy
> ModuleNotFoundError: No module named 'qtpy'
> ```

Note, in case HyDev decides to look at this issue: this error message occurs when running from source without the required dependencies installed (so that's completely normal and expected) and is unrelated to the issue of Hydrus not starting when using the prebuilt executable (as mentioned in the opening post). We've already cleared up that misunderstanding in Discord.

**Comment by ShadowJonathan** [comment]
We've also figured out that running the executable file will not result in an error log written anywhere, but still exits with code `0x0`, zero.

**Comment by bbappserver** [comment]
@Unknow0059 
The prebuilt executable should ship with all the packages needed, this error message is an indication that Hydrus cannot find the package necessary for displaying the GUI, it shouldn't happen because that package should have been bundled with the release.

If running from source try
`python3 -mpip install -r requirements.txt`

**Comment by Unknow0059** [comment]
> The prebuilt executable should ship with all the packages needed, this error message (...)  shouldn't happen because that package should have been bundled with the release.

Yes, as established, this is an issue with the executable and the error message was a false lead, because it came from trying to run the script directly.
> If running from source try
> `python3 -mpip install -r requirements.txt`

Since I am having issues with the executable, I tried running from source after doing that.
Here is the error:
```
(...) 
Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: Module use of python37.dll conflicts with this version of Python.
```
I replaced the python37.dll within HydrusNetwork's dir with the python38.dll from my python installdir, which fixed that. But now I get this:

```
Traceback (most recent call last):
  File "G:\emptydir\Hydrus Network\client.py", line 19, in <module>
    from hydrus.client.gui import QtPorting as QP
  File "G:\emptydir\Hydrus Network\hydrus\client\gui\QtPorting.py", line 55, in <module>
    from hydrus.core import HydrusConstants as HC
  File "G:\emptydir\Hydrus Network\hydrus\core\HydrusConstants.py", line 67, in <module>
    import sqlite3
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
```
Python comes pre-installed with an sqlite3.dll within it's "DLLs" folder.

**Comment by ShadowJonathan** [comment]
Please don't mess with the binary files in the install directory if you're going to try install it from source, if you want to install from source, clone this repository and follow those instructions. (Which btw @Unknow0059, I think is the best shot at fixing this issue for now, until we can figure out what is going on on your system)

**Comment by Unknow0059** [comment]
I said this on discord but just to update the issue: I cloned the repo and managed to run Hydrus from source, ignoring the prebuilt executable.

**Comment by hydrusnetwork** [comment]
Hey, I am sorry you have had trouble here. Please forgive me being late as we figure out the workflow for the new issue tracker.

I have had a similar recent report from a user who has this same issue when they try to update to anything 373 and above, which is when Qt came in. They are trying to run the client on a remote location, some network RAID configuration, also able to run the server but not the client. My current suspicion in that case is that there is something about loading the Qt dlls from that location, but I have not narrowed it down yet.

If there is no crash.log in your db directory or user desktop, that suggests client.exe was unable to load PyInstaller's python, before my code gets involved, which points to dll problems.

I am glad you are working from source, but I will investigate making a Qt-compatible debug executable to see if I we can get more information on this in future.

**Comment by hydrusnetwork** [comment]
Hmm, yeah, I did not have luck building different kinds of debug build for the client. Two debug modes fail to build, and another appeared to go ok, but then does not boot the exe correctly. I believe this is ultimately because of Qt wanting to be a non-console (windowed) program, and the debug normally working with console output. There is supposed to now be a 'windowed' dialog hook to display the debug traceback, but I am only getting problems through it.

However, here is a different build, using an older version of PyInstaller:

https://www.mediafire.com/file/4ditw5txjchxu64/Hydrus_Network_401_pyin3.5_-_Windows_-_Extract_only.zip/file

@Unknow0059 Please try extracting and running that on your desktop or similar. Does it boot? Does it give you a different error? Different versions of pyinstaller work better or worse for certain unusual situations, such as running the program with a symlink. If this works for you, that narrows down the problem.

Since you are comfortable with running from python source, did you happen to already have python or C++ Qt already on your system? I have had a couple reports before about system-wide Qt environment variables sometimes upsetting hydrus's private Qt.

**Comment by Unknow0059** [comment]
> Since you are comfortable with running from python source, did you happen to already have python or C++ Qt already on your system? I have had a couple reports before about system-wide Qt environment variables sometimes upsetting hydrus's private Qt.

I already had Python on my system installed from the Microsoft Store. I installed QT alongside other dependencies from the Requirements list in a virtual environment and ran client.py from there.

**Comment by hydrusnetwork** [comment]
Thank you. I also moved back from PyInstaller 3.6 to 3.5 for the Linux release, so I think I'll do the same for Windows, for you and anyone else in your situation. It must just be some odd dll loading issue in the bootstrap phase of the exe.

**Comment by hydrusnetwork** [comment]
@Unknow0059 Hey, if you spot this notification, could you try this test build? I am testing another user on some stuff and playing around more with pyinstaller 3.5 and 3.6, and I am wondering if a fix I did here helps your situation with 3.6:

https://www.mediafire.com/file/sn855t9ssc6qdn0/Hydrus_Network_pyinst3.6_who_knows_-_Windows_-_Extract_only.zip/file

**Comment by Unknow0059** [comment]
Nope, the client did not start. No errors written either.

**Comment by hydrusnetwork** [comment]
Damn, thank you. I think both yours (3.6) and the other users' (3.5) errors are in pyinstaller, so I am forced to decide to use one. Since you have a source version running, and I think it is probably correct to err on the side of the newer library, I am afraid I expect to move back up to 3.6 for next week. :/ Sorry for the trouble. It just seems loading Qt with PyInstaller is a problem for some situations.

**Comment by Unknow0059** [comment]
It's possible that programs created with pyinstaller are being instantly killed by a banking security application on my computer as [seen here](https://github.com/qutebrowser/qutebrowser/issues/5568).
