### ISSUE TITLE
Adding API for local booru

### ISSUE THREAD

**Issue by bigretromike** [hydrusnetwork/hydrus#245]
https://github.com/hydrusnetwork/hydrus/issues/60
https://github.com/hydrusnetwork/hydrus/issues/62

```
That would essentially make hydrus booru a fully working booru.
Would make it to posible to enjoy collection from various devices.
Adding API to it would also open path for (un)official clients or adding support for already existing one.

The look of www-page could be customize inside browser already
```
Any kind of API would be awesome.

**Comment by ShadowJonathan** [comment]
Maybe a server/client service with a configurable port so that any reverse proxy or any environment can fit to that?

**Comment by CuddleBear92** [comment]
@bigretromike have you seen https://hydrus.app/ yet?

**Comment by imtbl** [comment]
As mentioned, the client API already exists and is used by various tools; see <https://hydrusnetwork.github.io/hydrus/help/client_api.html>.

Please suggest specific improvements to the API and rename the issue accordingly (or close the issue if there's nothing you'd like to see added).

**Comment by bigretromike** [comment]
Its been 5 years from mine initial post.

I will close it here, when I have time to revisit what changed along that time and it will be still API releated I will reopen this, until then Im closing because there was a development but noone mention in on that original issue.

**Comment by imtbl** [comment]
> there was a development but noone mention in on that original issue.

That's because issues were completely disabled until recently (so no one could add comments or edit them in any way) and when we reopened them we closed all the old ones and added a comment (since it would have been non-maintainable to get 200+ issues updated).

It should be obvious that the phrasing _If your bug report or feature request is still relevant_ implies that you should check the _current_ Hydrus version if the bug/proposed feature has already been fixed/implemented. Especially since the API isn't exactly brand new or obscure; many Hydrus users are using it one way or the other these days (mostly though Hydrus Companion).
