### ISSUE TITLE
right click gallery query to open queues

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#256]
We need an simpler way to open queries as so many new users struggle to find the queue button inside the query.

To be able to right click the query itself should have two new options, open post queue and open gallery queue.

@hydrusnetwork did reply to it in a possitive manner, marking it as seen.

![image](https://user-images.githubusercontent.com/8496821/84907144-22574280-b0b3-11ea-8192-0666315d0e7a.png)

EDIT: this also makes it easier to open the queue without needing to load the thumbnails if those are set to load. Should optimize usage and speed for those that need to do an action or two in the queue.

**Comment by hydrusnetwork** [comment]
Thank you for this reminder. This should be added for tomorrow's 402. It works for the gallery page and the watcher, and shows the file/gallery log for the top selected query/watcher.

Only doing it for one is because the dialogs here have no ok/cancel, and so no way to determine users wanting to 'cancel out' of a batch view. If there is a need for multiple logs shown at once, we'll figure out a way to show multiple logs on one dialog than looping multiple dialogs in a row.

Let me know if you have any trouble with this.
