### ISSUE TITLE
Sankaku Channel MD5 Check

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#275]
Saving bandwidth is always a good call, and Sankaku is probably one of the stricter sites supported by Hydrus as far as that goes. By checking the MD5 reported by the site (the filename), precious megabytes could be saved by not downloading an image already in your client. I've been using this for a couple of weeks now (since v399), and so far it seems to be a big help.
Basically, it just gets the filename of the original image from the same element that the download url is pulled from and strips it down to just the MD5.

`[30, 4, ["md5", 15, [27, 7, [[26, 1, [[62, 2, [0, "div", {"id": "stats"}, null, null, false, [51, 1, [3, "", null, null, "example string"]]]], [62, 2, [0, "ul", {}, null, null, false, [51, 1, [3, "", null, null, "example string"]]]], [62, 2, [0, "li", {}, null, null, false, [51, 1, [3, "", null, null, "example string"]]]], [62, 2, [0, "a", {"id": "highres", "itemprop": "contentUrl"}, null, null, false, [51, 1, [3, "", null, null, "example string"]]]]]], 0, "href", [84, 1, [26, 1, [[55, 1, [[[9, ["^.+/data/.{2}/.{2}/([0-9a-f]{32})\\..+$", "\\1"]], [5, "hex"]], "//cs.sankakucomplex.com/data/ff/5a/ff5aaac1edc863df800ec5a75515ae7a.png?e=1590581484&m=79FdfblEAFkwUN2DeN9-Tw"]]]]]]], 0, false, "md5"]]`

**Comment by Zweibach** [comment]
The default Sankaku parser already fetches md5 hash so I'm not entirely sure what yours does any different?

**Comment by GoAwayNow** [comment]
It does? Since when? Well, since v400, I suppose. I sent it to the dev then because of all the wasted bandwidth I was running into with my SC subscriptions. It wasn't in the changelog, and since I already had the change, it looked the same on my end, so I thought it wasn't added.

**Comment by Zweibach** [comment]
The current default was added in v392 though, so Hydrus has been pulling md5 hashes for months by now. Even the previous default from v314 does it and that's about two years ago.

**Comment by CuddleBear92** [comment]
The thing is with default parsers.... they dont get updated with the client update at all.

**Comment by imtbl** [comment]
Closing this because it's already been added as Zweibach stated. Please reopen if necessary.

On a sidenote, if you are a heavy Sankaku user, I recommend the user-created downloader that utilizes their new JSON API: https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/736d4ed733bd9f194e53daac149082d96552a799/Download%20System/All-in-Ones/Single-Sites/sankaku-api-risky-2020.03.03.png

It imposes far fewer limits (in terms of throttling) and can fetch 50 pages with 100 files each at once. I've been able to download over 50k files in a day with this without running into any issues.
