### ISSUE TITLE
Tag count searching

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#280]
Different from the `system:number of tags` predicate. This is for searching for how many of a specific namespace's tags are present on the file. Such as searching for images with, for example, two `character:` tags. See these examples on [danbooru](https://danbooru.donmai.us/wiki_pages/help%3Acheatsheet#dtext-n2-3-6).

A possible usecase is looking for `chartags:2` + `solo` to either find images misstagged with `solo`, misstaged with one or more characters, or cases where one character has multiple character tags and is alone in the image. Last one is the desired result of course while the first two are good for finding misstagged images.

I imagine that it'd be a system predicate with perhaps the possibility of having written syntax for quick access. Perhaps by using `"namespace"tags:`. Example: `persontags:5` for finding images tagged with five real persons.

**Comment by bbappserver** [comment]
I would also like exclusions i.e count of zero.

```
-creator:*
```
Is the kind of search I find myself wanting to do fairly often.

Of course this type of search would be very expensive over everything on file, so maybe rather than a search predicate it should be a filter operation that occurs post query.

Then if you actually want to filter everything, you can 
```
system:everything
limit:0
```
And then filter by namespace incidence.

**Comment by Mengmoshu** [comment]
@bbappserver Have you *tried* `-creator:*`? Because unless I misunderstand you that has been possible (and even has specific optimizations) for a long time.

And if I have misunderstood you it's probably because you've gone beyond concise into sparse.

**Comment by hydrusnetwork** [comment]
@bbappserver @Mengmoshu Yeah, if you just type "-creator:", you should get the special '-creator:anything' result. That should do what you want. It would be expensive, but there are optimisations because the db can do fairly fast bare namespace lookup, especially when mixed with other tags.

I keep meaning to do counted namespaces, but it keeps slipping. I want it myself. Thank you for making this job--it will make sure this gets done.

**Comment by hydrusnetwork** [comment]
I forgot to say yesterday--this should be ready for 405. You can add a namespace to system:number of tags, including a blank entry for unnamespaced, and even add wildcard namespaces, if you ever want to see all files with at least two char*: namespaced tags.

Also, all num_tags search code has received an optimisation pass. It now uses the same tag caches as regular tag searching, and searches more cleverly. When in a normal 'my files' kind of search, and doubly so when mixed with other search predicates, it is often 10-100 times faster on my dev machine. Let's hope that holds up IRL!

**Comment by bbappserver** [comment]
@Mengmoshu It seems to be a bug
https://github.com/hydrusnetwork/hydrus/issues/396
