### ISSUE TITLE
Allow users to type out 'system:' predicates

### ISSUE THREAD

**Issue by Mengmoshu** [hydrusnetwork/hydrus#328]
Make `system:` predicates autocomplete filter the way real namespaces do. It's a bit counter-intuitive and slow to have to pick the predicate out of the list *and* ensure the search field is empty when you know which `system:` predicate you want. It'd be even nicer if we could type out the whole thing, since some users type very fast.

May have been discussed on Discord in the past.

**Comment by bbappserver** [comment]
If you start typing a system predicate, hydrus can launch a cancellable fuzzy search for other things but once you've typed
sys it should pop up like a code completion if you want it ti be really fast.

**Comment by thatfuckingbird** [comment]
Not exactly autocomplete, but related: I've written a parser for system predicates in the past, that takes text like
"system:number of tags < 5" and extracts the predicate into an easy to work with form (supports all predicates).
It was sent to dev and he plans to integrate it just didn't get around to it yet (for example it can easily go into the same dialog that does the parsing for OR and other logic expressions, and can also be used for API).

Adding a simple autocomplete that just filters the system predicate list for matching predicates shouldn't be hard. Since tags real tags can't start with system:, you don't need to mix real tags and predicates in the autocomplete list.

**Comment by ShadowJonathan** [comment]
This could hook into the `system:` tag parser (that's being developed for the API, iirc)

**Comment by hydrusnetwork** [comment]
This is possible these days! Not every system predicate is parsable, but most are, and I've been making sure to change the labels of system predicates to nice-to-parse forms. Ticking off, thank you all!
