### ISSUE TITLE
Hydrus tag auto-complete steals up/down/enter keypress from IME

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#34]
Here's another tough one for you: When entering Japanese text, the auto-complete box steals the keypress for up, down and enter.

Usually, they would do this:
* Up: Select previous suggestion
* Down or Space: Select next suggestion (space works in hydrus)
* Enter: Confirm & insert text

So normally you'd type like this:
1. "kosimizu" → you see "こしみず" on-screen, underlined to show that it is still being edited
2. space a few times to select the right written form → you see 輿水 on-screen, selected to show which fragment of text you're replacing
3. enter to insert the text → 輿水 is inserted properly into the textbox

But what actually happens is this:
1. "kosimizu" → seems normal:
    ![image](http://a.pomf.se/knpxfr.png)
2. space a few times → seems normal:
    ![image](http://a.pomf.se/gradim.png)
    * If you over-shoot you can't use the up key to go back to the right suggestion here, hydrus will intercept that key
3. enter → everything but the japanese is tagged, and the japanese is moved to the start of the textbox
    ![image](http://a.pomf.se/wonflu.png)
4. enter again (in an attempt to get out of the japanese editing mode) → the dialog closes and the image seems to be tagged with "character:" temporarily

**Comment by hydrusnetwork** [comment]
This is an interesting one!

I can't figure out an easy way to detect IME mode from wxPython, so I have temporarily set 'tab' to change the colour and mode of the text control so that it captures all key events (except a future tab press, which will return it to normal). Please let me know if you still get problems with this in future!

**Comment by ScoreUnder** [comment]
Taking tab might have problems of its own, if tab is intercepted then it might be difficult to navigate the dialog box with the keyboard.

**Comment by hydrusnetwork** [comment]
I actually made this shift+tab in the end, so that tab could be the new 'get the results now'. Let me know if this causes problems--I can change it easily.

**Comment by ScoreUnder** [comment]
This still does leave me a little lost when keyboard navigating. In dialog boxes like the tag siblings box, I usually expect tab to take me from the left box to the right one (and shift+tab to do the reverse). Is it possible those could be remapped? e.g. f5 to get the results now and insert to disregard IME-specified keys?
(Or ctrl+r / ctrl+d if key locality is an important issue here; I'm not entirely sure myself what these functions should be mapped to)

**Comment by hydrusnetwork** [comment]
I've actually hit this myself, now I think of it.

Insert is now IME mode toggle, but I can't do F5 for fetch results because there is a global hook on that (another thing I want to fix--better shortcut options so anyone can completely customise this stuff will be on the voting list), so I did Ctrl+Space.

Unless Ctrl+Space is a problem for some reason (I think it makes a non-breaking space in OS X or something, so maybe that breaks the shortcut--I'll check it before I put the release out), I'm going to close this now and put off further shortcut customisation for when it is user-editable.
