### ISSUE TITLE
Duplicate Filter Hover Window changes next click on image to shift-click

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#384]
## Environment

Hydrus version: 403 executable
Platform: Windows
OS specifics: Win x64 10 Pro 1909

## What happens

It seems that now in the duplicate filter, if you click anywhere on the hover window (that has all the buttons to skip, set 'this is better', stop, etc) it will make the first click you do back on the image act like a shift-click (which my left-shift-click pans the image, while the right-shift-click will do nothing). The second click after this will work as intended. 

## Steps to reproduce

1.Launch the duplicate filter having at least 1 potential duplicate pair
2.Click anywhere on the hover-window (either on the pane or on a button)
3.Click (and/or drag) the image or the background to try to use a filtering mouse shortcut
4.Note that you are just panning the image instead of setting a relation

## Desired outcome

Clicking the mouse will do the selected filtering shortcut. Ex: Left click will set 'this is better' instead of doing the equivalent of a shift-click and just panning the image

**Comment by hydrusnetwork** [comment]
Thank you, this should be fixed in tomorrow's 407.

This was an issue with the duplicate hover not being one that hides. On the other hovers, when you mouse the mouse off, they hide, and active focus moves to the media viewer.

With the dupe filter, the click off counts as a 'window-activating' click, which the shortcut system ignores. The mouse dragging seems to be activating quietly in the background, as some of this is still hard-coded when no other shortcut is caught. I have made it so mousing off a hover window immediately activates the media window, so no activating-click happens when coming off a hover window. Let me know if you have any more trouble with this.
