### ISSUE TITLE
version 404 resizing last column outside of its window width

### ISSUE THREAD

**Issue by Chad90b** [hydrusnetwork/hydrus#387]
## Environment

Hydrus version: 404
Platform:  windows
OS specifics: 10

## What happens

resizing the last column outside the width of the window itself should create a horizontal scroll bar, but it does not. so you cannot scroll to the side to grab the column and resize it back down again. this means you cannot resize this column anymore since you cannot grab the end to resize it.
you can in most cases resize the window itself and find the column end, though, and resize it back down this way

## Steps to reproduce

1. resize the last column so wide its outside the visible window space

## Desired outcome

a scroll bar should appear so you can view the entire length of the columns and the columns full content, or much less desirable: the column should not be able to be made wider than the visible window

**Comment by hydrusnetwork** [comment]
The secret here is that due to some pain in the neck sizing calculations related to the vertical scrollbar appearing or not, the final column is actually regularly sizing a little too large anyway, and to hide this fact, and stop an issue with dialogs growing a scrollbar-width with every open, I turned off horizontal scrollbars.

I will improve the column size memory code of the new list system so it compensates correctly for the vertical scrollbar.

**Comment by hydrusnetwork** [comment]
Catching up on some open issues. I believe both scrollbars are now working ok and multi-column lists are a lot more size-flexible.
