### ISSUE TITLE
version 404 media viewer in non-fullscreen hover/overlay issue

### ISSUE THREAD

**Issue by Chad90b** [hydrusnetwork/hydrus#388]
#114  Environment

Hydrus version: 404
Platform: windows
OS specifics: 10

## What happens

if you put the media viewer in non-fullscreen, the hover-overlay that shows urls for a file will show above the center-bars buttons preventing you from pressing any of the buttons

## Steps to reproduce

1. open media file in media viewer
2. exit full-screen
3. hover the last button in the top center menu; the url bar will appear above the button preventing you from pressing it

## Desired outcome

only show the url popup if the mouse cursor is not touching the center menu bar

## Error message / Log file / Screenshots

![2020-07-16_00-19-22](https://user-images.githubusercontent.com/68355086/87605911-08cd0900-c6fa-11ea-8bc0-a863981c445b.gif)

**Comment by hydrusnetwork** [comment]
Thank you for this report. For tomorrow's 407, I have it now drop down below the top hover in this case. I don't really like this, and at some point I'll figure out a 'flow' layout for the top hover's buttons, so that always fits in the space and won't spill over if the media viewer is really thin, but this is an easy solution for now.

![yo](https://user-images.githubusercontent.com/3878678/89347065-aff4ee80-d66f-11ea-8978-aae56b605b56.gif)
