### ISSUE TITLE
Tag import options should not apply to "additional tags" added through the API

### ISSUE THREAD

**Issue by thatfuckingbird** [hydrusnetwork/hydrus#456]
As discussed a few weeks ago with @hydrusnetwork after #317 was fixed. Some users of Hyrus Companion also ran into this after that bugfix, e.g. https://gitgud.io/prkc/hydrus-companion/-/issues/5

**Comment by hydrusnetwork** [comment]
Ok, so looking at this, it is a little more complicated than I thought when we spoke yesterday. The data storage used for Client API additional tags is the same one used when gallery/watcher parsing sends tags down to post/file urls, which _should_ be filtered.

I will have to expand that storage to store both 'filterable' and 'additional' tags, and since I am opening two channels, I may as well let you in the Client API call set filterable and/or forced as well. If the user wants to add 'process these', it is an additional tag, if you are manually parsing a hundred tags and the user wants them filtered like any other parsed tags, they can be 'filterable'. It'll probably be a new 'service_names_to_tags' style parameter. I'll update here once I have it sorted.

**Comment by hydrusnetwork** [comment]
Ok, should be sorted. I will expand the Client API help to talk about this, but basic change is 'add_urls' command now accepts two new parameters:

service_names_to_filterable_tags
service_names_to_additional_tags (a synonym for service_names_to_tags, which still works)

Tags sent to 'filterable' will be treated like any other parsed tag from a downloader. Those in 'additional' are be treated just like the 'additional' tags, and always added unless advanced tag import options (like 'don't add tags that don't already exist') are set. They should all spread down from watcher and gallery urls to their children, too.

Let me know if you have any trouble with it.

**Comment by hydrusnetwork** [comment]
You know what, I will change this to 'filterable_tags', rather than being complicated with 'service_names_to_filterable_tags'. Parsed/filterable tags don't have a service key--that's exactly what the tag import options filters do. That'll be simpler, and it is easy to change right now.

**Comment by hydrusnetwork** [comment]
Ok, should be sorted. I will expand the Client API help to talk about this, but the service_names_to_tags should now merge with and act like 'additional' tags in a tag import options. In general, they should always be added. To specify that's the sort of tag we are talking about, I have renamed it to 'service_names_to_additional_tags'. 'service_names_to_tags' still works and does the same thing, it is just now a synonym.

I have also added 'filterable_tags' as a parameter, for any API devs who write their own clever downloader and have tags that they do want filtered by any tag import options hydrus-side.

Let me know if you have any trouble with this.
