### ISSUE TITLE
Indicate presence of meta data such as colour profiles and Huffman optimisation in dupe filter

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#469]
Indication of huffman optimisation and prescence of metadata and probably a category for it along with the others. Probably a good idea to specifically note colour profiles.

**Comment by TheElo** [comment]
Explanation:

1. A identicator "This file has a embedded color profile" is the most crucial part here and has to be added as soon as possible imo.

Currently a lot of files are false positively displayed as "pixel-to-pixel duplicates" which is not true at all when one of those has a embedded color profile. Not only does this "metadata" directly dictates how to properly display a file but also as of Hydrus 413, Hydrus is not capable to display those files properly and ignores these profiles instead.

The embedded color profile tells how to correctly display the file but is also used correct/alter image colors by users and creators sometimes. The scenarios can go as far displaying a monochrome file as colored and then dedupping would show two equal 1:1 pixel duplicate colored files or one file could have good colors the other bad but still they would be displayed exactly the same and also get the 1:1 pixel duplicate indicator as false positive.

A indicator like is needed so the user is able to skip the pair or open it externally for comparison. In the future maybe Hydrus will get the ability of other image viewers to display those files correctly - but till then there should be a way for the user to distinquish and manually skip those files in dedup filter instead of deleting those accidently in belief that they are equal.

2. Presence of metadata
A indicator "This file contains metadata" would be helpful in the 1:1 case so the user knows that those two diffrent sized files are just because of meta content (this is currently implied with 1:1 dupes, but not communicated).

The next step after that would be to add a way to read the metadata, maybe as a button/shortcut that just shows two columns "Name/Content" so the user can read and compare metadata to make a better decision.

3. Hoffman color table optimasation
Technically not, but normally reffered to as metadata is a very commonly used losless compression method for images. It basically just interacts with color table, sorts it and removes unused colors iirc.
Images that are optimised this way create 1:1 pixel dupes, both files are equal. Logically the hoffman optimised file is the better one as it delivers the 1:1 same quality content at a lower filesize - these files should get a neutral/positve indicator maybe like "Hoffman optimised file"/"Lossles compressed JPG" when the other is not and vice versa.

This optimasation happens silently on some/many? image boards and places where people uploud images automatically. I works extremely fast and therefore could be created on diaplay of dupes to check, XnViewMP seems to be able to read a flag or something so it knows which files have that optimasation and which don't.

Having it would allow the user to further distinquish 1:1 pixel dupes.

**Comment by hydrusnetwork** [comment]
Thanks guys. The dupe filter now says if one or both files have an ICC Profile.

The subject of complicated image metadata has come up several times. I think what I should do is slap together a simple EXIF data viewer. I _believe_ I have all the tech I need for this, now. If I make a button on the media viewer to just view this any time you like, we'll start a hook into this that we can expand on later, rather than me dreaming of perfect systems some time far away in the future.

**Comment by hydrusnetwork** [comment]
As for Huffman optimisation, I don't know what that is, but if it is a flag I can pull from OpenCV or PIL, I can throw it on screen or place it on a 'advanced file metadata' dialog no problem. I'll do some research.

**Comment by hydrusnetwork** [comment]
I've got 'this file has EXIF data, the other does not' coming in tomorrow's release, along with a prototype EXIF data viewer. Unfortunately, I am not sure how to examine the color table for this Huffman stuff yet, so I'll make another job for that.
