### ISSUE TITLE
Delete files present in Hydrus when importing setting

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#528]
A delete file setting for when Hydrus tries to import a file already present in Hydrus.

**Comment by bbappserver** [comment]
Hmm I like it  but I think it needs to be some kind of special mode,  if it goes in the standard file import settings it sounds like a recipe for a mistake.

**Comment by Zweibach** [comment]
Why? Really, why? I fail to see how this differs any from the currently existing delete on successful import aside from it no longer leaving behind files that weren't imported just because they were already present. In which case I want them even less than the files that were imported and then deleted.

**Comment by hydrusnetwork** [comment]
Thanks. Perhaps it wasn't true when this issue was made, but if you have 'delete files on successful import' set, it will currently delete anything 'successful' or 'already in db'. Anything else, 'previously deleted', 'ignored', or 'error', will not be deleted.

When I do the upcoming import options integration, maybe the more detailed options that import folders offer could be integrated into a 'Local File Import Options' kind of thing that governs what to do in all possible end-states.

That said, I think this specific issue is no longer true, so I will close for now. Feel free to reopen if you want to reword it or if you actually have a bug and don't see 'already in db' being deleted.
