### ISSUE TITLE
Feature: Tag/Namespace management

### ISSUE THREAD

**Issue by Cazzar** [hydrusnetwork/hydrus#53]
When I was looking through my namespaces, I had noticed that I had a few mis-spelt namespaces (in my case, character) so I was thinking, maybe something could be done to merge a namespace?

This is namely for some cleanup things though I thought this might also work with the tags, though the parenting also provides that feature for singular tags.

**Comment by hydrusnetwork** [comment]
This is a good thought, thank you.

I think I will extend parents and siblings in future to be a little more intelligent, so that people can say things like 'I want all character namespaces to just appear as if they were normal tags' or 'rename the series namespace to copyright' and so on. I'll be looking at better censorship management after I finish the current downloader engine rewrite, so maybe it'll be a part of that.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
