### ISSUE TITLE
direct linking/hosting (to preapproved file services) for some images on the Hydrus network

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#56]
such file services would be like mega.nz,using the https://github.com/richardasaurus/mega.py repo,as making the master key public would allow u to have a 24/7 50gb space of storage,and i have gone over there tos,and i may not be a lawer,but it seems doing something like this is not against it.another one to whitelist would be imgur.
pls feel free to discuss it with me at rizon.net #bibanon

**Comment by hydrusnetwork** [comment]
This sounds like a great idea. I have considered doing something with Dropbox, but I don't yet have the time to work seriously on it. I plan to eventually add peer-to-peer capabilities to Hydrus, and having stable online nodes like this would be a great step in that direction.

I would also like to move some of my gallery code to external 'plug-in' files so that people can create and share their own more easily. Letting people create new plug-ins to represent different cloud storage services would free me up from having to create each one myself.

**Comment by pokeball99** [comment]
Agreed,then if they wanted,they could pull a pr,or u could have a public repo of summited plugins

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
