### ISSUE TITLE
Possibility of porting hydrus to mobile(ios/android)

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#60]
It  seems they have scripts for this kinda  thing ,but would you do it,as it seems that it might delay releases slightly due to the wizardry involved
http://kivy.org might be the best solution to this though

**Comment by ScoreUnder** [comment]
I'm not sure what the hydrus dev would think about this but I think it looks like a huge amount of effort to get that working. All WxWindows code would need to be rewritten for kivy, and the interface would need to be redesigned for small screens.

**Comment by hydrusnetwork** [comment]
Converting everything over would be a lot more work than I can fit in, and I suspect the complexity and CPU-heavy nature of the client is not a good fit for an app. I think someone with experience with app programming could write a really neat interface that would plug into an existing client running on a computer at home as a simple searcher/viewer. Inbox filtering, for instance, would work great on a phone. I am not sure I am the person to write such an app, as I have no experience doing that sort of code.

I am planning to expand the client's http interface in the near future to support remote searching and content updates like 'archive file' and 'add tag', so this will become a technical possibility quite soon.

**Comment by antonizoon** [comment]
Is it possible to host some kind of instance of the Hydrus server online, and expose a bit of a REST API? 

This way, we could possibly provide a window into the Hydrus network, and allow image viewer apps (just like Danbooru apps) to search and view images.

**Comment by hydrusnetwork** [comment]
@antonizoon That's my _general_ plan. It will probably have to be the client though, at least for now, since that is optimised for searching and presenting media--the repositories aren't designed for CPU stuff, so apps won't be able to offload searching or anything else difficult without major rewrites.

I've also been talking a bit about this here:

http://8ch.net/hydrus/res/471.html#1247

I am totally keen to open up hydrus's verbs to external programs. First step will be client file import via http POST, and then adding tags.

**Comment by michal-polrolniczak** [comment]
Maybe instead of making app, hydrus could host a booru page that would server every pictures with RealTime searching and editing tags? That way we could browser our collection on tablets/phones and still add tags, and the look would be customize on webbrowser side? And in the end, adding API would end up with unofficial clients that would add even more :-)

**Comment by pokeball99** [comment]
@bigretromike ,thats not really the spirit of the hydrus network........

**Comment by bigretromike** [comment]
@pokeball99 we already got most of the work done - the booru. Its always harder to make 3 separate clients than making www/api imo.

**Comment by pokeball99** [comment]
true,making an api would be simple,but not mr.hydrus here hosting an booru

**Comment by bigretromike** [comment]
to be honest, basicly it dose host it and shear it via "shear"
Basicly I see no point in colecting images in folders, because hydrus make it 10000% better, but it lack ability to look up those pictures from non supported os - like android. And I would love to be able to look them up via phone/tablet. yeah I could just SHEAR every picture there, but that would make it imposible to watch the way I would by shearing folder via smb/nfs - which I basicly can mount to ANY OS and look them up with external browser.
Or this is good point to start building apache/nginx booru as 3rd party and feed it with hydrus db..... hmmm....

**Comment by hydrusnetwork** [comment]
I would like to expand the local booru to do much more. Eventually, I would like it to use the API we have been discussing here in an AJAX way so it can run searches and add/delete files and tags just how an external script might.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
