### ISSUE TITLE
Hydrus sleeps between database updates

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#64]
Updating a database to the next version is almost instantaneous, but due to the use of sleep it becomes much slower. Updating a server database from v172 to v179 caused hydrus to spend 14 seconds in total just sleeping.

**Comment by hydrusnetwork** [comment]
This is actually intentional. DB updates are important, and I want to give people a bit of time to understand and follow what is going on, even when all that is happening is version += 1. It is also useful for people to notice on which version any crashes or other status updates happen. Since the delay works out to 2 seconds per week, I figured that was ok.
