### ISSUE TITLE
recognized as drawing software

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#640]
I just updated drivers for my huion tablet, and it decided that hydrus was a drawing program, along with a few other things that closed but I have no idea what as they weren't actively being used. 

This is less of a bug, as I have no idea how it would not be recognised by it as a drawing program, but more of a can you give people a heads up that it may be seen as a drawing program.

**Comment by bbappserver** [comment]
This is not a thing that is really in the scope of hydrus. Please direct inquiries at Huion support.
https://support.huion.com/support/home

I also don't know what it is for a program to identify another as a "drawing program", graphics tablet drivers are usually presented to the OS as a USB HID absolute pointing device, and the tablet itself is indifferent to the program it is providing input to.  Lots of tablet brands like to ship weird bloatware on top of this that may trigger if you are in hydrus, but this probably more has to do with the fact that your tablet is plugged in at the time than anything else.

In most systems, programs are grouped by the types of files they are declared as capable of opening.  My best guess is that your tablet considers Hydrus a drawing program since it accepts so many image files.  Or because of something the Qt widgets support.

**Comment by alidan** [comment]
I know its not really in hydrus scope to do something about it, but its a coinflip where to put this, bug fix as the program shutdown entirely the moment it asked to close drawing programs and I said ok, or a feature request as I don't think there is anything to do but add a small warning that it may be seen as a drawing program so shut it down in case an installer asks you to close drawing programs. 

I think people knowing this may happen would be a good thing long run.

**Comment by Zweibach** [comment]
As bbapp said, it's not a Hydrus side issue. Far as I know Hydrus does not make any file associations meaning there's nothing in the OS that says "Hydrus is this type of program". It's entirely on Huion. You should be aware that Hydrus does not edit any files outside of its own databse files, there's no drawing.

**Comment by alidan** [comment]
well aware, the program was still forced shut down by the driver, qtorrent ways to and I think acdsee
this program I do believe improper shutdown corrupted my db in the past, a first time use warning popup to make people aware 'some drivers may consider this a drawing program, so shut down before going forward with their installs' would probably help some people.
