### ISSUE TITLE
Hydrus client eventually crashes when clicking images

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#66]
This is the last thing I see:
```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python2: xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
[1]    15034 abort (core dumped)  hydrus-client
```

**Comment by hydrusnetwork** [comment]
Some guy with Debian also reported this, and now I am also getting it. My guess is the recent updated version of Pilow might be doing it--being unhappy with reading/writing some image data off the wx thread or something. Since it is so serious, I will check it this week.

**Comment by hydrusnetwork** [comment]
I can't induce the error on purpose, even if I spam click on/scroll through things. How often do you get this? Does it happen with only gifs (it has only happened for gifs, for me), or any old image?

**Comment by ScoreUnder** [comment]
I did last trigger it while searching the "animated" tag, so it could well be something to do with gifs.

On the other hand, it could just be that gifs render frames more often and so have a higher chance of colliding with whatever thread it's getting in the way of.

**Comment by ScoreUnder** [comment]
I've noticed this can occasionally happen even when it's loading the thumbnails for a search, without clicking anything.

I'm using pillow 3.0.0, wxpython 3.0.2.0, wxgtk 3.0.2, and python 2.7.10

**Comment by hydrusnetwork** [comment]
I went through all my image rendering code and couldn't find anything that was doing wx stuff outside of the wx thread, nor anything that I have particularly moved out of the wx thread in the last couple of weeks, but in looking through my v179 diff on github, I notice that my new 'is the mouse idle' calculation gets the current the mouse coordinates (wx.getmouseposition) in the daemon thread. It didn't even cross my mind that grabbing a couple of numbers could be an OS-level problem, but that's all I can see that could be causing it, and it also explains the random times this happens (my idle code kicks in every ten seconds).

I have put the code on the wx thread, and I haven't got the crash on Linux in the past ten minutes of occasionally loading some images, so perhaps we figured it out. I'll update if I do get the crash again, but otherwise I'd be interested in how v180 works for you next week.

**Comment by ScoreUnder** [comment]
I don't know about Win/Mac but on Linux you can query the mouse/keyboard idle time from the server itself:
https://thp.io/2007/09/x11-idle-time-and-focused-window-in.html

You will still need to do that on the main thread, but it will eliminate the need to keep a thread counting that kind of thing.

**Comment by ScoreUnder** [comment]
On the other side of things, you might find this pip library interesting:
https://pypi.python.org/pypi/wxAnyThread/
It is a decorator which lets a function execute in the main thread, while still allowing you to wait for it and get its result in the non-main thread.

**Comment by hydrusnetwork** [comment]
Thank you for the links. If you are interested, I have a method in ClientController.py called CallBlockingToWx. It has a lot of Hydrus-specific bells and whistles, but it basically does the given callable in the wx thread and returns the result to the calling thread. I fixed the mouse problem with a simple CallAfter though, because the problem method is really just a little quick thing.

Is this fixed for you now?

**Comment by ScoreUnder** [comment]
I haven't seen this crash since, so I think it's a yes. Thanks!
