### ISSUE TITLE
regexes searches for every word in a filename as a tag?

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#69]
every word in a filename should be able to be added as a tag aswell split up by spaces or commas in the filename 
for example a filename is something like this:
[random stuff] blonde_hair blue_eyes 1girl.jpg

that would then add all words into tags that the word contains.

on note, many booru image downloaders (the few of them) supports saving tags in the filenames with spaces between them or even commas if the user chooses (i got spaces :D )

**Comment by sttollgrin** [comment]
This is already supported, when you import files instead of clicking 'Import now' click 'Add tags based on filename'. From there you can extract tags from filenames using regular expressions. 

\w+ should be enough if the tags are separated by spaces / commas, however it will also pick up directory and extension...

![example](http://i.imgur.com/cmCpgxs.png)

**Comment by AreFinstad** [comment]
thank you, this actually works. its really confusing with the quick renamespace and the regexes and knowing what to use when you never have done so before.
it did import other things in the filename aswell but i guess its fine for now. atleast takes up 99.9% of the work of my back :D

**Comment by AreFinstad** [comment]
hmmm do you know whats wrong with this one? 
https://github.com/hydrusnetwork/hydrus/issues/65
