### ISSUE TITLE
Overwriting parent tags

### ISSUE THREAD

**Issue by fennekin2k** [hydrusnetwork/hydrus#701]
Recording a new pair with a parent erases the previous pair with the same parent.

**Reproduction:**
we have a pair (tag1 -> parent)
now add a pair (tag2 -> parent)
pair (tag1 -> parent) is deleted

**Environment:**
Hydrus version: 414
Platform: Intel Celeron N4000
OS specifics: Win10 x64 Pro

**Comment by hydrusnetwork** [comment]
Thank you for this report. I will check this out next week.

**Comment by hydrusnetwork** [comment]
Hey, I had a good look at this today, and I caught up with fleshing out my parent unit tests, and I am afraid I could not reproduce your issue. I am able to add multiple children to a tag and give a tag multiple parents. Can you say a bit more about how you see this problem, and perhaps an example of the sorts of tags that get it?

Is this in the manage tag parents dialog, for instance? You add a parent A->B when another parent X->B already exists, and then next time you open, only A->B one survived? Is there any chance the tags involved here might even have been in some sort of loop, like an A->B->C->A scenario? Do they have any siblings? If you try a really simple unique parent structure on your 'my tags' domain, something like 'a'->'c', and then 'b'->'c', do you get the same thing, or is that ok? I am wondering if perhaps some tags are getting collapsed here because one chain of siblings/parents is being merged with another.

**Comment by fennekin2k** [comment]
Not used: siblings, loops (A->B->C->A)
Used: hiearchy, namespaces (all tags namespaced)

I have two mirror namespaces. Any tag from the first n/space is also present in the second. N/spaces are completely separated. Tags in n/spaces are hiearchical (one parent, multiple children; recursive). During the design of the first n/space I didn't notice any errors, they started only with the second one (maybe I noticed too late).

The bug appears as a violation of the hierarchy.
I attach to the file only youngest tag, which raises all the other tags in the hierarchy. At some point, the chain breaks and doesn't reach the last parent(s).

Re-creation (delete then create anew) of a broken pair restores the chain with this tag, but breaks pairs of other tags that were attached to the same parent. They are still displayed in the list, but don't work.

Simple structures work without any errors.

I'll describe more precise reproduction conditions (tag structure) a bit later when I build it again from scratch to make sure it's reproducible.

**Comment by fennekin2k** [comment]
The error is not reproducible
