### ISSUE TITLE
Store image upscales like thumbnails

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#728]
AI based upscaling (eg waifu2x) has become popular recently but keeping upscaled versions of images in Hydrus is a bit clunky. I propose a system where Hydrus stores upscaled versions of images in a similar way to thumbnails. Where they live in a separate directory but are named with the same hash as the original. This way we keep all the metadata and such from the original image but can substitute in the upscaled version when viewing. These upscales could even be automatically generated by hydrus as a maintenance job (perhaps with some conditions for whether an image should be upscaled, like low enough resolution). This system would allow us to consider upscales to be transient and not necessary to backup since they can always be derived from the original. It also allows for upscales to be regenerated as the tech improves or the user changes parameters.

**Comment by pozieuto** [comment]
> These upscales could even be automatically generated by hydrus as a maintenance job (perhaps with some conditions for whether an image should be upscaled, like low enough resolution).
This is one of the uses cases of #720.

On its face, I don't like this way of handling generated edits of images. Giving specific types of files "special treatment" feels like a hackjob solution. I feel that effort should instead be invested in better handling of image sets and alternates, creating a more robust system that would be able to serve this use case just as well.

As pointed out, this would make it easy to discard "derivative / generated" files when making backups with external programs, like you can do with thumbnails already. However, once again, this use case is better addressed by improving or expanding upon existing systems - in this case, Hydrus' built-in database backup functionality should be expanded to allow conditional exclusions for media file backups.

**Comment by Zweibach** [comment]
I'd like it if the system went both ways because for some cases I'd like it if Hydrus could just serve me a downsampled/downsized image instead of the original.
Right now I'm considering putting my Hydrus on another PC and stationing it at a friend's place to reduce data usage. For something simple as archive/delete filtering I don't really need the full sized image but the size I like my thumbnails at is too small for the job.
Another usecase is for posting to services that have size and/or resolution limits. For cases like this though it's probably cheap enough to just generate on the spot that you don't need to save it for later use. Maybe a setting to keep the generated rescales for a limited time just in case?

**Comment by hydrusnetwork** [comment]
Thanks. My preference here is to use the existing duplicates system, ideally working better at automatic tasks in the future, and having nicer alternate-labelling and quick-navigation between relationships, to handle this. I want to support upscales and reencodes and things flexibly, but hardcoding feels like a rabbit hole, especially when duplicates/alternates have some overlap already, and I am particularly fearful of doing hash swaperoo tech. I experimented with tag swaperoo a while ago and it was a disaster, ha ha ha.

#720 is the basic answer here, and my longer comment I just posted [here](https://github.com/hydrusnetwork/hydrus/issues/1283#issuecomment-1328088447) is my image of how it would work on my end.
