### ISSUE TITLE
client will not start after update to v180 & v181 from v179

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#74]
client will not start after update to v180 from v179.
i did first overwrite with the extraction, that didnt work.
i did so try the installer and that didnt work either. 

i get greeted with this window when i start v180
![](http://i.imgur.com/KRhdI29.png)

here is the logs: https://drive.google.com/file/d/0B-hww4iUE6HscGxkeEFPYklwZTQ/view?usp=sharing

also to note, v179 does still work when i just overwrite the folder.... which is a good thing XD

**Comment by sttollgrin** [comment]
Similar problem here, client starts just fine, however just after startup I get
```
UnicodeDecodeError
'ascii' codec can't decode byte 0xa0 in position 1: ordinal not in range(128)
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUICommon", line 584, in EventMenu
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUICommon", line 536, in _UpdateList
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUICommon", line 2913, in SetPredicates
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientData", line 1310, in GetUnicode
```
and no system predicates are available - search doesn't work either

0xA0 is non breaking space (nbsp) - I'm guessing the ConvertIntToPrettyString method uses locale settings to return string like '1 234 567' for number 1234567, and if the locale settings has nbsp as thousands separator - it breaks hydrus GUI because wx fails to display nbsp.

I've performed small test - hydrus client works fine with 999 files, all system predicates are displayed and work fine, however upon importing 1 more file everything breaks - no more system predicates, no more search, every new tab results in the error above being shown. I'm guessing that the problem is with 'system:everything (999)' becoming 'system:everything (1 000)'.

As a workaround, in system locale I've currently changed my thousands_sep to regular space, and additionally disabled digit grouping, client started working again, displays predicates like 'system:everything (12345)' - without spaces.

**Comment by AreFinstad** [comment]
well i dont even get to the main screen sooo

**Comment by eider-i128** [comment]
Can confirm nbsp is causing problems. Disabling grouping or changing separator to other character (for example ",") fixes problem. Locale Emulator can also be used as workaround.

**Comment by hydrusnetwork** [comment]
Hey, sorry for my slow reply here--I don't have much time this week. You figured out what was wrong--in my recent big unicode rewrite, I missed the one line where I ask the OS for a formatted version of large numbers. Anyone with a slightly unusual "123,456" separator is getting an ugly bytestream instead of a nicely encoded unicode string, and so is getting that error. Rolling back to v179 is possible.

This is fixed for tomorrow's release.

**Comment by AreFinstad** [comment]
im getting this same error in the new v181 update from v179

**Comment by AreFinstad** [comment]
the hotfix fixed the issue :D thanks guys! <3
