### ISSUE TITLE
PTR::mappings has roughly 4GiB in redundant indexes.

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#758]
The `client.mappings.db` has both
- The primary key constraint `PRIMARY KEY(hash_id,tag_id)`, and
- The UNIQUE key constraint `UNIQUE(hash_id,tag_id)`

For all tables of all services.
**HOWEVER** The primary key constraint is sufficient to ensure uniqueness, and is the index is provided by the table ordering.

This means that the uniqueness constraint is an unnecessary additional BTree that
 - Consumes about 16 GiB (at least for current mappings 10), about 0.7GiB additional with the other tables (your mileage may vary depending how big local tables are)
 - Costs additional processing to update the redundant index, roughly doubling the time to perform an insert. 
## Environment
Hydrus version:20
Platform: All

**Comment by bbappserver** [comment]
Is ran this SQL
```sql
--Drop the indexes
DROP INDEX "main"."current_mappings_5_hash_id_tag_id_index";
DROP INDEX "main"."current_mappings_10_hash_id_tag_id_index";

DROP INDEX "main"."pending_mappings_5_hash_id_tag_id_index";
DROP INDEX "main"."pending_mappings_10_hash_id_tag_id_index";

DROP INDEX "main"."deleted_mappings_5_hash_id_tag_id_index";
DROP INDEX "main"."deleted_mappings_10_hash_id_tag_id_index";

DROP INDEX "main"."petitioned_mappings_5_hash_id_tag_id_index";
DROP INDEX "main"."petitioned_mappings_10_hash_id_tag_id_index";

--Prepare to vacuum large database
--If you do this in a running hydrus remember to set the pragmas back or open a brand new connection after you're done with the hydrus settings

--I had an old hydrus database with a low page size, this is a good opportunity to resize the pages.
pragma page_size=4096;
--This is adequate for systems with 16GiB, half it for systems with 8GiB, double it for 32GiB, significantly reduces repeated reads
pragma cache_size=-2000000; 
pragma threads=4;

--be less aggressive with syncing, but don't use memory only, for large database files this can make the OS stall as it runs out of memory
pragma synchronous=1;
--Don't use in memory tables for big writes or we might eat all the memory
pragma temp_store=1;

--Tell the database engine to use the more efficient access patterns that you can get with an exclusive lock
pragma locking_mode=EXCLUSIVE;

vacuum;

--Restore the locking mode
pragma locking_mode=NORMAL;
--Restore other pragmas here
```

**Comment by vickyorlo** [comment]
More than halving the database size, letting us accumulate _twice_ as many shitty tags? Why, that sounds positively based, count me in.

**Comment by hydrusnetwork** [comment]
I am sorry, but I believe the primary key is (tag_id, hash_id), not (hash_id,tag_id). The primary key is for performing tag-first queries (get all files that have tag xxx), and the unique index is for performing hash-first (get all the tags for file yyy). As far as I know, both are still required for core functions.

In SQLite, if you do not have an index that starts with the columns for which you have data (e.g. searching by hash_id, when you only have (tag_id,hash_id) index), EXPLAIN QUERY PLAN should show you a SCAN plan instead of a SEARCH plan, meaning the entire table must be iterated through to find your results. This would mean importing a file to your cut-in-half database (which updates some caches that perform the 'all tags for file yyy') might take some time as the billion rows were fetched.

I am not sure if instead having a non-unique single column (hash_id) index would store less data. This may be worth exploring. However I think it would make hash-based queries run a little slower, I think, as the index would be _non-covering_.

As an aside, if you query a normal mapping table with _both_ tag_id and hash_id, I think it chooses to use the primary key. In IRL data, searching mappings tags first tends to be about 2.5 times as fast as files first, simply due to distributions of the typical data you see. It may be worth double-checking this is true and making sure that ANALYZE and sqlite_stat1 is also figuring this out.

I have explored dropping an index, then doing tag processing to get the ptr synced, and then recreating the indices, but this proved impractical for IRL situations by making the in- and out- overhead a potentially ten-hour operation (not to mention adding this 16GB on to the transaction size, both at start and end). If it is logically possible with modern sync, it would need a special super-idle sync mode for the UI.

If you believe I am incorrect somehow, please let me know.

**Comment by bbappserver** [comment]
> I am not sure if instead having a non-unique single column (hash_id) index would store less data. This may be worth exploring. However I think it would make hash-based queries run a little slower, I think, as the index would be non-covering.

I have examined this option, and posted the extended answer to the discord.

The short answer is you're right, that reverse index is pretty important so we can't just drop the index, I didn't notice the columns were reversed.

But the `UNIQUE(hash_id,tag_id)` is still wider than it needs to be and has an extra lookup for the uniqueness, which can be handled by the primary key, and would always be faster with the primary key.
