### ISSUE TITLE
Identical images not detected as identical when only one has alpha channel

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#770]
Consider these visually identical PNGs that use the five valid PNG pixel formats:

![png_gray](https://user-images.githubusercontent.com/67081751/103464697-91357980-4d2d-11eb-92f5-7fa1a4e4297a.png) `0`: grayscale
![png_rbg](https://user-images.githubusercontent.com/67081751/103464695-91357980-4d2d-11eb-904e-3ec995fce6b8.png) `2`: rgb
![png_pal8](https://user-images.githubusercontent.com/67081751/103464698-91ce1000-4d2d-11eb-973c-c31a7f3ca384.png) `3`: indexed
![png_graya](https://user-images.githubusercontent.com/67081751/103464696-91357980-4d2d-11eb-9671-22ac02246bb7.png) `4`: grayscale + alpha
![png_rbga](https://user-images.githubusercontent.com/67081751/103464694-909ce300-4d2d-11eb-871f-8976756f6843.png) `6`: rgb + alpha

Hydrus detects that `0`, `2`, and `3` are all pixel-for-pixel duplicates, and that `4` and `6` are pixel-for-pixel duplicates. However, the six other combinations are not given this designation, because one has an alpha channel and one does not, even though the alpha channel is entirely unused in the one that has it. (Though if the alpha channel _were_ used, it would be useful for Hydrus to still mention that the color values of the pixels are identical.) This could be a "missing feature" as much as a bug, but it's remarkable to me that identical rgb, grayscale, and indexed images get properly matched despite storing color information very differently, while identical rgb and rgba images do not.

Of course, it is inefficient to save images with no transparency using a pixel format that includes transparency, but it still happens in practice (just as with other bad ideas like pixel-for-pixel duplicate PNGs of JPEGs, which I also encounter). I have been running into this issue with real media downloaded from the internet frequently, and wondering why Hydrus keeps giving me duplicates that appear completely identical while not saying that they are. As it turns out, it is Hydrus deceives me, and not my eyes.

This is distinct from #693, which wants duplicate detection to work better with alpha channels overall, and is not concerned with pixel-for-pixel duplicate detection.

Hydrus version: 423
Platform: Windows 10 x64

**Comment by bbappserver** [comment]
I think terming the alpha channel unused, or the images as identical despite one having an alpha channel and the other not is somewhat imprecise. 

But if I've understood correctly just to clarify:
1. This is first of all after the detection, and actually in the filtering GUI.
2. Hydrus should treat an two equivalent images in the same colour model as the perceptually identical iff:
   - One does not have an alpha channel
   - The other has a fully opaque alpha channel

I believe you would be correct in treating this as a bug not a missing feature.

It appears that the reason is that hydrus only considers the image pixel hash, and doesn't actually reevaluate the displayed images which must differ if an additional channel becomes involved.  Otherwise it would seem that they should be presented as pixel identical.
#### ClientMedia.py:108
```py
        if c_hash not in hashes_to_pixel_hashes:
            
            path = HG.client_controller.client_files_manager.GetFilePath( c_hash, c_mime )
            
            hashes_to_pixel_hashes[ c_hash ] = HydrusImageHandling.GetImagePixelHash( path, c_mime )
            
        
        s_pixel_hash = hashes_to_pixel_hashes[ s_hash ]
        c_pixel_hash = hashes_to_pixel_hashes[ c_hash ]
        
        if s_pixel_hash == c_pixel_hash:
            
            is_a_pixel_dupe = True
            
            if s_mime == HC.IMAGE_PNG and c_mime != HC.IMAGE_PNG:
                
                statement = 'this is a pixel-for-pixel duplicate png!'
                
                score = -100
                
            elif s_mime != HC.IMAGE_PNG and c_mime == HC.IMAGE_PNG:
                
                statement = 'other file is a pixel-for-pixel duplicate png!'
                
                score = 100
                
            else:
                
                statement = 'images are pixel-for-pixel duplicates!'
                
                score = 0
                
            
            statements_and_scores[ 'pixel_duplicates' ] = ( statement, score )
            ```

**Comment by hydrusnetwork** [comment]
Thank you very much for this report. I am sorry it has taken me the year to get to it. A user reminded me that I still had this to figure out, and after recently adding the pixel hash system to the database, it is a good time to fix this. These test images were excellent, they really helped me figure it out.

> it's remarkable to me that identical rgb, grayscale, and indexed images get properly matched despite storing color information very differently, while identical rgb and rgba images do not.

I normalise all my images to 24/32bit RGB or RGBA on load, no matter what their source, and then the pixel hash I use to test if two images are pixel duplicates is simply the sha256 hash of the raw bitmap bytes. Assuming all the numbers/conversions are nice and we have no ICC profiles making weird colours, a greyscale image generally converts perfectly to RGB.

So the problem here was that my pixel hash doesn't deal with the bridge between RGB and RGBA. My system isn't clever enough to do 'these are pixel dupes but B has an interesting alpha channel', but if there are a bunch of these sorts of images IRL in future, I will consider adding this. For now, I have added a test so that if the alpha channel is completely opaque, the image is converted to RGB for the pixel hash calculation.

All five of your test images now have the same pixel hash in tomorrow's release. There is a secondary problem that this is only fixed for new images going forward, so any opaque-alpha-channel images already in your database would need to have their pixel hashes recalculated for full pixel hash search to work for them. I do not track which files have transparency, but I would not be surprised if this is added in future to allow for targeted recalculation. The problem may be mitigated in that many users will not have finished calculating their pixel hashes from when I added the system--I expect users with millions of files will take months of background work to catch up. And advanced users can add the job through regular file maintenance. I will keep this in mind and pick a good time to retroactively fix bad alpha pixel hashes for all users.

Please let me know if you have any more problems.
