### ISSUE TITLE
Can't update to v396 - HELP :(

### ISSUE THREAD

**Issue by MAKCUMU3ATOP** [hydrusnetwork/hydrus#787]
## Environment

Hydrus version: v395 exe
Platform: Windows
OS specifics: Win10

## What happens

I sucsessfully updated to v 395 but now I can't update to v396 because of error (see screenshots). I tried several times to downgrade and update step by step but no luck. Now I'm stuck because my network version 18 and I need 19 to refresh my account key. Please help.

## Steps to reproduce

1. Launch v396 updater exe.
2. Wait for updating
3. Get error

## Desired outcome

Update to newest version.

## Error message / Log file / Screenshots

[client - 2021-1.log](https://github.com/hydrusnetwork/hydrus/files/5853477/client.-.2021-1.log)
![h1](https://user-images.githubusercontent.com/77820900/105444005-b4d94900-5c75-11eb-9d4c-194eb704ff1a.jpg)
![h2](https://user-images.githubusercontent.com/77820900/105444014-b86cd000-5c75-11eb-8388-29a5fcb27745.jpg)

**Comment by Zweibach** [comment]
Try deleting the tag you see there at the end before you update again.

**Comment by MAKCUMU3ATOP** [comment]
> Try deleting the tag you see there at the end before you update again.

Thanks for the reply. Yes, I thought about that, but problem is I do not have these tags! No "newweek", no "newstart" or that other words. I can't delete cause they aren't existing. Or I should look somewhere else?
![111](https://user-images.githubusercontent.com/77820900/105563583-3dfc8880-5d27-11eb-87a1-9cb59f9bed34.png)

**Comment by hydrusnetwork** [comment]
Hey, I am sorry for the trouble here. I am confident we can figure this out, but it may take a bit of back and forth.

It looks like you ended up with a borked tag in your 'subtags' table, and the update can't figure it out. Perhaps that bad tag exists on a file that was deleted, or from the PTR if you sync to it, so while you do not get the result in your 'my files', it exists in the master definition for other reasons.

I am not sure why the text has become non-decodable. This could indicate hard drive corruption, so it may be worth skimming the "install_dir/db/help my db is broke.txt" document, and perhaps running crystaldiskinfo as it describes to make sure your drive is healthy. We'll now try to fix that one bad tag, but if it turns out there are many as corrupted as this, we may end up trying the larger recovery operations in that txt document.

PLEASE MAKE A BACKUP HERE IF YOU DO NOT ALREADY HAVE ONE, JUST IN CASE THIS GOES WRONG

Please close your client, go to install_dir/db folder and run the 'sqlite3' executable program. This will bring up a terminal. Please copy and paste these lines exactly, one by one:

```
.open client.master.db
ATTACH "client.caches.db" as cc;
SELECT docid FROM subtags_fts4 WHERE subtag MATCH "just finished my workout*";
.exit
```

Does that give one or more number results? Hopefully it gives one. Write it down before you do the '.exit'.

If it gave one, please do this. If it gave more than one, stop and let me know. I have written 123456 as the id, but replace it with the number given from the first query.

```
.open client.master.db
ATTACH "client.caches.db" as cc;
UPDATE subtags SET subtag = "broken just finished my workout tag" WHERE subtag_id = 123456;
UPDATE subtags_fts4 SET subtag = "broken just finished my workout tag" WHERE docid = 123456;
.exit
```

If that worked ok, try updating again. You may have more broken tags, or that may be just the only one.

If the UPDATE lines fail, let me know.

**Comment by MAKCUMU3ATOP** [comment]
> Hey, I am sorry for the trouble here. I am confident we can figure this out, but it may take a bit of back and forth.

Hello and thank you for the reply!
CrystalDiskInfo says my disk is in GOOD condition:
![888](https://user-images.githubusercontent.com/77820900/105631155-a5b0f180-5e55-11eb-8409-b5c0ebd11e05.jpg)

Also I did what you said and get more that 1 number - here are they all:
![555](https://user-images.githubusercontent.com/77820900/105631166-bc574880-5e55-11eb-9ce9-cce2fc08800d.jpg)

What should I do now? Thanks!

**Comment by hydrusnetwork** [comment]
Ah, damn, it looks like there are several tags that have that phrase, all near the start. Some tumblr, maybe, or artist series.

Please try again with this:

`SELECT docid FROM subtags_fts4 WHERE subtag MATCH "just finished my workout, remember*";`

If that produces no results, try:

`SELECT docid FROM subtags_fts4 WHERE subtag MATCH "just finished my workout remember*";`

If that produces no results, try:

`SELECT docid FROM subtags_fts4 WHERE subtag MATCH "remember every week is a new oportunitie*";`

Once you have just one 'docid', you should be good to do the UPDATE.

**Comment by MAKCUMU3ATOP** [comment]
Yes, it works!

I found that one specific number, and repaired it as you said. Afetr that my client updated normally. Now I have the latest version and can refresh it. Thank you very-very much! Can you tell my how can I donate to you for your hard work?

Oh also, using the chance to talk with the creator, I want to ask one more thing. Is it possible to download only that tags from community repository which I need? I mean - I have few thousands of pictures, but if I understand correctly - I should download hundreds of millions tags and subtags from all users of Hydrus and then my client will pick from it tags only for my pictures. It's heavy for downloading and processing, especially big load for harddisk and CPU. Is it possible to form a list of my pictures and download tags for them only? If yes - please hepl me how to do it? If no - no problem, I'm still happy to use Hydrus. Thank you one more time!

**Comment by Zweibach** [comment]
> Is it possible to download only that tags from community repository which I need?

No.

**Comment by hydrusnetwork** [comment]
Hey, I am glad we got you working again. I am not sure what happened there, but for whatever reason that one definition got messed up. Your hard disk seems yeah totally ok, so I guess we will chalk this up to some odd encoding blip somewhere along a tag processing chain that meant that tag wasn't stored properly. Or something like an unlucky rough power loss event or unhelpful/rude anti-virus file lock or cloud backup service that made your database write some bad data just for a tiny area. I have never seen that SQLite OperationalError before, and it is a surprise that just one tag would go bad. There are much more awful tags in the PTR for an older client than some tumblr '#' characters. In any case, you seem good now. Please let me know if you have any more trouble.

If you would like to support me, I have a Patreon at https://www.patreon.com/hydrus_dev . Any amount you can offer for as short as you like is always appreciated, but not at all expected. I am happy to help out.

Unfortunately you cannot just get the PTR's tags just for your own files. The system guarantees privacy and saves a huge amount of server CPU time and bandwidth by committing to the concept of a 'full sync'. It is definitely a big investment, about 42GB now I think, and hours of processing time even on an SSD. I only recommend syncing with the PTR if you are on an SSD and have a large collection. Otherwise, I recommend making a new 'local tag service' under _services->manage services_ and just adding private tags via downloaders or similar. If you are partially synced with the PTR right now, I recommend you pause it under the _review services_ window. It won't do any more work until you feel it is worth resuming.

I hope to have some filtering tech coming in this year that will let users sync with just parts of the PTR, like 'just get creator/character/series' tags and so on, which should allow users to easily grab just 10% or 30% or so of the current mass and skip things like 'title' tags if they don't care for them. Still, 30% of 1 billion records is still quite a lot.
