### ISSUE TITLE
Search autocomplete ignores certain valid tag characters

### ISSUE THREAD

**Issue by sulejman3** [hydrusnetwork/hydrus#799]
If a tag starting with a forward slash (`/`) and less than 3 other characters exists, it cannot be searched for.

## Environment

Hydrus version: 427
Platform: Linux
OS specifics: Debian 10 x86_64

## What happens
I have used tags like `/a/`, `/g/` for files related to imageboards. Forward slash `/` is apparently ignored by the tag autocomplete, and if the tag has less than 3 alphanumerical characters, it cannot be searched for. Tags shorter than 3 characters normally are brought up, but this rule does not apply here either.

`/` is a valid character, and searching works with longer tags such as `/wsg/` or `/pol/`. 

## Steps to reproduce

1. Set a  tag starting with any number of `/`, followed by less than 3 other characters
2. Open a File page and type the newly created tag in search field
3. Observe results

## Desired outcome
Please make tag autocompletion treat `/` as a regular character, since it is a valid character for tagging purposes.

## Error message / Log file / Screenshots
![Screenshot_20210128_214107](https://user-images.githubusercontent.com/30478613/106196654-fd32c280-61b1-11eb-949d-b3da43dedbd3.png)

**Comment by roachcord3** [comment]
I think in addition to `/`, `(` is ignored.

**Comment by hydrusnetwork** [comment]
Thank you, this is an interesting one. When you search for tags, certain characters are removed internally to help lookup by merging things. If you search '[intensifies]', this is actually treated as 'intensifies'. The way tags are stored for fast search also remove these characters, so you'll still get '[intensifies]' and 'intensifies' tags back for an input of '[intensifies]' or 'intensifies'.

Now for your issue: Since these characters are invisible to tag search, a search that only includes:

`[](){}/\"'-_`

Will count as the empty string '', and no search will be done.

I don't have a great solution here. This problem has come up in other ways, so I want to write an 'exact text search' mode for autocomplete where the characters will count. Perhaps I could make the exclusionary characters customisable in normal search, so you can turn '/' 'on'. I will have to think about it.

For now, if you just type 'a', you should get the results for '/a/'. When you search '/pol', it actually sends 'pol' down, which is why it seems to work.

If you want to search for all boards, and these tags are not on the PTR, your best solution I think is to try namespaces. Using 'board:/a/' would (with the right permissive autocomplete settings), allow you to type 'board:' and get all board tags. You can set this tag manually, or use siblings to map.

**Comment by sulejman3** [comment]
Hi, thank you for answering.
I should have stated it in the report, but using `a` alone does not bring `/a/`.
If `a` is used as a tag, typing one letter does bring it up, but since `/a/` starts with `/` not `a`, it is not brought up and `/a/` cannot be searched for.

**Comment by hydrusnetwork** [comment]
Damn, thank you. '/a/' not appearing for a short text query of 'a' is not intended. It is due to some different text matching logic for shorter queries. I get the same problem, I will fix this.

**Comment by hydrusnetwork** [comment]
I have looked into the problem. Unfortunately, with the current database structures, I cannot make a solution that does not add 50-200ms time on every search on a large domain, like the PTR. I have queued up a job to make a fast cache for this situation.

**Comment by hydrusnetwork** [comment]
This is now fixed for v430! I wrote the new cache and fixed the lookup logic. Thank you for you patience, please let me know if you have any more trouble.
![a](https://user-images.githubusercontent.com/3878678/108635592-ca44bd00-7445-11eb-963b-5e8d6905f1b3.png)
