### ISSUE TITLE
A corrupt PTR update fails processing silently instead of being moved out

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#836]
## Environment

Hydrus version:428(source)
Platform: Mac 10.13
OS specifics: 

## What happens

My PTR history has gone partially corrupt due to a crash of hydrus at the wrong time.  There is a partial update file, and several of the update files seem to be missing.

Pressing the "process now" button does not cause modal processing to occur as usual, it seems to do nothing, but I expect it just fails instantly and does not enter an error state or emit an error log.

Exporting update files shows there are missing

See also https://github.com/hydrusnetwork/hydrus/issues/835

**Comment by Radtoo** [comment]
I had this same issue on 433. A workaround for the issue in my case was to:
1. Get another intact copy of Hydrus + PTR via a Quicksync archive or a fresh Hydrus copy with the PTR added.
2. Move db/client_files/f*/* to a new folder (I assume it would equally work to use services->review services->remote->export updates).
3. Services->import repository update files from the new folder.

**Comment by hydrusnetwork** [comment]
Thank you for this report. As I just mentioned in #837, I think this is now fixed. When processing fails due to a corrupt file, the client schedules all update files for an integrity check and asks the service to perform a metadata resync which ensures it does not have any surplus update file records.

The only thing I don't really like is it tells the user 'please unpause repo processing once the file maintenance is done', which is not super user friendly. Perhaps I could schedule an 'unpause' signal once all repo update file maintenance is done, but I am also wary of several ways this could go wrong. Since this is emergency maintenance after a critical error, I am ok with the human having to restart things I think.
