### ISSUE TITLE
PTR update files cannot be re-downloaded from a specified point or corrected automatically.

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#838]
## Environment

Hydrus version:428
Platform: Mac 10.13
OS specifics: 

## What happens

While the processing status of the PTR seems to be resettable the download status does not.  Yes it's not really ideal to redownload every PTR file if only one of them is corrupt so I'm not suggesting that.  But if a PTR update file is found to be corrupt because either.

- The server reports that there is no such hash in requesting a subsequent update file for siad hash
- The PTR processing procedure detects a fault in the file's contents

Then ideally hydrus should start trying to automatically correct the issue by trying an earlier hash to redownload the file and then continue.  This might happen multiple times, but it's irrational to just download every single file after this point, you just need 1 error step at a time in case you have 99 good files and file 10 is the only broken one, so instead, treat it as though correcting the single file should correct the problem, and initiate the procedure.  If you fail again, it will just enter the exact same error handler, and keep repeating this one at a time until all of the gaps are filled.

Alternatively, I need a way to manually intervene and tell hydrus to clear all records of downloaded update files after a particular update number.  I don't want to have to redownload 10,000 update files, just the 60 odd near the current problem.

**Comment by hydrusnetwork** [comment]
Thank you for this report. As I just mentioned in #837, I believe this is now fixed with the new maintenance systems. If a single update file is incorrect, a metadata resync is triggered and the client refreshes all its knowledge from the server. This resync can also be fired off from _review services_ at any time. Any corrupt files will be removed, any surplus files will be delisted, and any holes then filled in with new downloads.
