### ISSUE TITLE
Feature request: use booru for tags only

### ISSUE THREAD

**Issue by ghost** [hydrusnetwork/hydrus#9]
Okay, so, I apologize if I missed this like the other stuff, but I've been playing around with the booru downloader and can't find it:

Is it at all possible (from a technical standpoint) to just use a booru (specifically, e621) as a tag source for downloading local tags, without downloading any additional images? IIRC, they use some kind of hashing to identify unique files, but I don't know how easy or hard it would be to match that against a local library's hashes.

What I'm looking for is basically a feature that allows me to make a local selection and say "download all tags from X booru for these images, according to my default tag options". Or to install a booru as a tag service that I can sync with like a tag repo.

**Comment by disposablecat** [comment]
Reposting this here because this is semipermanent and centralized:

Here is a working Hydrus Tag Archive of Derpibooru up to 1-24 (id 814383):

https://mega.co.nz/#!BsMw0aBZ!2iFV3TAH_QYzg4fg1kg_aCCpwyp4eCrS5LMTi2cDTqM

This has had various cleanup performed on it to make it suitable for Hydrus. Specifically:

-everything that could reasonably be interpreted as "creator:" has been replaced with that
-Ratings have been namespaced
-the most popular species and character tags have been namespaced
-OC: has been replaced with character:
-all files have series:my little pony
-spoiler: is a namespace, if you find those tags as infuriating as I do, uncheck it in Hydrus when you add this.

This matched about 1/5 of my pony folder, probably due to resizes and people from /mlp/ and /pone/ not overlapping with the Derpibooru userbase.

The working scripts used to create it have been updated here:

https://gist.github.com/disposablecat/9fa1ee3d036d2e353dcc

All the cleanup above was done automatically via derpicleaner.py - no manual adjustment was used whatsoever - so if anyone has any objection to any of it they can comment out those lines and re-run the scripts. This will also make updating this relatively easy.

**Comment by Mooninaut** [comment]
I don't know if this is any help, since it seems like you've already downloaded the entire dataset, but you *can* search for e621 posts by MD5 using the api. You search for the tag "md5:xxxx". Example: https://e621.net/post/index.xml?tags=md5:50bac7d7e9749656c98485eed00a6e79.

You can also do range requests on post IDs, instead of grabbing them one ID at a time, using the syntax id:min..max. For example, https://e621.net/post/index.xml?tags=id:200..299%20order:id&limit=100. The default limit on results per request seems to be 80, and the maximum they allow at present is 100. The default ordering is by id, descending, so I added the order:id meta-tag to change it to ascending.
