### ISSUE TITLE
New User: Importing Files Question

### ISSUE THREAD

**Issue by slelmir** [hydrusnetwork/hydrus#905]
Hi, I'm a new user, just started going through the guide, but I was wondering if anybody has an answer to a question I already have. I have hundreds of thousands of files I've downloaded from mostly from Pixiv using Powerful Pixiv Downloader, divided into folders like this: 
'single main tag/artist/source site (like pixiv, sankaku complex, etc)/filename with fittable tags'
Would I be able to integrate my folders and files into the Hydrus database while keeping the same folders and names? So in a way, I could use Hydrus to add and search by tags, and have everything collected in the database like shown above? And if it is possible, would I be able to open all the files in a single folder in the database at the same time in a Hydrus thumbnail window? Then I could add a single tag to all the files in that one folder? It would be cool to just drag and drop my already existing folders into Hydrus and everything just show up in the program. Sorry if this is asking too much at this point in time. My main issue is just not having enough filename space for all the tags I want in a single file, so if I just had a way to do that, I would be A-okay. Thanks if anyone can let me know.

**Comment by slelmir** [comment]
It would be nice to search by tags, title, filename, multiple types of identifiers like that

**Comment by Mengmoshu** [comment]
The fundamental design of Hydrus is that imported files go into Hydrus' folders. You can turn your existing folders and filename tags into tags as part of the Hydrus import process. But Hydrus will make copies of the files when you import them.

When you add the folder names as tags you can do a search in Hydrus for those folder tags.

Keep reading through the guide to find info on importing files, there should be something about tagging as part of importing. If you still can't figure out everything you need, I suggest joining the Discord and asking for help in `support_chat` since the turn around time for messages here is kinda slow.

**Comment by slelmir** [comment]
Ok, thanks man, I appreciate it

**Comment by Zweibach** [comment]
> Keep reading through the guide to find info on importing files, there should be something about tagging as part of importing. If you still can't figure out everything you need, I suggest joining the Discord and asking for help in `support_chat` since the turn around time for messages here is kinda slow.

Especially since the issue tracker is not intended to be used for support questions like these.
