### ISSUE TITLE
Account "Could not connect!"

### ISSUE THREAD

**Issue by ehawman** [hydrusnetwork/hydrus#913]
![image](https://user-images.githubusercontent.com/52979227/124054877-80b64100-d9e8-11eb-8a7a-0ff3fb81eea4.png)

Been seeing this since 443. I've tried and tried and it absolutely categorically refuses to cooperate. I try to keep on top of updates since it took me the better part of 9 months to get 10k updates fully processed (Is it supposed to take 30 minutes per update package? I ran that sucker 24/7 for most of a Y E A R)

Anyway what kind of information do you need from my end?

**Comment by bbappserver** [comment]
If it takes that long you are probably not on an SSD or a otherwise fast volume. it isn't supposed to take that long but if you don't have fast enough random I/O and a lot of things are accessing the database it's going to take quite some time as the processing is interleaved with other accesses.  For reference syncing the PTR on reasonable modern hardware and sufficient capacity with nothing else takes about 10 days.  It will speed up a lot as more of the database's index gets sucked into memory.

The PTR server has been temporarily down lately, so this does not appear to be an error in hydrus, it is functioning normally and responding as expected.  Let us know if the problem continues after a few weeks.

**Comment by ehawman** [comment]
Sounds good to me! Thanks. Yeah it's a spinny disk. I'll move it to my SSD and see if that doesn't improve matters.

**Comment by Suika** [comment]
There might be a problem with the IP being blocked by some stupid ISP rule. EIther way, if you can't pin or access https://ptr.hydrus.network:45871/ then use ptru.hydrus.network:45871.
@ehawman

**Comment by IlluminatiWave** [comment]
and moving it to the ssd solved it?
