### ISSUE TITLE
Client fails to start Fedora 34

### ISSUE THREAD

**Issue by manwithakeyboard** [hydrusnetwork/hydrus#920]
## Environment

Hydrus version: 446, linux executable
Platform: Linux
OS specifics: Fedora 34 (fresh install)

## What happens
Client fails to run.

## Steps to reproduce

1. In a fresh install of Fedora 34 (not upgrading from prior releases) run linux executable client, will silently fail.
2. Running via terminal returns error
3. client DATE.log file is created but is empty
4. Note: client worked in Fedora 33 (upgraded sequentially since Fedora 25? or 26)
5. Tried completely blank hydrus install but with or without existing database the error is the same

## Desired outcome
Client to run and hydrus to import old database.

## Error message / Log file / Screenshots

hydrus client started
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(client:38933): GLib-GIO-ERROR **: 21:12:20.315: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

Note: User is a brainlet and can not find where "core" is dumped but would attach if knew how.

**Comment by hydrusnetwork** [comment]
Hey, I am sorry for the trouble here. I did a little searching of that error, and I am no expert, but it looks like the new version of 'Wayland' (UI system) is having trouble with Qt. I do not create a DATE.log, so it sounds like that is some import or crash handler going wrong.

Can you check if your package manager has a package 'qt5-wayland' or 'qt5-qtwayland'? If you do not have it, see if you can get it and try again.

The problem here may be because there is a fundamental problem with Wayland, but I think more likely is there is an import problem, when hydrus is trying to boot it is loading some .so files from its install directory, and some from /usr/lib or similar, and the conflict between your Wayland and whatever the building Ubuntu machine has is throwing an error.

If qt5-wayland is a no-go, please try running hydrus from a terminal with the environment variable:

QT_DEBUG_PLUGINS=1

I am not sure this will work with a build release, but it may give more information with the error.

Don't worry too much about the core dump. Since we are in python, extracting useful information out of that is often more trouble than it is worth.

If we get more information, we may be following this sort of routine, forcing a python path in the installer rather than your system, but that may not actually be your problem. Might be useful background reading/scanning:

https://forum.qt.io/topic/111553/solved-qt-qpa-plugin-could-not-find-the-qt-platform-plugin-xcb-in

If this turns out to be a mega pain, the generally great solution to Linux flavour problems is to run from source, which isn't actually all that difficult these days. I have a help doc here on it:

https://hydrusnetwork.github.io/hydrus/help/running_from_source.html

Let me know how you get on!

**Comment by manwithakeyboard** [comment]
> Can you check if your package manager has a package 'qt5-wayland' or 'qt5-qtwayland'? If you do not have it, see if you can get it and try again.
>Package qt5-qtwayland-5.15.2-7.fc34.x86_64 is already installed.
No luck.
Setting
>QT_DEBUG_PLUGINS=1
then trying the client returns the same error.

> the generally great solution to Linux flavour problems is to run from source, which isn't actually all that difficult these days.
>which isn't actually all that difficult these days
>brainlet eyes glaze over after an hour trying to decipher instructions
ngmi, did find a workable solution though by using the windows release via WINE which never used to work (last tried in 2019) but now does.

**Comment by hydrusnetwork** [comment]
Ah, that's a shame. Perhaps this is just a version mismatch issue, and the Ubuntu the Linux build is made on--I think Ubuntu-18.04--has bad .so files for Fedora 34. I am glad you got things working through Wine!

If you would like to try running from source one day, let me know and I can walk you through it step by step. I'm on discord on Saturdays as well, feel free to DM and we can do it live.

https://discord.gg/wPHPCUZ

**Comment by puphime** [comment]
I would like to add to this by pointing out that you can work around this and still use the linux release by setting the env var GDK_BACKEND to x11:
`env GDK_BACKEND=x11 ./client`
