### ISSUE TITLE
idle state ruled by gpu usage

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#928]
An alternative to the CPU usage % to trigger an idle mode would be nice.
One that uses the GPU as games and such these days don't really use too much of the CPU on the higher end and the GPU is easier to track in this case. 

If this is a stat you can easily pull and use then i think that makes more sense for atleast me.

**Comment by hydrusnetwork** [comment]
Unfortunately, I use psutil right now to pull these sorts of stats, and I don't think it grabs GPU. Here's the docs of the basic system wide stuff it can give if you are interested:

https://psutil.readthedocs.io/en/latest/#psutil.Process.as_dict

I agree that when you have 8 cores or whatever, total CPU is not so useful. Perhaps, now I look, I can use the 'percpu' parameter to look at all CPUs separately:

https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent

If you are playing any vidya or doing encoding, one of those is going to be blasting at at least 80%.

**Comment by hydrusnetwork** [comment]
Unfortunately, it turns out I was tracking this per CPU core after all! I've changed up the options for tomorrow so you can choose how many cores need to exceed the % limit. Not sure if that is really helpful to your problem, but perhaps in some encoding situations having 4 > 25% is more useful than 1 > 50%?

If psutil starts offering GPU %, or there is another neat solution available, I'd love to revisit this.

**Comment by CuddleBear92** [comment]
That's sad to hear. And sadly there is very few games that max multiple cores aswell these days outside of the very top AAA titles. Just thought that the idea of tracking the GPU would be better for this as you are normally GPU locked in the first place.

Will have to try to play around with those new settings atleast. Encoding should and normally will pull 100% on all cores though so that im pretty certain on. Its more on the gaming side for the most part.
