### ISSUE TITLE
Space after period or comma won't render in macOS Big Sur

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#930]
## Environment

Hydrus version: v447
Platform: macOS
OS specifics: Big Sur 11.4

## What happens

Say you have some text like this: `Hello world. Welcome to Hydrus!`

The way that this is displayed in the client looks like `Hello world.Welcome to Hydrus!` This is purely a rendering bug, because the space is still in the character sequence, as you will be able to see from the repro steps below.

This is also a problem for commas (`,`) but strangely not for other punctuation marks, such as question marks (`?`), exclamation marks (`!`), quotes (neither double [`"`] nor single [`'`]), colons (`:`), semicolons (`;`), hyphens (`-`), nor slashes (`/`).

This has been a problem since switching to Big Sur; I apologize for putting off reporting it. It is worth noting that in the version that worked with both Catalina and Big Sur, this rendering bug only happened when the client was run on Big Sur.

## Steps to reproduce

1. In any field where you can type text, type a period (`.`) followed by a space (` `) and then any other character. You will see that there is no space displayed.
    1. Copy the text into your clipboard and paste it somewhere in another app, such as in TextEdit. You will see that the space is still very much in the sequence of characters.
2. Next up, try it with two spaces instead. You will see only one space rendered.
3. Do this in a field that has an autocomplete dropdown. You will never see a space rendered in that dropdown, even when you use multiple spaces in your text input. (Probably because multiple spaces are replaced with a single space.)
4. Open up a dialog where there is some text that has multiple sentences in it. Observe that spaces after a period are still not displayed.
5. Do all this with commas too. It's also broken for them.

## Desired outcome

The spaces should be displayed normally.

## Error message / Log file / Screenshots

First screenshot shows the general behavior:

<img width="556" alt="enter_text" src="https://user-images.githubusercontent.com/73802796/125691081-90be5b4f-6f6f-418f-a124-287cd7a00598.png">

Second screenshot shows how two spaces look (and how it's not consistent depending on where they're displayed):

<img width="437" alt="manage_tag_siblings" src="https://user-images.githubusercontent.com/73802796/125691138-1c56b6a0-42b4-4755-b202-e81ee93f25a7.png">

Third screenshot shows a known tag with a period and a space after in it, so you can trust that I am not just complete shit at hitting my spacebar:

<img width="435" alt="manage_tag_siblings" src="https://user-images.githubusercontent.com/73802796/125691249-f39bd31b-3a59-4374-b7dc-2d2751119b70.png">

Fourth screenshot shows it is not just in text inputs:

<img width="797" alt="manage_options" src="https://user-images.githubusercontent.com/73802796/125691770-d6e0a8ce-0125-4a65-9fd3-9958ba9124fc.png">

Fifth screenshot shows this behavior for commas too:

<img width="394" alt="hydrus_client" src="https://user-images.githubusercontent.com/73802796/125693376-2dfdaa5f-e101-4a4b-b0c8-b8aa488b3e0e.png">

**Comment by hydrusnetwork** [comment]
Thank you for this report. This appears to be a bug in Qt, something to do with the kerning calculations in Big Sur:

https://bugreports.qt.io/browse/QTBUG-88495

That report suggests this is fixed in 5.15.3. We are on 5.15.2 at the moment. I had a look around the Qt site, and unfortunately it seems regular people are not going to get 5.15.3 in public, we will have to wait for python Qt 6.0:

https://www.qt.io/blog/qt-offering-changes-2020
https://www.qt.io/blog/commercial-lts-qt-5.15.3-released
https://wiki.qt.io/Qt_5.15_Release

I do not really understand why patches are being locked behind a licence. Maybe I am misunderstanding something in the blitz of different dates and release types in those pages.

I am expecting to move to Qt 6.0 within the next year, after it has had some time to mature, and I hope we can expect a number of improvements for Big Sur.

I shall close this issue for now, since I do not believe I can fix it myself. I am sorry for the trouble.
