### ISSUE TITLE
ClientAPI Issues Discerning Parents/Siblings? 

### ISSUE THREAD

**Issue by seniorm0ment** [hydrusnetwork/hydrus#957]
I am having trouble confirming if this is an issue with the ClientAPI or Lolisnatcher Droid (app). But this shouls give a way to replicate it. Using Lolisnatcher Droid, if I do a search for something such as "video" I would expect nothing to appear because the PTR's ideal tag for "video" is "medium:video". It doesn't seem to autochange the tag after you type it either.

This could maybe be expected behavior for the API? However it is kinda confusing imo. It doesn't help that Lolisnatcher Droid doesn't visually seem to differentiate between siblings and parents and ideals currently either which is partially why I'm having trouble understanding if this is a ClientAPI issue or Snatcher issue. Was hoping for anyone more familiar with the API could play with Lolisnatcher Droid and see if they can conclude. Or maybe we already know.

**Comment by floogulinc** [comment]
The client API currently does not expose the concept of siblings and parents so there is no way for clients to be aware of them. It appears when doing the search, Hydrus resolves the sibling relationship and searches for the ideal tag. I see the same behavior in Hydrus Web. We also don't get suggestions from the API so any tag suggestions you see in a client have been compiled from tags already seen so in that regard I would suggest using `service_names_to_statuses_to_display_tags` as the source of tags rather than `service_names_to_statuses_to_tags` as the former gives fully resolved siblings/parents.

See #921 and #958

**Comment by seniorm0ment** [comment]
thank you for clarification
