### ISSUE TITLE
Weird duplicate behavior 

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#979]
### Hydrus version

v454

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

win 7 ulitmate 64bit

### Bug description and reproduction

Just to preface this due to the image pool to reproduce the result, I find shock humor funny

ok, I was doing duplicate culling, and wanted to minimize the amount I have to do, so I went with 'potential duplicates' thinking that I could have a nice and easy time figuring out what was higher quality, 20 potentials gave me 38k, 40 gave me 7k, so as a joke I put 100 in thinking there is nothing there, but I had 113 images, so that tells me a single image had 113 potential duplicates. 

I hit the show potential duplicates, thinking I would get 113, because there is no way there are 2 image sets with 100 potentials or more in a pool of 113, what I got was 39 images, I hit it again and I got 4... 

now these images were all duplicates, or related alternates to be specific. but this behavior is weird, after setting them all to related alternates, they go away, and I go down in threshold, down to 60 images, the pool is 81 big, but hitting show potential pairs, all I get are 15 images.

the image set was
"filly twilight telling an offensive joke"
https://derpibooru.org/search?page=2&q=filly+twilight+telling+an+offensive+joke

having this should be able to reproduce the behavior.

I'm not sure if this is a bug, or if this is working as intended, but when I had a >100 potential duplicate search and 113 results were had, I expected 113 images, and when >60 potential duplicates was selected and it came up 81, I expected to see all 81 because neither of those pools of images had enough to facilitate 2 different image pools. 

this isn't really a critical bug, but more something functioning outside of expected behavior.

![client_2021-09-14_14-51-34](https://user-images.githubusercontent.com/2681758/133324525-1238b1ae-1fe1-43ff-aa08-d3be12cc1185.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report. This is tricky and not well documented, but the thing actually being tested in the search here is 'does this file have > x potential dupes', which is slightly different to 'show me the x potential dupes to file y'.

If you are interested in seeing the x potential dupes a file has, try right-clicking one of your results here and hitting _manage->file relationships->view this file's relations->x potential dupes_. This will do that specific search manually and throw them all up on a new page, with that focused file as the first result. (You _may_ need to be in _help->advanced mode_ to see this menu option.)

The reason why your search for 'has more than x' does not always give x results is because 'potential dupe' is not a transitive relationship. A clean file may be below the search threshold with a dupe that has a watermark in the bottom-right corner, and with another that has a watermark in the top left, but the two watermarked files may not be similar enough to each other to also match at the same (for instance, 'exact match') threshold.

Forgive how bad it looks, but this sketch illustrates the way the data is stored:

![dupes](https://user-images.githubusercontent.com/3878678/135183596-0bc1d314-a44c-4625-98c8-b6732f1b1635.png)

Seven red dots represent files, and the black lines each represent a 'potential dupe' pair relationship that has been detected. One file is similar enough to all six others to be worth throwing up in the duplicate filter, but none of the others are so 'middle of the road'. Searching for 'num potential dupes > 5' would give the file on the left, but none of the others, which have, going clockwise, 2, 1, 3, 1, 3, and 2 relationships.

This situation happens more when the search distance is high, leading to high variability of matching and more false positives.

If you right-click and say 'show all x potential dupes' and you don't get x results back, please let me know!
