### ISSUE TITLE
hide, show & remove images/thumbs on download tabs?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#98]
i think we should be easily be able to show and hide images/thumbs in the download tab so it doesnt use resources.
this is really handy if your download queue gets really large as there is no way to clean out already downloaded files from the previews.

i also think we should be able to remove images/thumbs from the download tabs by choice to clean out resources.

if your download queues goes but to high numbers it will try to load all these images every time the tab is open and will slow everything down to a halt.
being able to also hide them should not load the images as that halts the database once it loads it in between downloading files which slows it all down i think.

**Comment by AreFinstad** [comment]
to note, this should also be present in the import tab aswell IMO as the same issues are there aswell when you import too many files at once time it slows everything down and prone it for crashes.

**Comment by HASJ** [comment]
I kinda requested that in a previous post but it is better to be in a different post anyways. +1

When your download queue gets large, how large are we talking about? The client starts breaking down here and I'm not really sure why but I think things start getting bad after 5k files. I have to restart the client constantly because eventually DB errors and later unidentifiable GUI errors will pop up nonstop leading to a crash.

**Comment by AreFinstad** [comment]
i dont really have that much issues with it. the hole ui slows down when i download from more than one tab at a time and so on.
i also have had some issues to close the program and needed to force close it by killing the process.
i have 4 queues up atm and i cant close them or i will lose my queue and find the links i searched for again. 
the queues are at:
Sankaku 28.6k
danbooru:9.9k
gelbooru:16.6k
rule34hentai:42.3k (since its new and need to get the tags)

the first 3 all have been using the same tags to search aswell and you can see why i use sankaku because it get more hits with it XD

but frankly, it doesnt matter if i download anything really as the same issues happen when i just import aswell with the slowdown and locking of the ui. 
have talked to the dev of JMM ( http://japanesemediamanager.github.io/ )
and he said its most likley the SQLite that is causing alot of the issues, i did create another issue about a database where me and "hydrus" talked about some of the issues i have been having.
judging from all other programs that have SQLite is that they all lock up when they are accessing the database, it just cant handle doing more than one thing at a time which just slows things down in general. it doesnt matter what "hydrus" says that it only supports one cpu core. we can still hyperthread it with one core. 

on the end note, i dont have that many issues that you have for some reason. but i havent been downloading as much as i can yet as i still are not nearly done with what i have locally and want to import that before moving to downloads so i dont waste space.

**Comment by HASJ** [comment]
I have both a Sankaku and a Gelbooru tab running.
Sankaku at 5379/30k and Gelbooru at 5417/20k.
Both running essentially the same tags but Gelbooru has only added 400 files since I already had many of those on the DB from Sankaku.
It'd be MUCH, **MUCH** faster if I could get Sankaku/Gelbooru tag database, import it to Hydrus, download the wanted tags with Bulk Image Downloader then import it all back to Hydrus, but I have not found a way to do that.

Indeed the UI hangs whenever files are added to the DB, either by downloading or by importing. At first I thought the tag management was that much taxing but it now seems to be because the DB is getting bigger and bigger. Hydrus also started taking a long time to boot up apparently because of that.

However, I thought SQLite had support for multi-threading and in fact, it does: https://www.sqlite.org/threadsafe.html
Is it just the way Hydrus is built?

**Comment by AreFinstad** [comment]
not sure TBH.
lets hope he looks at the FirebirdDB and so on.
https://github.com/hydrusnetwork/hydrus/issues/63

also think moving over to a merged downloading tab helps alot too maybe for performance. 
https://github.com/hydrusnetwork/hydrus/issues/82

tho i do think most performance gains in general will come from a new database baseline as most programs with SQLite has the same issues where the ui locks up and just runs slow.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
