### ISSUE TITLE
Can't add any rating service (or any service at all)

### ISSUE THREAD

**Issue by KamillaPup** [hydrusnetwork/hydrus#986]
### Hydrus version

457

### Operating system

macOS 11 "Big Sur" (Intel)

### Install method

Installer

### Bug description and reproduction

I can't select any items to add in the manage services screen.

1. Menu | _Services_ -> _Manage Services_
2. Click on _Add_
3. Try to select anything.
<img width="449" alt="Screen Shot 2021-10-13 at 11 15 56 AM" src="https://user-images.githubusercontent.com/26353056/137182460-413dfb1d-b25f-419c-85ed-84637fb35b16.png">

**Comment by KamillaPup** [comment]
This appears to be an issue with every sub menu. I have tried multiple themes and styles and they all prevent me from adding a service :<

**Comment by Zweibach** [comment]
Not sure what you mean by "themes *and* styles", styles are purely cosmetic and don't change how the program actually works so don't matter here.

Hydrus got an update some days ago so we're now on 458, might be worth to see if it's fixed by now becayse yah, sometimes that happens.

As for if the issue persists: Do the buttons just not react or do you get a short freeze or something else that makes it seem like Hydrus is trying to do something but nothing ends up happening?

**Comment by KamillaPup** [comment]
I actually don't like the new menu as it's more a dialog box and not a menu. It requires much more clicks to open the tree then two more clicks to select the item. Is this really the only possible solution?
