### ISSUE TITLE
.clip file thumbnails

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#996]
Clip Studio Paint files (.clip) contain a SQLite database which contains a PNG preview of the file Hydrus can use for a thumbnail. The steps are roughly:

1. Open the .clip file
2. Find the index of `SQLite format 3` in the file.
3. Read everything from that index on
4. Load that as an SQLite db
5. Run this query on the DB: `SELECT ImageData FROM CanvasPreview`
6. The blob you get from the first row should be a preview of the file as a PNG, you can then continue with the regular png thumbnail process.

If you need the dimensions of this PNG, you can get them by selecting `ImageWidth` and `ImageHeight` from the same table. You can also get the real file dimensions from `CanvasWidth` and `CanvasHeight` in the `Canvas` table.

I got this information from a couple of repos that implement parsing of .clip files:
- https://github.com/saitolume/clipstudio.js
- https://github.com/calmery/ExtractClipStudio

Example files for testing can be found here: https://www.clipstudio.net/en/dl/

**Comment by hydrusnetwork** [comment]
Thank you again for this help. I have implemented this for tomorrow's release, and I figured out how to pull resolution too. It was extremely convenient that it was SQLite. On update, your client will schedule metadata rescan for all clips and then a thumbnail generation. My example clip file only produces a white square, so please let me know how you get on with real files, whether it is all blank canvases or if that is the exception.

There's some cool data in here, like layer info, DPI, project settings, and some sort of extendible system to store arbitrary metadata about 3d objects. Shame I am not writing a clip inspector, because they have made it real nice to do!

**Comment by floogulinc** [comment]
I suggest testing with the sample files provided on the site I linked in my original post.
